### ISSUE TITLE
Image view scale type 

### ISSUE THREAD

**Issue by kkrishnan90** [davemorrissey/subsampling-scale-image-view#108]
Hi Dave, 
Hope you're doing good ? Since I used your library on one of my apps (Mr whipped comics - it's in your hall of fame) . I am working on another project where I wanted to use your library again. Here I wanted to display the image view by fitting it to the full screen size. Like we have a scale type attribute for image view (default attribute in android for image view). I tried my level best to scale and fit my images (png images) to the full screen size of the mobile device, it won't let me do by leaving a border around my image view .. Any suggestions from you on this issue would be great. Once again thanks for such an awesome library. Would definitely give credits to your library for every time I use yours in my app.

**Comment by davemorrissey** [comment]
setMinimumScaleType(SCALE_TYPE_CENTER_CROP)

**Comment by kkrishnan90** [comment]
Thanks Dave. But, I don't want the image to be cropped. I want the full sized image to be displayed in my app.

**Comment by davemorrissey** [comment]
It sounds like you're describing the default behaviour so I'm not sure what you mean, are you saying you want the image stretched to fit the screen, ignoring the aspect ratio? Or you want it to start fully zoomed in?

**Comment by vkuba** [comment]
Hi davemorrissey  and kkrishnan90 have You found any solution for this issue?
I have 2 images that are bigger than my screen size for example:
(On the right and left it's the same image)
![2015-10-02 15 13 34](https://cloud.githubusercontent.com/assets/6241523/10247384/ff585e72-6918-11e5-93b2-758d205c747a.png)
I want to have 2 scaled images that looks the same on all devices.
I useed setMinimumScaleType(SCALE_TYPE_CENTER_CROP) on 1st and 2nd SubsamplingScaleImageView but as You can see I get images that doesn't fit to my View size.

**Comment by fukemy** [comment]
Hi i found SCALE_TYPE_CENTER_CROP not working when image size < screen size. eg : my image size is 300-600 while screen size is 720-1024
