### ISSUE TITLE
Bitmap is recycled even if it's used as ImageSource.cachedBitmap(bitmap)

### ISSUE THREAD

**Issue by Yarikx** [davemorrissey/subsampling-scale-image-view#110]
Image loaders (like Picasso), which manage bitmap recycling still can not be used correctly.

**Comment by Yarikx** [comment]
It might be some race issue, as it not always reproducible for the same image.

**Comment by davemorrissey** [comment]
I don't have a test project to try this with or the time to build one. Could you try debugging it, or hopefully someone else will be able to try it.

**Comment by Yarikx** [comment]
Ok, after small debugging I found the case how to reproduce.
The key step is to load 'cached' image second time.

After first call method 'setImage' everything works fine, bitmap is loaded, 'bitmapIsCached' is set to true, and method 'onImageLoaded' is executed, which after all reset flag 'bitmapIsCached' back to false.

If we call 'setImage' with the same image, the view try to call 'reset(true)' method, and as flag 'bitmapIsCached' is false, it recycle source bitmap

**Comment by omgnuts** [comment]
Here's a fix for that if you need it. Check this compare: https://github.com/omgnuts/lib-subsampling-scale-image-view/commit/8e5d2463faae4a377dded254b9a02e394a2313b3. In the above fix, you need to extend the class and use setCacheEnabled(true). Its used on a production app with a few million requests, so its stable. 

Another way would be to allow the caching to be done on a per call basis, but it would change the code too much at this point.

**Comment by davemorrissey** [comment]
This should be fixed now. I'll do a new release as soon as I've cleared up the other open bugs.
