### ISSUE TITLE
Is it possible to get the coordinates of the tap on image?

### ISSUE THREAD

**Issue by zulluadi** [davemorrissey/subsampling-scale-image-view#116]
I would need to get the coordinates of a single tap on a png. Is this possible to do that?

**Comment by zulluadi** [comment]
Just saw viewToSource method which seems to do what I need.

**Comment by OmarHassan25** [comment]
@zulluadi  Could you please help describe how you solved it?

**Comment by zulluadi** [comment]
Hi Omar, sorry but I can't really remember in which project I used this library. From what I've seen, if you need to get the click position on the image, you should use the viewToSourceCoord method
