### ISSUE TITLE
Smoother preview image and actual image transition

### ISSUE THREAD

**Issue by gokhanbarisaker** [davemorrissey/subsampling-scale-image-view#117]
Hi,

Current implementation clears preview image from both memory and ui, then loads the actual image. That introduces delay between image transition.

Is it possible to invalidate view, once the actual image completes decoding, instead of invalidating at the start of actual image load?

Thanks,

**Comment by davemorrissey** [comment]
Are you declaring the correct dimensions of the full size image when you initialise the view? There will only be a delay in transition if the view loads the bounds of the full size image and discovers they don't match the declared dimensions - it then discards the preview image and re-calculates all the state based on the correct dimensions, causing the screen to go black. If you declare the correct dimensions, the transition is seamless.
