### ISSUE TITLE
Support for API level 8 and above

### ISSUE THREAD

**Issue by mohsinhussain** [davemorrissey/subsampling-scale-image-view#122]
Is there any chance for this library to support Android API level 8 and above? Currently it supports for 10 and above. My client strictly wants app compatability for API level 8. Every thing looks perfect but still cannot use it cause of this issue.. :(

Any help?

**Comment by davemorrissey** [comment]
BitmapRegionDecoder is only available in SDK 10 and above. If you don't need to display large images, you can disable tiling and the view may then work for SDK 8 (I can't promise it). If you do need to display large images, you could try using a custom decoder - documentation and a sample implementation can be found here: https://github.com/davemorrissey/subsampling-scale-image-view/wiki/04.-Custom-decoders

Note if you do use RapidDecoder, JPGs will not be properly supported and may be very slow, but it should work well for PNG images.

Officially, this library cannot support anything older than SDK 10.
