### ISSUE TITLE
Add some kind of tapListener

### ISSUE THREAD

**Issue by writtmeyer** [davemorrissey/subsampling-scale-image-view#123]
As Chris Banes has done for his PhotoView a TapListener would be nice.

The method could be something like this in Chris library:
void onPhotoTap(View view, float x, float y);

If you like, I would add this and make the appropriate enhancements to the GestureListener. Please let me know if you're interested in a pull request for this.

**Comment by davemorrissey** [comment]
I'm not sure I really see the need for this. The sample class [AdvancedEventHandlingActivity](https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/sample/src/com/davemorrissey/labs/subscaleview/sample/eventhandlingadvanced/AdvancedEventHandlingActivity.java) shows how to add this functionality. Granted this is more complicated but it also supports much more fine grained control over the behaviour and extension to support a variety of touch events.

**Comment by writtmeyer** [comment]
Since this event is handled within the SubsamplingScaleImageView itself (and then transforming it to an onClick event) I thought it would be a useful extension.

**Comment by davemorrissey** [comment]
I'm going to park this idea for now, as it is possible to do this and more with the samples provided. If there's more demand for this I'll reopen it.
