### ISSUE TITLE
unable to access setpin()

### ISSUE THREAD

**Issue by akhilchandranms** [davemorrissey/subsampling-scale-image-view#124]
I followed your installation and setup guide.I am able setup the custom image view with zooming and panning.Now I want to  add a pin(marker) on image as you shown in the extension example.But I am unable to" import com.davemorrissey.labs.subscaleview.sample.extension.views.PinView;"
the android studio suggestion only shows decoder package, SubsamplingScaleImageView,ImageSource,BuildConfig,ImageViewState. after the " import com.davemorrissey.labs.subscaleview."

**Comment by davemorrissey** [comment]
The PinView class is part of the sample library, it's only a demo and is not included in the release. If you want to use it, you need to copy it to your own project.
