### ISSUE TITLE
unable to use PinView 

### ISSUE THREAD

**Issue by akhilchandranms** [davemorrissey/subsampling-scale-image-view#125]
I added the PinView classinto my project  and custom View PinView into my main xml file.When I tried to run the code it gives me following error:Attempt to invoke virtual method 'void com.mypackagename.PinView.setImage(com.davemorrissey.labs.subscaleview.ImageSource)' on a null object reference.
I am not using fragmentactivity. I need to load the image and pin in the main activity.

**Comment by davemorrissey** [comment]
This is a problem in your code, not the library. Please ask questions like this on stackoverflow.
