### ISSUE TITLE
onImageLoaded not called with 3.4.0

### ISSUE THREAD

**Issue by GreenSkinMonster** [davemorrissey/subsampling-scale-image-view#130]
Hi,

Thank you for this awesome library, it helped me a lot in my project.

I use following code to hide loading progress bar when image is ready.
It worked fine with 3.2.0 and 3.3.0, but not work with latest version 3.4.0
onImageLoaded didn't always get called after image is shown.

```java
wvImage.setOnImageEventListener(new SubsamplingScaleImageView.DefaultOnImageEventListener() {
    @Override
    public void onImageLoaded() {
        progressBar.hide();
    }

    @Override
    public void onImageLoadError(Exception e) {
        progressBar.hide();
        Logger.e("loading error", e);
    }
});
```

Thanks.

**Comment by davemorrissey** [comment]
This will be fixed in the next release
