### ISSUE TITLE
Animation listener

### ISSUE THREAD

**Issue by feher-melos** [davemorrissey/subsampling-scale-image-view#133]
Hi!

Would there be interest in adding a callbacks to listen to the animations?
Similarly to these:
http://developer.android.com/reference/android/view/animation/Animation.AnimationListener.html
http://developer.android.com/reference/android/animation/Animator.AnimatorListener.html.

I need this because I'd like to chain operations AFTER the built-in fling/pan animations are finished.
E.g. to schedule/start new animations without interrupting the already running built-in animations.
Also, would be nice to have a isAnimating() method to see if there is an active animation ongoing.

What do you think?

Cheers,
Gabor

**Comment by davemorrissey** [comment]
Good idea, this had occurred to me recently as well.

**Comment by tonyshkurenko** [comment]
How to check if it's animating now?
