### ISSUE TITLE
The photo possibly show in original orientation, and we would not like it.

### ISSUE THREAD

**Issue by great181855** [davemorrissey/subsampling-scale-image-view#134]
I use this project in my app.  But the photo which be taken by camera app vertically  shows horizontally . there is same way to fix the Bug. 

SubsamplingScaleImageView  exifOrientation is 90

**Comment by davemorrissey** [comment]
Have you tried `imageView.setOrientation(SubsamplingScaleImageView.ORIENTATION_USE_EXIF);` ?

**Comment by great181855** [comment]
OK , thank you . It works correctly . I should read code and commit carefully .

**Comment by great181855** [comment]
OK , thank you . It works correctly . I should read code and commit carefully .
