### ISSUE TITLE
can u add rotate gesture  or setRotationBy & setRotationTo method

### ISSUE THREAD

**Issue by JWBlueLiu** [davemorrissey/subsampling-scale-image-view#135]

**Comment by davemorrissey** [comment]
There's already a setOrientation method and it works in 90 degree increments. A free rotation feature is pretty much impossible with a tiled image, I'm just not that good at trigonometry. I considered it for a while, and realised I would have to rewrite most of the class. So, unfortunately, I won't be attempting it.

**Comment by ntoskrnl** [comment]
that's very sad to hear :(
