### ISSUE TITLE
ViewPager + Transformer problem

### ISSUE THREAD

**Issue by MFlisar** [davemorrissey/subsampling-scale-image-view#136]
I tried to add the transformers found on http://developer.android.com/intl/es/training/animation/screen-slide.html to a `ViewPager`, especially the DepthPageTransformer...

The result is that if I zoom in into on image and slide sometimes the zoom function of your view stops working or the sliding of the viewpager does not work... sometimes the images are already zoomed in when first shown altough that shouldn't be...

Seems like the animations are messing something up...

**Comment by davemorrissey** [comment]
I've reproduced this with DepthPageTransformer, and it's a bug with that transformer. It occasionally leaves the previous page on screen, and still receiving touch events, but with the alpha set to 0. There's probably a way to fix it but I haven't tried.
