### ISSUE TITLE
Multiple SSIVs with SCALE_TYPE_CENTRE_CROP gives different outputs.

### ISSUE THREAD

**Issue by droidekas** [davemorrissey/subsampling-scale-image-view#139]
![device-2015-10-22-170604](https://cloud.githubusercontent.com/assets/6491284/10664327/2abe3a56-78e0-11e5-8500-26390e34672b.png)

Each image is 1 SSIV. My image loading code is

```
SubsamplingScaleImageView imgView = ((SubsamplingScaleImageView) this.findViewById(photoId).findViewById(R.id.image_view));
            imgView.setOrientation(SubsamplingScaleImageView.ORIENTATION_USE_EXIF);
            imgView.setDebug(true);
            imgView.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP);
            imgView.setImage(ImageSource.uri(uri), new ImageViewState(0, new PointF(0, 0), SubsamplingScaleImageView.ORIENTATION_USE_EXIF));
```

They are all the same images.The issues I am facing:

1. I cannot pan the the images till I zoom into them first
   - The left-top image has a lot of the image which is not visible however I cannot pan into that portion of the image till i zoom first.
2. I cannot figure out how the scaling works for the image.
  -The effect that I am looking for is: Either the height or the width of the image should match the dimensions of the container.

**EDIT** : I cannot pan any image before I first zoom into it.

PS:Please let me know if I can give this a better title.I could not come up with anything

**Comment by davemorrissey** [comment]
Try not passing the ImageViewState, you're panning the image to the top left. Without that it should be centered.

**Comment by droidekas** [comment]
I've tried that too.Is there any specific reason I cannot pan the image without zooming?

**Comment by davemorrissey** [comment]
It looks like the two images on the left should be able to pan vertically, care you saying they don't? Can you attach the original image so I can see what its dimensions are?

**Comment by droidekas** [comment]
They only pan horizontally and not vertically,
If i zoom the images,then they pan vertically(for the full length) of the image and horizontally too.

More Context:
I am trying to build a collage view which comprises of 2/3/4 SSIVs:MY individual unit is : 

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#FFFFFF">

    <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:id="@+id/image_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <ImageView
        android:id="@+id/add_image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:src="@drawable/ic_add_grey600_36dp" />
</FrameLayout>

```

I have a custom view group where i add these images and set layout params for each frame based on user selection accordingly calling  `pictureFrame.layout(left,top,right,bottom)`

Attached is the full resolution image

![img_20151013_085004](https://cloud.githubusercontent.com/assets/6491284/10670836/2301420c-7905-11e5-895d-6b85db6aceb4.jpg)

**Comment by droidekas** [comment]
The image does not pan  horizontally completely either

**Comment by droidekas** [comment]
The issue is because I was inflating a custom layout which contained SSIV and then placing them in a  FrameLayout. This isn't directly an issue with SSIV. Please close the issue if the problem is out of scope . Thanks a lot :)

**Comment by davemorrissey** [comment]
Okay, thanks!
