### ISSUE TITLE
Can we perform actions like flip/mirror the bitmap?

### ISSUE THREAD

**Issue by droidekas** [davemorrissey/subsampling-scale-image-view#141]
Ensuring that the image is shown with the sampling involved with this view,is Flip/Mirror possible?

**Comment by davemorrissey** [comment]
It would be quite easy to do that with images small enough to load as a single bitmap, but with tiling it becomes very complicated. The tile grid would need to be swapped or reversed, and matrix calculations would need a big rewrite. To be honest, the maths involved already makes my head hurt and I think this would be a challenge.

**Comment by droidekas** [comment]
Yes a single bitmap would be much easier to handle,but I fear OOMs.However if this is an enhancement that you would consider and could guide me for areas where i could incorporate the feature for tiling.Do let me know :)

**Comment by droidekas** [comment]
And is it possible to respect ExifOrientations like `ORIENTATION_FLIP_HORIZONTAL`?

**Comment by davemorrissey** [comment]
Possibly, yes, any idea why an image would be saved flipped?

**Comment by droidekas** [comment]
But you do not have those constants in your exif array.Because its too big an image and you want to make a collage out of it or edit etc.Hence I would flip->save->read from disk with tiling enabled.

**Comment by davemorrissey** [comment]
I think I misunderstood your question. It would be possible to support that EXIF flag *if* I implemented flip support. It can't just be added now.

**Comment by droidekas** [comment]
Yes,I am referring to supporting those EXIF flags. Thanks!So would that be a considered enhancement?or is it  out of scope?

**Comment by davemorrissey** [comment]
Support for flip/mirror is an enhancement, but a big and complex one, and also likely to be very rarely used so not high priority. It might be a long time before I can get around to doing this.

**Comment by droidekas** [comment]
I sort of needed a quick fix for this,so for now:I create a copy of the flipped bitmap and use SSIV on that.It would be too complex otherwise. Do you see any problem in this approach?

**Comment by davemorrissey** [comment]
If you can do that, great. I'm assuming you can do this on a server.
