### ISSUE TITLE
Can we add multiple markers on the image?

### ISSUE THREAD

**Issue by endl3ssx** [davemorrissey/subsampling-scale-image-view#142]
I have a project in which I would like to use this library, for the excellent zooming and panning functionality.
I have a very large image, which is a map viewed from the front.
I would like to add pins for different events on the map.
I used PinView to add a pin, but if I add multiple pins, only the last one remains on screen.

Can I add multiple pins at once and show them all on the map?

**Comment by davemorrissey** [comment]
PinView is just a demo. You will need to write your own subclass the way you want it.

**Comment by MayurDev** [comment]
Can you give some hint how can achieve ?

**Comment by calvingoc** [comment]
I answered this question in post 236.
