### ISSUE TITLE
Listener is not being called when the image view is not visible

### ISSUE THREAD

**Issue by ntoskrnl** [davemorrissey/subsampling-scale-image-view#143]
In my layout I show progress view before loading the image.
I register image event listener and switch to content view using ViewAnimator. The listener methods are never invoked. 
They are invoked when the image view is shown, but not when it's hidden. Is this an expected behavior?

**Comment by davemorrissey** [comment]
Yes this is expected. The view cannot load appropriately subsampled tiles until it has dimensions, and it doesn't have dimensions until it is visible. It is transparent and displays nothing until the image is loaded so you can overlay a progress bar on top of it (leaving at least some of the view visible) or even underneath it.
