### ISSUE TITLE
How to limit panning of the image?

### ISSUE THREAD

**Issue by ntoskrnl** [davemorrissey/subsampling-scale-image-view#144]
I am implementing a simple image cropper that allows user to rotate and crop the image. The cropping area is a horizontal rectangle in the center of the screen (it can be resized but not moved). I use view.setRotation() to allow the user to rotate an image by an arbitrary angle. User can zoom in/out the image and move it around.

I would like to dynamically set constraints for the image panning, so that the **cropping rectangle is always within the image**.

Or at least I would like to know when image was moved and check its positions relative to the cropping rectangle. I want move image back (with animation) if needed.
What would you recommend?

**Comment by davemorrissey** [comment]
Read through the wiki to see if you can do what you want with the methods provided, but I suspect you'll need to make your own fork of the code and change it significantly to do this.

**Comment by brianguertin** [comment]
I wanted the same thing; I made a cropping tool where you have a circle in the center of the screen and you drag/zoom the image underneath in order to crop it.

@ntoskrnl The only change I had to make to this library was to make the `fitToBounds` `protected` instead of `private`. Then, I was able to get the behaviour I wanted by copying and overriding to account for the view's "padding". Also be sure to use `PAN_LIMIT_INSIDE`.

I only tested it for my use case and it probably breaks other panning modes. I think with a little more testing/tweaking this padding support could be included in the library. Anyway here it is:

```java

    // Extend fitToBounds function to account for view padding
    protected void fitToBounds(boolean center, ScaleAndTranslate sat) {
        if (panLimit == PAN_LIMIT_OUTSIDE && isReady()) {
            center = false;
        }

        PointF vTranslate = sat.vTranslate;
        float scale = limitedScale(sat.scale);
        float scaleWidth = scale * sWidth();
        float scaleHeight = scale * sHeight();

        if (panLimit == PAN_LIMIT_CENTER && isReady()) {
            vTranslate.x = Math.max(vTranslate.x, getWidth() / 2 - scaleWidth);
            vTranslate.y = Math.max(vTranslate.y, getHeight() / 2 - scaleHeight);
        } else if (center) {
            vTranslate.x = Math.max(vTranslate.x, getWidth() - scaleWidth - getPaddingRight());
            vTranslate.y = Math.max(vTranslate.y, getHeight() - scaleHeight - getPaddingBottom());
        } else {
            vTranslate.x = Math.max(vTranslate.x, -scaleWidth);
            vTranslate.y = Math.max(vTranslate.y, -scaleHeight);
        }

        float maxTx;
        float maxTy;
        if (panLimit == PAN_LIMIT_CENTER && isReady()) {
            maxTx = Math.max(0, getWidth() / 2);
            maxTy = Math.max(0, getHeight() / 2);
        } else if (center) {
            maxTx = Math.max(0, getPaddingLeft());
            maxTy = Math.max(0, getPaddingTop());
        } else {
            maxTx = Math.max(0, getWidth());
            maxTy = Math.max(0, getHeight());
        }

        vTranslate.x = Math.min(vTranslate.x, maxTx);
        vTranslate.y = Math.min(vTranslate.y, maxTy);

        sat.scale = scale;
    }
```
