### ISSUE TITLE
Question - Is there something like onImageLoadedListener()?

### ISSUE THREAD

**Issue by ehdtkqorl123** [davemorrissey/subsampling-scale-image-view#145]
I am trying to get its pixel size (width/height) immediately right fter importing image source from asset/ ,but I don't get what is expected.

SubsamplingScaleImageView imageView = (SubsamplingScaleImageView)findViewById(id.imageView);
imageView.setImage(ImageSource.asset("squirrel.jpg"));
Log.d("log", "imageView.getSWidth() + "/" + imageView.getSHeight());

This returns 0/0. 

Seems like this is because the image is not loaded when I call Log.d(...).
The workaround for me is to use postDelayed like

imageView.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (imageView.isReady()) {
                    Log.d("log", imageView.getSWidth() + "/" + imageView.getSHeight());
                }
            }
        }, 1000);

But Instead of this, is there a better way to get the size?
Hope there is load Listener or something...

**Comment by davemorrissey** [comment]
Yes, it's all in the wiki.
