### ISSUE TITLE
How to prevent SubsamplingScaleImageView from obtaining focus and getting events?

### ISSUE THREAD

**Issue by bnelson1000** [davemorrissey/subsampling-scale-image-view#147]
There are a few places in my app where I want to use your library to display a static image that does not allow the user to interact with the image at all. One place is a simple welcome image and the other is in a grid. The xml for the welcome image is shown below. Even with the android:focusable and app:panEnabled and zoomEnable attributes all set to false, I can still double-tap on the image and pinch/pan the resulting zoomed image. In the grid, I want to display a preview of the image and set an AdapterView.OnItemClickListener() to detect click events on the preview to launch a fully interactive view of the image, but the item click isn't working, and I suspect it is because the SubsamplingScaleImageView is handling the events.  

Do I need to subclass the SubsamplingScaleImageView to make this work, or am I doing something incorrectly in the XML?

        <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
            android:id="@+id/welcome_image"
            android:layout_width="225dp"
            android:layout_height="225dp"
            android:layout_below="@+id/welcome_text"
            android:paddingBottom="16dp"
            android:layout_centerHorizontal="true"
            android:focusable="false"
            android:focusableInTouchMode="false"
            app:panEnabled="false"
            app:zoomEnable="false"
            app:quickScaleEnabled="false"/>

Thanks,

Bill

**Comment by davemorrissey** [comment]
It's `zoomEnabled`, not `zoomEnable`
