### ISSUE TITLE
Zooming "catches" on edges

### ISSUE THREAD

**Issue by plusCubed** [davemorrissey/subsampling-scale-image-view#148]
Here's a video of what I'm talking about: https://youtu.be/to_BOMs7H2U

From my initial debugging, what appears to happen is that the predicted `vTranslate` coordinates in `onTouchEvent()` are off because of the centering in `fitToBounds()`, causing the `vCenter` coords to be off and the `vTranslate` coords to be corrected in `fitToBounds()` to that edge. This would explain why the further off the center, the worse the "catching" is.

**Comment by davemorrissey** [comment]
It has to be this way because the image should be centered in the dimension it doesn't fill. Otherwise when you zoom out you could leave the image off center. I don't plan to change this behaviour.

**Comment by plusCubed** [comment]
Hmm... I suppose this is a question of whether to maintain the user's initial intended center (and "catch" to readjust because of the centering) or to change to the new apparent center as the photo's width/height becomes larger than the viewport. Google Photos takes the second approach so the zoom seems unaffected by the edge and more smooth.

**Comment by plusCubed** [comment]
Google Photos appears to "catch" when zooming out to center the photo, but readjusts to the new center while zooming in so there's no catching.

**Comment by abhi385** [comment]
how to make zooming with out limit.

**Comment by davemorrissey** [comment]
I've improved the behaviour in 3.6.0.
