### ISSUE TITLE
Multi-Touch Gestures

### ISSUE THREAD

**Issue by santafebound** [davemorrissey/subsampling-scale-image-view#149]
This is less an issue than a suggestion. Would love to see Multi-Touch Gesture support so that I can rotate my images free-hand as opposed to in lock-step fashion as per the rotation button provided. I use your library in my Android app, Hypercycle (http://www.hypercycle.co/attributions.html). Works great!

**Comment by davemorrissey** [comment]
Unfortunately a free rotation feature is essentially impossible, the maths is just too complicated and the tile grid won't really work for anything other than 90 degree increments.

**Comment by santafebound** [comment]
Check out this repo: https://github.com/siddhpuraamitr/MultitouchWithDynamicAddandRemove

I get that it's probably built on completely different principles, but who knows. Some inspiration at least.

**Comment by davemorrissey** [comment]
Yes this is completely different. It doesn't need a tile grid for displaying large images.
