### ISSUE TITLE
subsampling-scale-image-view scale the picture incorrectly after the device rotation

### ISSUE THREAD

**Issue by duanju** [davemorrissey/subsampling-scale-image-view#155]
I faced issue when i rotate the screen. The picture cannot be reset to their original scale status. 
For example, when i open my app the screen look like the figure 1. when i rotate the screen, it looks like the figure 2. So far, all things are OK. However when i rotate screen back, the picture is scaled as figure 3 shows. Is there any API can be used to force the image back to the status as figure 1?

figure 1.
![capture_1](https://cloud.githubusercontent.com/assets/7081847/11556716/8f5be822-99e3-11e5-8f3a-fe7368fada63.PNG)

figure 2.
![capture_2](https://cloud.githubusercontent.com/assets/7081847/11556718/9252b0ec-99e3-11e5-8e2a-2d3561fb3f19.PNG)
figure 3.
![capture_3](https://cloud.githubusercontent.com/assets/7081847/11556728/9e7019f0-99e3-11e5-9fe5-f6471bb65e9e.PNG)

I use subsamplingscalimageview in a viewpager and have device orientation configuration in AndroidManifest.xml like this  android:configChanges="orientation|keyboardHidden|screenSize"

Any helps will be appreciated.

**Comment by davemorrissey** [comment]
The view attempts to preserve the current scale and center if its size is changed, so that's what's happening here. There's no single "correct" behaviour for this, I just felt this was most appropriate.

If you want to have different behaviour on size changed, create a subclass and override `onSizeChanged`. Alternatively, allow the view to be recreated and see the wiki page for instructions on how to set the scale and centre after an orientation change.

**Comment by duanju** [comment]
Thanks to reply this. The key of this issue is that when i add the configuration android:configChanges="orientation|keyboardHidden|screenSize" in my AndroidManifest.xml file, subsampling-scale-image-view could not detect the rotation automatically.

**Comment by davemorrissey** [comment]
If adding that attribute results in the view's `onSizeChanged` method not being called, then you will have to call it yourself. However it looks like it is being called and doing what it should, so you need to override it if you want different behaviour. Alternatively, I recommend removing that attribute.

**Comment by duanju** [comment]
Davemorrissey, you are right. I have resolved this problem by your comments. You did a great job. Thank you very much.

**Comment by rafaelekol** [comment]
I have same issue.
I tried your suggestion to extend your class and reset image scale onSizeChanged. It helped me to reset the image on rotation, but now I got another problem. My images opens in zoomed state. What I did wrong?

```
import android.content.Context;
import android.util.AttributeSet;

import com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView;

public class CustomSubsamplingScaleImageView extends SubsamplingScaleImageView {

    public CustomSubsamplingScaleImageView(Context context, AttributeSet attr) {
        super(context, attr);
    }

    public CustomSubsamplingScaleImageView(Context context) {
        super(context, null);
    }

    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        //reset image scale to original on image rotation
        resetScaleAndCenter();
    }
}
```
