### ISSUE TITLE
Frame drops with specific image

### ISSUE THREAD

**Issue by jamie-beardedhen** [davemorrissey/subsampling-scale-image-view#157]
I am encountering severe jank when using [this image](http://i.imgur.com/nBjwqcv.png) on a 1st Gen Moto-G running Api 22. The jank begins whenever the View is displaying part of the right-hand half of the image.

Systrace shows an "Expensive Bitmap Upload" alert for a 2655x2048 texture, which takes around 100-150ms to execute. Weirdly, there is no jank at all when the image orientation is set to SubsamplingScaleImageView.ORIENTATION_90, and I haven't been able to reproduce this on other devices yet. Other large images display fine, it just seems to be this size which causes problems.

Any help with figuring out what's happening would be much appreciated - thanks for an awesome library! If more details are required I'll be happy to add them.

**Comment by davemorrissey** [comment]
Depending on screen resolution, image size and orientation, the view will sometimes load very large single tiles, up to the canvas maximum bitmap size. It seems that in this case, the device has a maximum bitmap size of 4096x4096 but isn't actually powerful enough to handle that.

You could try forking the project and changing the maximum tile size to 2048 or smaller, but this would obviously affect other devices with the same screen size/resolution when you only have a problem with this one.

**Comment by jamie-beardedhen** [comment]
Thanks for the quick response. Would there be any disadvantages to setting the default maximum tile size to something small e.g. 512x512? I'm thinking it would be useful if this could be configured when loading the image, via some method like setMaxTileSize(int size). I'll update this issue after I've tried this change out.

**Comment by davemorrissey** [comment]
Generally larger tiles are better, if you go as small as 512x512 the initial load will take longer (but perhaps not noticeably) and the view will have to load a lot more tiles as you scroll around. Probably 1024x1024 is the minimum sensible size, but I haven't done many experiments with this.
