### ISSUE TITLE
Tile caching

### ISSUE THREAD

**Issue by tomlocks** [davemorrissey/subsampling-scale-image-view#158]
Hi, 

first thanks for great library. I'm using it in my project, but I have one question. I have a fragment with your view, which contains a map in .png format. But the problem is that the tiles are created every time i come back to this fragment or during a screen rotation. Assuming that I don't change my map content during entire application lifecycle is it possible to cache the tiles somewhere and then reuse them? I would like to use them again to avoid the delay.

Thanks for help

**Comment by davemorrissey** [comment]
Doing this might not make the view load any faster. The initialisation of BitmapRegionDecoder is relatively slow, then reusing it to load tiles is fast, and replacing that with individual bitmaps that have to be initialised and loaded every time the user pans and zooms might be slower. If you want to do it this way, try something like TileView (https://github.com/moagrius/TileView).
