### ISSUE TITLE
about PDF rendering

### ISSUE THREAD

**Issue by iamyellow** [davemorrissey/subsampling-scale-image-view#160]
hey! 1st of all a big thank you for your awesome job with this library!

2nd, this is a question, not an issue at all... I've used it in order to render a pdf magazine from our server. each page is a big image I'm downloading to a local file and then displaying as the examples. btw, I'd like to use the PDF renderer API* provided in  >= 4.4 devices. as far as I understand, it seems the rendering is done 'against' a bitmap. so... do you think we're going to find memory problems or some kind of problems?

thanks in advance!

* http://developer.android.com/intl/es/reference/android/graphics/pdf/PdfRenderer.html

**Comment by davemorrissey** [comment]
To be honest, I don't know, I've never looked at that API before. I guess you'll have to be careful with the sizes of bitmap you create to render the page into. The docs suggest you can do tiling with it, maybe you can even write a custom decoder implementation for this library.
