### ISSUE TITLE
Any plan on new version?

### ISSUE THREAD

**Issue by mariotaku** [davemorrissey/subsampling-scale-image-view#165]
Current version (3.4.1) has leaks for InputStream #131 , is it possible to have a new release version?

**Comment by mariotaku** [comment]
Bumping this issue up.

**Comment by franciscofranco** [comment]
Yeah I was kinda hoping for a new release too since I reported that bug and saw the fix :)

**Comment by davemorrissey** [comment]
3.5.0 released
