### ISSUE TITLE
SCALE_TYPE_CENTER_CROP + START

### ISSUE THREAD

**Issue by tarekk** [davemorrissey/subsampling-scale-image-view#166]
Is it possible to have SCALE_TYPE_CENTER_CROP_START thing ?

the same as CENTER_CROP but the image starts from the top not from the center ??

**Comment by davemorrissey** [comment]
This will work:
    imageView.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP);
    imageView.setImage(ImageSource.asset(asset), new ImageViewState(0, new PointF(0, 0), 0));

**Comment by wengwyue** [comment]
thanks, this work for me!
