### ISSUE TITLE
Image doesn't load with deepzoom enabled

### ISSUE THREAD

**Issue by knightry** [davemorrissey/subsampling-scale-image-view#168]
e.g. https://i.imgur.com/hWwlWgI.jpg

@laurencedawson [suggested](https://www.reddit.com/r/redditsync/comments/407kf1/image_doesnt_load_if_deep_zoom_is_enabled/cys62mq) this was an issue with deepzoom and not reddit sync.

Happy to provide additional details if necessary

**Comment by davemorrissey** [comment]
Unfortunately I can't do anything about this. My view uses BitmapRegionDecoder, a standard class in Android, and that uses the Skia library to decode images. The bug is in Skia, so it should be reported to them.
