### ISSUE TITLE
[q] using the library for image overlays and gesture-based placement

### ISSUE THREAD

**Issue by vladp** [davemorrissey/subsampling-scale-image-view#170]
Hello,
apologies if there is a different place to ask a generic question.
I am building a facility in my app that would allow a user to place one image on top of another, and use drag/drop to point exactly the location of the placement.  Then a user should be able to rotate and scale in/out the top image in place (while still seeing behind it the bottom image).

Wanted to know if  this library would be a good foundation solution for the above. As I particularly like its ability to handle large image size, and that it has a number of extension points.

Of course, if you have any suggestions on what extension points could be useful for implementing teh above -- would appreciate them as well.

thx in advance

**Comment by davemorrissey** [comment]
That's difficult to answer without understanding exactly what you want to do. If you look through the wiki and the sample code, you should be able to see whether you can do what you need to with this library.
