### ISSUE TITLE
Hello,may I ask one questions to you?

### ISSUE THREAD

**Issue by cxu123** [davemorrissey/subsampling-scale-image-view#172]
At SubsamplingScaleImageView.java ,1350 Line:
you code is:
 while (subTileWidth + xTiles + 1 > maxTileDimensions.x || (subTileWidth > getWidth() * 1.25 && sampleSize < fullImageSampleSize)) {  ...}

why not 

 while (subTileWidth > maxTileDimensions.x || (subTileWidth > getWidth() * 1.25 && sampleSize < fullImageSampleSize)) { ...}

Can you tell me why  need use "subTileWidth + xTiles + 1"  ?

![image](https://cloud.githubusercontent.com/assets/12625804/12320918/46d243b6-bae6-11e5-9a50-1cf363df2821.png)

**Comment by davemorrissey** [comment]
That solved a rounding problem that resulted in the last few pixels of the image not being shown.

**Comment by cxu123** [comment]
Thank you very much.
