### ISSUE TITLE
Zooming image and pin

### ISSUE THREAD

**Issue by roby222** [davemorrissey/subsampling-scale-image-view#174]
Hi dave,

I'm playing around with PinView sample. I've added a pin, but I want that the pin scale likes the foreground image (actually the pin don't scale)

How can I do?  Any tips?

Thanks
R.

**Comment by davemorrissey** [comment]
Just get the current scale and draw the pin scaled accordingly in your onDraw method

**Comment by roby222** [comment]
finally I've solved thanks! but I replaced canvas ( and drawing bitmaps ) with  custom views.
With canvas approach the draw/scale bitmaps is too much slow, in particular if you scale a big bitmap Pin. (the drag is very laggy )
Instead of scaling, I programmatically edit the height, width and x,y coords of the view.

**Comment by hunterand1** [comment]
@roby222  plz send me your solve and thnx so match

**Comment by rpisu** [comment]
@hunterand1 I don't promise nothing, but in the next weeks, I will try to put together a sample using it.sephiroth.android.library.imagezoom as Image Lib for zooming and pan. A custom "Volley NetworkImageView " for the pin and background.
keep in touch

**Comment by hunterand1** [comment]
@rpisu i need create costum map what libaray need?

**Comment by roby222** [comment]
@hunterand1 I don't promise nothing, but in the next weeks, I will try to put together a sample using it.sephiroth.android.library.imagezoom as Image Lib for zooming and pan. A custom "Volley NetworkImageView " for the pin and background.

I don't think this solution works with maps ( tiles ).
It only works if you have a background bitmap (as an unique bitmap), and one or multiple pins (NetworkImageView) that you inject dinamically
