### ISSUE TITLE
Does not fit nor zoom on small image

### ISSUE THREAD

**Issue by ivanmestre** [davemorrissey/subsampling-scale-image-view#179]
When using an image than is smaller than the container, the image is not fitted to the containers size and it does not allow zoom.

**Comment by inorichi** [comment]
You have to increase the maximum allowed scale. See `setMaxScale` and `setMaximumDpi`.

**Comment by ivanmestre** [comment]
I solved it by overriding the onImageLoaded method and doing this inside it:

`setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
        float maxDpi = getResources().getDisplayMetrics().densityDpi * getSHeight() / getHeight();

        setMaximumDpi((int)maxDpi);
        setMinimumDpi((int) maxDpi / 3);`

Now the image is scaled correctly, but it is not centered in the view.

**Comment by ivanmestre** [comment]
I managed to center it by calling resetScaleandCenter()

**Comment by hendrawd** [comment]
what is getSHeight() and getHeight()?
