### ISSUE TITLE
Intermittent Failure To Render Image Asset

### ISSUE THREAD

**Issue by mpkuth** [davemorrissey/subsampling-scale-image-view#181]
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:background="@color/beige">

    <ProgressBar
        android:indeterminate="true"
        android:layout_gravity="center"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>

    <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        android:id="@+id/img_menu"/>

</FrameLayout>
```

```
public class MenuActivity extends AppCompatActivity implements
        SubsamplingScaleImageView.OnImageEventListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.act_menu);

        SubsamplingScaleImageView imgMenu = (SubsamplingScaleImageView) findViewById(R.id.img_menu);
        imgMenu.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP);
        imgMenu.setImage(ImageSource.asset("menu.jpg"), new ImageViewState(0, new PointF(0, 0), 0));
        imgMenu.setOnImageEventListener(this);
    }

    @Override
    public void onReady() {
        Log.d(getClass().getSimpleName(), "onReady");
    }

    @Override
    public void onImageLoaded() {
        Log.d(getClass().getSimpleName(), "onImageLoaded");
    }

    @Override
    public void onPreviewLoadError(Exception e) {
        Log.e(getClass().getSimpleName(), "onPreviewLoadError");
        e.printStackTrace();
    }

    @Override
    public void onImageLoadError(Exception e) {
        Log.e(getClass().getSimpleName(), "onImageLoadError");
        e.printStackTrace();
    }

    @Override
    public void onTileLoadError(Exception e) {
        Log.e(getClass().getSimpleName(), "onTileLoadError");
        e.printStackTrace();
    }

}
```

4 out of 6 times loading the image asset results in the following warnings (but no errors?) and nothing rendered in the view. The 2nd and 6th attempts (seems random) to load the image asset resulted in the image being displayed as expected an no warnings were seen in the logs.

```
02-02 17:24:09.623 10160-10247/com.preo.client D/MenuActivity: onReady
02-02 17:24:09.623 10160-10247/com.preo.client D/MenuActivity: onImageLoaded
02-02 17:24:09.623 10160-10247/com.preo.client W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (3098x11516, max=8192x8192)
02-02 17:24:09.623 10160-10247/com.preo.client W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (3098x11516, max=8192x8192)
02-02 17:24:09.623 10160-10247/com.preo.client W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (3098x11516, max=8192x8192)
```

Unfortunately, the image I'm using can't be uploaded publicly. However, I was able to reproduce the issue with another tall and skinny jpg (1781x10800) that I created from 4 random pages of another doc.

Using imagemagick: convert -density 300 2013-17_USAH_Rulebook.pdf[2-5] -quality 90 -append test.jpg
Doc Source: http://assets.ngin.com/attachments/document/0042/4244/2013-17_USAH_Rulebook.pdf
![test](https://cloud.githubusercontent.com/assets/2456092/12767111/61105fc6-c9d5-11e5-8ed0-176458f3f2ac.jpg)

com.davemorrissey.labs:subsampling-scale-image-view:3.4.1
Samsung Galaxy S6 Active
Android 5.0.2
minSdkVersion 16
targetSdkVersion 23

I am concerned by the lack of consistency (I would expect it to either load or not load every time) and the fact that none of the OnImageEventListener error callbacks are triggered when it fails.

**Comment by davemorrissey** [comment]
I'm very surprised the behaviour is non-deterministic. I can't reproduce this on my 5X, could you step debug the `initialiseTileMap` method and let me know what you see?

You don't get any error callback because the image has loaded successfully and the error occurs in rendering, and that isn't reported to the onDraw method. There's no way to know it happened.

**Comment by mpkuth** [comment]
I got back to this today and was only able to reproduce twice in about an hour of trying. Unfortunately, never under the debugger. I swear it was more reproducible last time. Anyway, I might try again another day but unless I can reproduce it reliably again there's probably not much to be done.
