### ISSUE TITLE
Zoom issue while freehand drawing

### ISSUE THREAD

**Issue by anubhaw2091** [davemorrissey/subsampling-scale-image-view#182]
Hi dave,
Thanks for this awesome library.

While freehand drawing if we zoom the image, i.e two finger gesture, we can only zoom only once. What if we want to zoom at a place and then go to another corner to draw a line?
Is it possible?

My xml code:

           <com.example.mks.selectimage.FreehandView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/image"
            />

I implemented multiple lines drawing in a freehand screen. So once I drew a line, I can't reposition image to another position to draw a another line.

Thanks.

**Comment by davemorrissey** [comment]
I'm really sorry but I can't provide this kind of support, what you want to do is possible but the sample is the most basic example possible for illustration purposes only, and is not supposed to be feature complete. You will need to implement your own gesture detection.
