### ISSUE TITLE
component not showing with 2 layouts side by side

### ISSUE THREAD

**Issue by ivanmestre** [davemorrissey/subsampling-scale-image-view#184]
Hi, i'm using this library to display a map.
I have it placed inside a RelativeLayout next to another relative layout. It is inside a RelativeLayout because I need to place son buttons on top of the image.
Here is the xml:

`

    <RelativeLayout
        android:id="@+id/navigation_drawer"
        android:layout_width="200dp"
        android:layout_height="match_parent"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:background="@android:color/black">

    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/view_area_main_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_toLeftOf="@id/navigation_drawer"
        android:layout_toStartOf="@id/navigation_drawer">

        <com.gm3dia.android.buildertodo.view.PinView
            android:id="@+id/pin_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:longClickable="true" />

    </RelativeLayout>
`

Both are inside another RelativeLayout.
But the Imageis not showing. If I set the visibility of the first layout to GONE on runtime it shows. 
What can be happening.

**Comment by davemorrissey** [comment]
I think this is because you're trying to put the second RelativeLayout to the left of the first one, but the first one is already on the left of the screen so it won't show. It might be better to try StackOverflow for questions like this because it's not related to this library and you'll get a faster answer.
