### ISSUE TITLE
More notes

### ISSUE THREAD

**Issue by alexiscanny** [davemorrissey/subsampling-scale-image-view#187]
Hi davemorrissey,
I'm actually using the subsampling-scale-image-view and I would like to change the note.
I've 3 pics and for each pic I want change the note...so far I did:
`
@Override
        public Fragment getItem(int position) {
            ViewPagerFragment fragment = new ViewPagerFragment();
            fragment.setAsset(IMAGES.get(position));

            if (position==0) {
                findViewById(R.id.note1).setVisibility(View.VISIBLE);
                findViewById(R.id.note2).setVisibility(View.INVISIBLE);
                findViewById(R.id.note3).setVisibility(View.INVISIBLE);
                TextView descriptionnote = (TextView) findViewById(R.id.note1);
                descriptionnote.setText(descriptionPhoto[0]);

            }

                if (position == 1) {
                    findViewById(R.id.note1).setVisibility(View.INVISIBLE);
                    findViewById(R.id.note2).setVisibility(View.VISIBLE);
                    findViewById(R.id.note3).setVisibility(View.INVISIBLE);
                    TextView descriptionnote2 = (TextView) findViewById(R.id.note2);
                    descriptionnote2.setText(descriptionPhoto[1]);
                    fragment.setAsset(IMAGES.get(position));

                }
                     if (position == 2) {

                        findViewById(R.id.note1).setVisibility(View.INVISIBLE);
                        findViewById(R.id.note2).setVisibility(View.INVISIBLE);
                        findViewById(R.id.note3).setVisibility(View.VISIBLE);
                        TextView descriptionnote3 = (TextView) findViewById(R.id.note3);
                        descriptionnote3.setText(descriptionPhoto[2]);
                         fragment.setAsset(IMAGES.get(position));
                     }

            return fragment;
        }
`

But it doesn't works properly...
Do you have any suggestion?
Thanks a lot.
Alessio

**Comment by davemorrissey** [comment]
I'm sorry, I can't provide support for developer's customisations and the projects they build around this library. If you believe there is a problem with the library itself, please provide a description - "it doesn't work" is not enough to help me troubleshoot.

**Comment by alexiscanny** [comment]
I changed the code...and it works how I want to work....soon I will try to posted so someone can used.
Thanks
