### ISSUE TITLE
Bitmap from Picasso is very slow

### ISSUE THREAD

**Issue by timkoers** [davemorrissey/subsampling-scale-image-view#188]
When dragging and zooming the image that has been loaded with Picasso (and I think is in memory) is very slow.
The zooming occurs with big steps and is very shockery. The dragging also shocks alot.
I don't think this is how it is supposed to be :-P

**Comment by vavan4567** [comment]
I am using Glide, and it works very fast. Try it

**Comment by timkoers** [comment]
@va I think that switching to Glide costs more time than fixing the slow dragging problem. Could you send an example URL of your image? I fetch mine from Unsplash.com

**Comment by davemorrissey** [comment]
If you're displaying large images by providing a bitmap, the view can't do subsampling and you may get poor performance. Please see https://github.com/davemorrissey/subsampling-scale-image-view/wiki/X.-Using-with-Picasso

**Comment by Alxzu** [comment]
@vavan4567 can u show Glide's code? Thanks
