### ISSUE TITLE
Extract an image from SubsamplingScaleImageView?

### ISSUE THREAD

**Issue by danijelb** [davemorrissey/subsampling-scale-image-view#19]
I am using SubsamplingScaleImageView to allow users to crop a photo by using gestures. I modified the library to overlay additional elements over the image (a logo and a tint). Is there any easy way to extract the photo from the view while preserving the zoom factor, position of the image and the overlays?

I've tried using buildDrawingCache()/getDrawingCache() but it's not a good solution because the final image size depends on the resolution of the screen. On a Full HD I get 1080x1080, but on lower res screens I can get resolutions like 480x480 which is not enough since I need at least 800x800.

**Comment by osrl** [comment]
How do I get the `ImageRegionDecoder` or create a new `BitmapRegionDecoder ` instance? Does this method give me my overlays? What do I apply my overlays to?

**Comment by davemorrissey** [comment]
You have to do this manually in a subclass. Decode the image yourself and draw the overlays on it. All the methods you need to do this are documented in the wiki. Bear in mind you need to be careful not to run out of memory.

**Comment by muhammad-ameen** [comment]
i want bitmap fit to my imageview, how i zoom bitmap programmatically

**Comment by ashishmahla** [comment]
It should be obvious from the amount of activity on this issue but just to reiterate, we NEED a method to get the displayed bitmap. It would be awesome if it were built in the library. Please add this feature if possible.

**Comment by deepakkaku** [comment]
Can we get a working solution to this at least? I can't find a way to extract the bitmap with layers even after going through each every duplicate issues marked here.
