### ISSUE TITLE
How to use this with Bitmap image ??

### ISSUE THREAD

**Issue by obaidjatoi** [davemorrissey/subsampling-scale-image-view#190]
Can you please tell me how to set Bitmap to this image view ? 
Because this is not working

ivPicToDisplay.setImage(BitmapFactory
                        .decodeFile(imgDecodableString));

also this is not working

ivPicToDisplay.setImage(bitmap);

Can you please tell me how can i achieve this ?

**Comment by davemorrissey** [comment]
`view.setImage(ImageSource.bitmap(bitmap));`
