### ISSUE TITLE
How to do fitxy?

### ISSUE THREAD

**Issue by SerhatHacioglu** [davemorrissey/subsampling-scale-image-view#191]
I use 618*17296 picture.
It looks i.hizliresim.com/MpgnAg.png
but i want hizliresim.com/Wk9ML8
how can i do this?

**Comment by davemorrissey** [comment]
Please read https://github.com/davemorrissey/subsampling-scale-image-view/wiki/07.-Configuration - look for SCALE_TYPE_CENTER_CROP.
