### ISSUE TITLE
Custom decoder is not working

### ISSUE THREAD

**Issue by timkoers** [davemorrissey/subsampling-scale-image-view#193]
I have followed the solution for the Picasso image decoder and the decoder is not working.

I've set them using 

imageView.setBitmapDecoderClass(PicassoDecoder.class);
        imageView.setRegionDecoderClass(PicassoRegionDecoder.class);

And both of the classes contain the exact same code as [this](https://gist.github.com/davemorrissey/e2781ba5b966c9e95539) gist. I have also put a Log.d line inside the decode and decodeRegion methods, but none of them are visible in the logcat.

**Comment by davemorrissey** [comment]
Neither of these classes have zero-argument constructors, so you need to use the `setRegionDecoderFactory` and `setBitmapDecoderFactory` methods.

**Comment by timkoers** [comment]
Still not working. It looks like the image view is not using the decoders at all.

**Comment by bmis0002** [comment]
Any update on this issue?
