### ISSUE TITLE
Option to change the default timing for animations

### ISSUE THREAD

**Issue by laurencedawson** [davemorrissey/subsampling-scale-image-view#194]
It would be great if we could override the default animation duration.

At the moment I think it's at 500 / 550 ms. Feels a little more natural at 220.

Cheers

**Comment by davemorrissey** [comment]
Released in 3.5.0

**Comment by laurencedawson** [comment]
Working great. Thanks for this.

**Comment by AlexVPerl** [comment]
Great addition to the library, thanks. Any quick example or explanation of values and what they do would be great too 👍 Specifically ZoomDuration, ZoomScale & ZoomStyle :)

**Comment by davemorrissey** [comment]
It's all here: https://github.com/davemorrissey/subsampling-scale-image-view/wiki/07.-Configuration

**Comment by AlexVPerl** [comment]
Awesome - thanks!
