### ISSUE TITLE
Scaling view on top of SubsamplingScaleImageView

### ISSUE THREAD

**Issue by lukasz-gosiewski** [davemorrissey/subsampling-scale-image-view#195]
Hello,
I'm writing small app that shows images on ViewPager. In one page there is one SubsamplingScaleImageView + random amount of VideoViews. Moreover i need to draw these VideoView in specfied point of original image. Everything works fine, but I need to scale this point to fit to displayed image size. For now i just get the SubsamplingScaleImageView width and height, divide original image width and height by them and got the scale. However this scale is not precise because size of SubsamplingScaleImageView is not size of displayed image (image is set to adjustViewBounds so width is ok but height not, or in the other way - it depends). The point is - How can i get real precise size of displayed image ? (imageView.getDrawable().getIntrinsicHeight() in normal ImageView)
Thank you for your answer !

**Comment by lukasz-gosiewski** [comment]
Fast way to make this for others: 
Calculate proportion of original x / y if x is ok, or y / xif y is ok.
Then get real size by multplying good size by proportions (if u have good width then multiply it by proportions and u have good y)
Calculate "margin" size by divide (ssimageiew - image) by 2. (x or y, it depends which one u got good)
At the end just move your view by this "margin" size.

**Comment by davemorrissey** [comment]
I don't really follow this, but have you read the wiki? There are lots of methods to help you do things like this.
