### ISSUE TITLE
How can I get Bitmap in an area of this view?

### ISSUE THREAD

**Issue by junyuecao** [davemorrissey/subsampling-scale-image-view#196]
What I want is get Bitmap of the source image providing an area position and size on this view.
How can I achieve that?

**Comment by davemorrissey** [comment]
Take a look at the wiki, especially the page below. You can use methods like `viewToSourceCoord` to determine the visible area of the image, then use BitmapRegionDecoder to get that area from the source.

https://github.com/davemorrissey/subsampling-scale-image-view/wiki/10.-Extension
