### ISSUE TITLE
Bitmap too large to be uploaded into a texture (2880x1620, max=2048x2048)

### ISSUE THREAD

**Issue by SaravanarajaGITHUB** [davemorrissey/subsampling-scale-image-view#197]
i used this code to show the image whichis located in drawable 
imageView.setImage(ImageSource.resource(R.drawable.batman));

when i try to run it in ma device image not visible and in log i see the running message (Bitmap too large to be uploaded into a texture (2880x1620, max=2048x2048))

**Comment by franciscofranco** [comment]
Because your device doesn't support bigger textures than 2048x2048 you can't load one into memory. That's precisely the idea of this lib, offloads you from that job and downsamples the picture.

**Comment by SaravanarajaGITHUB** [comment]
After added this piece of code i can view the image with out any problem

BitmapFactory.Options bitmapOptions = new BitmapFactory.Options();
            bitmapOptions.inDither = true;
            bitmapOptions.inPreferredConfig = Bitmap.Config.RGB_565;
            bitmapOptions.inScaled = false;
            Bitmap bitmapImage = BitmapFactory.decodeResource(getResources(), imageId , bitmapOptions);

imageView.setImage(ImageSource.bitmap(bitmapImage));

I would like to know what happening in this code and this code is the perfect solution for my problem?

**Comment by davemorrissey** [comment]
Your solution is more likely to cause this problem than your original code, so I don't know why you aren't seeing the same error with the new code. Can you attach the image you're displaying please?

**Comment by davemorrissey** [comment]
BTW there's a note in the docs saying you have to put resources in `drawable-nodpi` to prevent them being scaled by Android - have you done that?

**Comment by ending0421** [comment]
i met same issue using this libs while decode a local file image . How can i resolve this issue in my case ? it is not a image build in apk so i can not put these in drawable-nodpi folder.

**Comment by davemorrissey** [comment]
@ending0421 Please include your code when reporting a problem.

**Comment by ending0421** [comment]
@davemorrissey  `mBitmap = BitmapUtil.decodeBitmap( mDocumentLocalPath );
    if ( mBitmap != null ) {
      mImageViewData.setImage( ImageSource.bitmap( mBitmap ) );
    }`
mImageViewData is SubsamplingScaleImageView inflated from xml with scaleType = "fitCenter" and layout_gravity = "center" , no other special params. 
Here is BitmapUtile.decodeBitmap(String path )
` public static Bitmap decodeBitmap(String path) {
    Options options = new Options();
    options.inSampleSize = 1;
    return decodeBitmap(path, options);
  }

  public static Bitmap decodeBitmap(String path, Options options) {
    Bitmap bitmap = null;

    try {
      bitmap = BitmapFactory.decodeFile(path, options);
    } catch (OutOfMemoryError var4) {
      options.inSampleSize *= 2;
      bitmap = decodeBitmap(path, options);
    }

    return bitmap;
  }`

**Comment by davemorrissey** [comment]
@ending0421 Please read the setup instructions and the wiki. The view can't tile bitmaps if you load them like this.
