### ISSUE TITLE
Disable pinch zooming but allow double-tap zooming?

### ISSUE THREAD

**Issue by aprechtl** [davemorrissey/subsampling-scale-image-view#198]
Hi, is it possible to disable pinch zooming but allow double-tap zooming? I'm developing for Android Wear and the devices are too small to pinch zoom, but I want to be able to double-tap.

**Comment by davemorrissey** [comment]
I think your best bet is to fork the project, and remove all the code that handles `touchCount >= 2` in `onTouchEvent`.
