### ISSUE TITLE
Image in Subsampling has compression artifacts

### ISSUE THREAD

**Issue by rafaelekol** [davemorrissey/subsampling-scale-image-view#199]
Image in Subsampling has compression artifacts. How can I change compression rate in Subsampling.

**Comment by davemorrissey** [comment]
Can you provide a screenshot that shows this?

**Comment by rafaelekol** [comment]
**Image viewed from native Gallery**

![screenshot_20160324-130804](https://cloud.githubusercontent.com/assets/1390965/14042658/4644deca-f2a6-11e5-926b-e34fd645b0db.png)

**Image viewed via Subsampling has artefacts on top actionbar, just under plus sign.**

![screenshot_20160324-130736](https://cloud.githubusercontent.com/assets/1390965/14042659/4645d96a-f2a6-11e5-8de0-ade7db969677.png)

**Comment by davemorrissey** [comment]
This might be a result of using RGB_565 to save memory, but I've never seen artifacts like that from a PNG. You could try creating a copy of SkiaImageRegionDecoder and using ARGB_8888, but you might get more out of memory errors on older or low-end devices.

**Comment by rafaelekol** [comment]
Sorry I sent you screenshots from my Android phone(which are created in PNG format). The image that causes problem is actually JPEG(this image originally was created as screenshot in iPhone 6).
I am attaching this original JPEG  image.
![fe1a4f89-81db-4d3d-8530-cab650c7e221_media](https://cloud.githubusercontent.com/assets/1390965/14072600/ece98bf6-f4e3-11e5-9e92-7d3b17a84f99.jpeg)

**Comment by davemorrissey** [comment]
It would be better to save that as a PNG because the JPEG has compression artifacts as you can see from the attached image. The same advice I gave above still applies, use ARGB_8888 but be aware this can cause OOMEs.

![ece98bf6-f4e3-11e5-9e92-7d3b17a84f99](https://cloud.githubusercontent.com/assets/1893039/14074448/d8d4efd6-f4c8-11e5-8a78-5f1e41097903.jpeg)

**Comment by rafaelekol** [comment]
Thank you for advice
