### ISSUE TITLE
Getting the Image source boundaries.

### ISSUE THREAD

**Issue by zerocold96** [davemorrissey/subsampling-scale-image-view#200]
I was looking at your freehand sample and everything works great, but how do I go about finding the actual onscreen coordinates of my image. SourceToViewCoord gets me the coordinates of the entire view I just want the coordinates of my image.

For example limit the drawing to only the image and not the view on your sample.

**Comment by davemorrissey** [comment]
Calls to `sourceToViewCoord(0, 0)`, `sourceToViewCoord(0, sourceHeight)` etc will give you the bounds. If you don't know the source dimensions, use `getSHeight()`, `getSWidth()`
