### ISSUE TITLE
Disabling fling

### ISSUE THREAD

**Issue by lukasz-gosiewski** [davemorrissey/subsampling-scale-image-view#201]
Hi, is it possible in any way to disable fling to move feature ? I'm creating some views on top of your component and it's not possible to animate them in the same way as view, so i want to disable fling gesture. I can't totally disable this gesture in subclass because view is content of PageViewer and when i disable this gesture by onTouchEvent, PageViewer is no longer switchng pages by fling.

**Comment by davemorrissey** [comment]
I'd suggest creating a fork and modifying the code to your needs, this requirement is too specialised to include in the main library.

**Comment by lukasz-gosiewski** [comment]
Yep, i did this already. Anyway it's worth thinking about, maybye more people want to disable fling gesture ? ViewPager is popular way of displaying images.

**Comment by davemorrissey** [comment]
ViewPager is very popular, but the need to disable fling is rare and you're the first to ask for it. There are already so many configuration options, and the touch handling is so complicated, that I don't want to add more touch handling options unless they're essential - it makes testing a nightmare! In cases like this I think the best option is creating a subclass or a fork, or using a custom gesture detector.

**Comment by lukasz-gosiewski** [comment]
Subclass wont allow us to disable this anyway, u need to create fork :) However topic closed ;)
