### ISSUE TITLE
Setting the minimum scale for pinch zooming

### ISSUE THREAD

**Issue by shroffrushabh** [davemorrissey/subsampling-scale-image-view#203]
Hello,

So I am using your library for its pinch zoom capabilities and its working perfectly. I wanted to know if this the following case can be solved, I have a image inside your subsampling-scale-image-view which is panorama and I am pre-zooming into the image using the following

ivImage.setScaleAndCenter(1.25f, new PointF(centreX, centreY));

Is it possible for the library to make sure the subsampling-scale-image-view does not get scaled below "1". I tried using the following but it did not work

ivImage.setMinScale(1f);

**Comment by davemorrissey** [comment]
https://github.com/davemorrissey/subsampling-scale-image-view/wiki/07.-Configuration#setminscalefloat--setmaximumdpiint

**Comment by shroffrushabh** [comment]
so I already tried that method, but it did not do the trick. I have a panorama of size 2500 x 600, while my screen size is like 1200 x 700 (something on those lines, horizontal oriented screen). Since the pano image is much bigger than the screen, I use the 

ivImage.setScaleAndCenter(1.25f, new PointF(centreX, centreY));

to display only a part of the pano image. But now when I use the pinch zoom feature to zoom out from "1.25", I want to set that min scale to "1", but I can see that scale value goes to as small as "0.5" in which case the image view which has the panorama image resizes itself to fit the whole 2500 x 600 image in 1200 x 700. I want to set a hard limit on the scale to not go below "1" and the minScale function did not work :(

**Comment by davemorrissey** [comment]
Please read the manual I linked to. It says you need to call `setMinimumScaleType(SCALE_TYPE_CUSTOM)`
