### ISSUE TITLE
java.lang.NullPointerException warning after setting image resource

### ISSUE THREAD

**Issue by macaronlover** [davemorrissey/subsampling-scale-image-view#204]
imageView.setImage(ImageSource.resource(R.drawable.plan));

After using your code I get this warnning:

`Method invocation 'imageView.setImage(ImageSource.resource(R.drawable.plan))' may produce 'jave.lang.NullPointerException'`

How can I get rid of this?

**Comment by macaronlover** [comment]
I found a solution

`assert imageView != null`

**Comment by davemorrissey** [comment]
That would happen with any view so it's not an issue with this library.
