### ISSUE TITLE
larger images pan/zoom more smoothly than smaller ones, as long as not SCALE_TYPE_CENTER_CROP

### ISSUE THREAD

**Issue by edovino** [davemorrissey/subsampling-scale-image-view#205]
Stumbled across a odd problem: our app uses 15 large panorama images (JPEGs). Most of these are in the 14000x5000 px range, but some are smaller: around 7500x5000px
For these smaller images, panning & zooming is always choppy. However, panning & zooming the large panorama's is buttery smooth - that is, until we set `setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP)` - then we get the same choppy behaviour as with the smaller images.

**Comment by davemorrissey** [comment]
It's possible that on high res screens the smaller images are loaded in full - when I first built this library most phones had a canvas max bitmap size of 2048px but now many support far larger bitmaps and have such high density screens that even a 7500x5000px bitmap won't be tiled or subsampled. The performance of these huge bitmaps may be quite poor.

Try `setDebug(true)` to see the tile boundaries and sample sizes, that should give you some clues why different images perform better. One option might be to fork the code and override the canvas max bitmap size with a smaller value that works better. If that helps I'll make it a configuration option.

**Comment by edovino** [comment]
That was exactly it - the smaller images got divided into just two (huge) tiles. Larger images did get multiple tiles, until you set SCALE_TYPE_CENTER_CROP: then they got divided into two tiles as well. (That might be a bug? The overall size of the image hasn't changed - just the pan-limits)

Anyway, I've added a mth to set a max tile size (if set, that overrides the values returned from `getMaxBitmapDimensions`), and that works out just fine. I can send a pull request if you like.

**Comment by davemorrissey** [comment]
I don't think the behaviour with SCALE_TYPE_CENTER_CROP is a bug, it's just a combination of screen size, density, max bitmap size, image size and settings that results in large tiles being loaded.

If you don't mind sacrificing a bit of quality, try calling `setMinimumTileDpi(200)` - by default the view will load tiles subsampled to at least match the density of the screen, and that's not really necessary on a 400dpi screen, especially if you're displaying photos.

A PR would be good, I think this will be useful.

**Comment by edovino** [comment]
yes, you're right of course - I guess that method does more than I expected: I suppose I was looking for `setMinScale()` to get rid of the initial letterbox-view of the panoramas.
