### ISSUE TITLE
Attribute "src" has already been defined

### ISSUE THREAD

**Issue by ruijun** [davemorrissey/subsampling-scale-image-view#207]
@davemorrissey 
Hello ! When I add `com.davemorrissey.labs:subsampling-scale-image-view:3.5.0` as a dependency in my build.gradle file. it appears this error:

**Attribute "src" has already been defined**

**Comment by jklwan** [comment]
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:src="@drawable/img"/>

</LinearLayout>`
this can work。

**Comment by davemorrissey** [comment]
That seems like a good solution. I've not seen this problem myself, it may be a conflict with another library.
