### ISSUE TITLE
Gif support (not an issue)

### ISSUE THREAD

**Issue by aleksandr1592** [davemorrissey/subsampling-scale-image-view#208]
Hello.May I ask you why don't you support non-animated gifs.Is it technically impossible to cut gif for tiles?

**Comment by davemorrissey** [comment]
This view uses BitmapRegionDecoder, which doesn't support GIFs. If you disable tiling (see the wiki) it will use BitmapFactory and I think that does support GIFs. Are you using GIFs large enough to require tiling? What kind of images are they (building plans, maps...)?

**Comment by aleksandr1592** [comment]
I have to load high-resolution (up to 2000x3000) gif with automobile parts schemes.It cause out of memory error in some devices.My best idea so far is downsampling.However, I want to find a way to load them without loosing image quality.Is it even possible?

**Comment by davemorrissey** [comment]
I'd strongly recommend converting it to a PNG.

**Comment by aleksandr1592** [comment]
Thank you for your answer and for your suggession.I will try to convince server-side developers to do it.

**Comment by davemorrissey** [comment]
Okay. I don't know of any way to subsample or tile a GIF, but it's possible you could find a native library that does support it, and use a custom decoder class. Converting to PNG will be far easier.
