### ISSUE TITLE
PDFDecoder

### ISSUE THREAD

**Issue by stefanplindner** [davemorrissey/subsampling-scale-image-view#215]
Hey,

first of all, thanks a lot for the library. We tried to implement pdf rendering as mentioned in #160.
Here is our first basic approach. We have tested it on some Nexus devices, and it seems to work properly.

https://gist.github.com/stefanplindner/ef96abb00204b8e6e0f378cfe026a6d7 

We use a VerticalViewPager to create a PDFDocumentViewer.

Best regards,
Stefan

**Comment by davemorrissey** [comment]
Interesting, thanks, but why is this raised as an issue?

**Comment by stefanplindner** [comment]
I thought there might be some others with the same problem (since it was already asked) and i wanted to show them a solution for it.

**Comment by davemorrissey** [comment]
Great, they can find it through this issue or the reference on the closed one, you could also ask and answer your own question on stackoverflow.

**Comment by KnIfER** [comment]
My solution : https://github.com/KnIfER/PolymPic
