### ISSUE TITLE
Restoring ImageViewState: unexpected behaviour for fully visible images

### ISSUE THREAD

**Issue by eltos** [davemorrissey/subsampling-scale-image-view#219]
When saving and restoring the `ImageViewState`, a previously not zoomed image may become zoomed depending on screen and image aspect ratio.
So instead of keeping the scale value, a fully visible image should stay fully visible when rotating the screen.

**Comment by davemorrissey** [comment]
This is the intended behaviour, but you can modify it by creating your own subclass.

**Comment by eltos** [comment]
I am just wondering, weather this is the behaviour that a user would expect (Well, I didn't). But that's your decision.
As getState() is a final method, one cannot overwrite it.
Instead, if someone else stumbles across this, replace the calles to `getState()` with the following to change the behaviour:

```java
//ImageViewState state = mImageView.getState();
ImageViewState state = mImageView.getState() == null ? null : new ImageViewState(
        mImageView.getScale() > mImageView.getMinScale() ? mImageView.getScale() : 0,
        mImageView.getCenter(), mImageView.getOrientation());
}
```

**Comment by davemorrissey** [comment]
That looks like a good solution. The view is intended to be easy to extend and customise, and although the defaults may not suit everyone I don't want to make backwardly incompatible changes.
