### ISSUE TITLE
incorrect displaying of some jpegs

### ISSUE THREAD

**Issue by miku-nyan** [davemorrissey/subsampling-scale-image-view#22]
![14114382974140](https://cloud.githubusercontent.com/assets/8571961/4468861/3d046182-4906-11e4-9c64-9a6363e983ba.jpg)
This file (md5: 2314425c399561cb6d75f7aa3c8eeab7) is displaying incorrectly in subsampling-scale-image-view (and can't reproduce this bug in other apps).
It looks like this:
![14119475986950](https://cloud.githubusercontent.com/assets/8571961/4468876/961f5ed4-4906-11e4-8015-2a5086d3a13e.png)

What could be the reason?

**Comment by davemorrissey** [comment]
I have extracted the bitmap decoding into an interface to allow an alternative decoder to be easily substituted in. A basic implementation built on RapidDecoder is included in the sample library, and it displays this image properly. See the updated README for more details.
