### ISSUE TITLE
why in SubsamplingScaleImageView's initialiseBaseLayer method,fullImageSampleSize always divide 2？

### ISSUE THREAD

**Issue by niejunhong** [davemorrissey/subsampling-scale-image-view#220]
fullImageSampleSize = calculateInSampleSize(satTemp.scale);
    if (fullImageSampleSize > 1) {
      fullImageSampleSize /= 2;
    }

sometimes,load double resolution cause OOM in my app?
could i remove   fullImageSampleSize /= 2; ??

**Comment by davemorrissey** [comment]
There's a comment on the line above that explaining why it's done. You're welcome to try removing it, but I can't be sure whether that will introduce major bugs.

**Comment by niejunhong** [comment]
@davemorrissey thanks! I'll try to remove it.
