### ISSUE TITLE
Large images in a ViewPager causing severe slowdown

### ISSUE THREAD

**Issue by laurencedawson** [davemorrissey/subsampling-scale-image-view#221]
When large images are shown in a ViewPager, slowdown can result when swiping between images.

The follow message is logged:

> I/Choreographer(19817): Skipped 52 frames!  The application may be doing too much work on its main thread.

My thoughts are that the subsampling should only happen for the current image and not others.

**Comment by davemorrissey** [comment]
Discussed recently in #218 - try `setMinimumTileDpi`

**Comment by laurencedawson** [comment]
Thanks, that did the trick. 

As larger resolutions become the norm, might I recommend setting a max cap to this lib?
