### ISSUE TITLE
A different scale option?

### ISSUE THREAD

**Issue by QuentinLewes** [davemorrissey/subsampling-scale-image-view#225]
Hello @davemorrissey ,
I have a list of images, each one's width is larger than its height , so I made the Activity landscape and used scale option SCALE_TYPE_CENTER_CROP, users can swipe right or left to see the whole image.

My problem is that when a image's height is much smaller than screen's, the image would be too large and become blurred.

So I think I need a way to use SCALE_TYPE_CENTER_CROP when image's height is larger than screen's, and remain image's original height when it is smaller than screen's.

**Comment by davemorrissey** [comment]
Try this:

   setMinimumScaleType(SCALE_TYPE_CUSTOM);
   setMinScale(1f);

(I haven't tried it but I think this might be what you need)

**Comment by QuentinLewes** [comment]
This will remain image's original height when it is smaller than screen's.

But when image's height is larger than screen's, "setMinScale(1f)" will  forbid the behavior like SCALE_TYPE_CENTER_CROP.

**Comment by davemorrissey** [comment]
Good point. You could implement behaviour like this with a subclass, or possibly just by passing an initial state that centres the image, provided you know its width and height, and the dimensions of the view.

**Comment by QuentinLewes** [comment]
I got a plan:

Get image's `sWidth` and view's `vWidth`,
```
    if (sWidth > vWidth){
        view.setMinScale( (float)(vWidth/sWidth) );
    }else {
        view.setMinScale(1f);
    }
```

I learned how to get a image's dimensions before loading it into memory from [stackoverflow](http://stackoverflow.com/questions/16440863/can-i-get-image-file-width-and-height-from-uri-in-android).

But if I try to get view's dimensions before `view.setMinScale()` using methods `view.getWidth()` and `view.getHeight()`, the returned values are both 0. Is there any solution for this?

**Comment by QuentinLewes** [comment]
I changed the source code:
```
public static final int SCALE_TYPE_CENTER_INSIDE = 1;
public static final int SCALE_TYPE_CENTER_CROP = 2;
public static final int SCALE_TYPE_CUSTOM = 3;
public static final int SCALE_TYPE_CENTER_CROP_CUSTOM= 4;
private static final List<Integer> VALID_SCALE_TYPES = Arrays.asList(SCALE_TYPE_CENTER_CROP,
 SCALE_TYPE_CENTER_INSIDE, SCALE_TYPE_CUSTOM, SCALE_TYPE_CENTER_CROP_CUSTOM);

...

private float minScale() {
	int vPadding = getPaddingBottom() + getPaddingTop();
	int hPadding = getPaddingLeft() + getPaddingRight();
	if (minimumScaleType == SCALE_TYPE_CENTER_CROP) {
		return Math.max((getWidth() - hPadding) / (float) sWidth(), (getHeight() - vPadding) / (float) sHeight());
	} else if (minimumScaleType == SCALE_TYPE_CUSTOM && minScale > 0) {
		return minScale;
	} else if (minimumScaleType == SCALE_TYPE_CENTER_CROP_CUSTOM){
		return Math.min( Math.max((getWidth() - hPadding) / (float) sWidth(), (getHeight() - vPadding) / (float) sHeight()), 1f);
	} else {
		return Math.min((getWidth() - hPadding) / (float) sWidth(), (getHeight() - vPadding) / (float) sHeight());
	}
}
```

Many thanks for your help!

**Comment by davemorrissey** [comment]
Awesome, looks good! If I could decide what this should be named I would add it as another scale option.

**Comment by QuentinLewes** [comment]
Fine, I am looking forward to it :-)
