### ISSUE TITLE
Display Matrix Change Event Support Request

### ISSUE THREAD

**Issue by MuhammadRashid** [davemorrissey/subsampling-scale-image-view#226]
I would like to ask, can this amazing widget allow the application to be notified when the displayed Matrix has changed.? This can be useful for when we need to update our UI based on the current zoom/scroll position.

Can anybody help me in this regard? I really need it for my application.

**Comment by davemorrissey** [comment]
The best way to do something like this is create a subclass of the view.

**Comment by DevAxis** [comment]
Thank you very much for your response. Can you please help out by a code snippet? As I am really not able to implement required functionality after extending Sub
sampling Scale Image View.

**Comment by davemorrissey** [comment]
Please take a look at the sample project source code and the wiki, there should be enough to get you started. Otherwise, StackOverflow is a good place to ask for advice.
