### ISSUE TITLE
ImageSource from byte-array

### ISSUE THREAD

**Issue by kumpz** [davemorrissey/subsampling-scale-image-view#229]
Currently there is no option to easily load an image available as byte-array.
Would it be possible to implement support for this?

**Comment by davemorrissey** [comment]
Use BitmapFactory to decode it, then pass it in using `ImageSource.bitmap`

**Comment by kumpz** [comment]
The problem is the internal size-limit of Bitmaps.
Another problem would be the huge ram-consumption.

**Comment by davemorrissey** [comment]
This view can't load tiles from a byte array in memory. It would need to decode the bitmap using BitmapFactory to display it, so you'd run out of memory either way. Write the byte array to disk and pass the file URI in - that way tiling will be supported.

**Comment by kumpz** [comment]
I hoped to be able to avoid that.
Thanks tho

**Comment by kumpz** [comment]
I know it's been quite some time.
I finally got to set up a github-repo with a version supporting byte-arrays.
If you are interested:
[https://github.com/kumpz/subsampling-scale-image-view](url)

**Comment by kumpz** [comment]
If you are ok with it, I'd make a pull-request
