### ISSUE TITLE
Loaded bitmap is "pixelated"

### ISSUE THREAD

**Issue by SammyVimes** [davemorrissey/subsampling-scale-image-view#23]
Some images are loading in very poor quality. It's always the same images, but I can't figure out what they have in common. Here is the example of image and a screenshot how it looks like on a device. (btw, I use subsampling view). The issue persists on every device I tried and also on genymotion emulator, so I think it's a bug
![sun-ken-rock-v01-c03---20](https://cloud.githubusercontent.com/assets/4058545/4541937/73006988-4e1b-11e4-9d19-e21307bdb243.jpg)
![image](https://cloud.githubusercontent.com/assets/4058545/4541978/3728f906-4e1c-11e4-831d-cca55e43c0ef.png)

**Comment by davemorrissey** [comment]
I have extracted the bitmap decoding into an interface to allow an alternative decoder to be easily substituted in. A basic implementation built on RapidDecoder is included in the sample library, and it displays this image properly. See the updated README for more details.
