### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by prashanthd** [davemorrissey/subsampling-scale-image-view#232]
is this imageview zooming works in full screen dialogs?

**Comment by davemorrissey** [comment]
I've never tried that. Have you tried it?

**Comment by prashanthd** [comment]
Yes it is working perfect. Thanx @davemorrissey for such a beautiful lib.  One thing I am missing is, I want image to be full screen irrespective of aspect ratio is it possible?

**Comment by davemorrissey** [comment]
Have a look at the configuration page in the wiki, you'll find what you need under the minimum scale type option.
