### ISSUE TITLE
Can we use Glide library with this to display the image?

### ISSUE THREAD

**Issue by abhimrawks** [davemorrissey/subsampling-scale-image-view#234]
I am using Glide everywhere else and would like to integrate Glide here as well. Glide automatically takes care of all the network calls and caching. That would be nice to have.

**Comment by kakai248** [comment]
Your best approach would be to use Glide to downloadOnly. Because it gives you a File that you can use directly in this view. I eventually switched to UIL because I can access cache files and it still gives me bitmaps so I can use them in the preview part.

**Comment by fifa1016** [comment]
you can use this:
  Bitmap bitmap = Glide.with(GalleryActivity.this).load(picUrl )
                                .asBitmap().into(-1, -1).get();

**Comment by gnumilanix** [comment]
Here's one approach. For some reason formatting did not work:

`Glide.with(view.getContext()).load(url).asBitmap().into(new SimpleTarget<Bitmap>() {
    @Override
    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
        view.setImage(ImageSource.bitmap(resource));
    }
});`

**Comment by yeming1001** [comment]
@gnumilanix 使用你说的方法 glide显示大图，显示多张后，还会出现后面的图显示不出来的情况，改如何解决

**Comment by davemorrissey** [comment]
I'll close this now. There's plenty of advice on this in these comments, other issues and StackOverflow. The view can't easily be changed to work with image loaders because most work with bitmaps, bypassing this view's support for large images without out of memory errors. As kakai248 says, using an image loader to store the file locally is best.

**Comment by peerJasim** [comment]
// For SubsamplingScaleImageView use SimpleTarget

      Glide.with(context)
                    .asBitmap()
                    .load(images[position])
                    .apply(RequestOptions.diskCacheStrategyOf(DiskCacheStrategy.AUTOMATIC))
                    .into(new SimpleTarget<Bitmap>(width, height) {
                        @Override
                        public void onResourceReady(Bitmap bitmap, Transition<? super Bitmap> transition) {
                            subsampleImageView.setImage(ImageSource.bitmap(bitmap)); //For SubsampleImage
                        }
                    });

**Comment by CarsonRedeye** [comment]
```
class SubsamplingScaleImageViewTarget(view: SubsamplingScaleImageView) : CustomViewTarget<SubsamplingScaleImageView, Drawable>(view) {
    override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable>?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun onLoadFailed(errorDrawable: Drawable?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun onResourceCleared(placeholder: Drawable?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }
}
```
```
Glide.with(this)
                    .load(file)
                    .into(SubsamplingScaleImageViewTarget(image_preview))
```

**Comment by benni12er** [comment]
@CarsonRedeye Thank you, this is the right answere! When using Bitmaps as response, the app gets slowed down as hell while using the File, everything works like with a classic imageview.
