### ISSUE TITLE
Subclassing

### ISSUE THREAD

**Issue by Michels10** [davemorrissey/subsampling-scale-image-view#235]
Hi,

I was wondering what the thoughts were on simplifying the process for allowing the use of Picasso and OkHttp3 with subsampling-scale-image-view...

Right now the SubsamplingScaleImageView's setImage() function is declared final disallowing us from overriding that method.  Are there negative side effects to removing that final declaration?  I'd like to subclass SubsamplingScaleImageView into PicassoSubsamplingScaleImageView to look something like this... (Untested)

```
public class PicassoSubsamplingScaleImageView extends SubsamplingScaleImageView {

    public PicassoSubsamplingScaleImageView(Context context, AttributeSet attr) {
        super(context, attr);
    }

    public PicassoSubsamplingScaleImageView(Context context) {
        super(context);
    }

    private void picassoConfig(final String url) {
        final OkHttpClient client = new OkHttpClient();
        OkHttp3Downloader downloader = new OkHttp3Downloader(this.getContext(), Integer.MAX_VALUE);
        final Picasso picasso = new Picasso.Builder(this.getContext())
                .downloader(downloader)
                .build();

        this.setBitmapDecoderFactory(new DecoderFactory<ImageDecoder>() {
            public ImageDecoder make() {
                return new PicassoDecoder(url, picasso);
            }});

        this.setRegionDecoderFactory(new DecoderFactory<ImageRegionDecoder>() {
            @Override
            public ImageRegionDecoder make() throws IllegalAccessException, InstantiationException {
                return new PicassoRegionDecoder(client);
            }
        });
    }

    public void setImage(ImageSource imageSource) {
        if (ImageSource.uri != null)
            picassoConfig(imageSource.uri.toString());
        super.setImage(imageSource);
    }
}
```

Note: this assumes the inclusion of:

```
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp3:okhttp:3.4.1'
compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2'
```

There are ways around this, for instance right now I've just replaced the setImage function above with setImageUrl(String url), but I don't think it's as elegant.

**Comment by davemorrissey** [comment]
I think the solution you have is pretty good!

There are reasons why so many methods are private and/or final - they manage the state of the view and all its internal variables, and replacing one of these methods might very easily break the view, in very subtle ways. I aimed to design the class with extension in mind, and provide the set of non-final methods required to do this, but I wanted to avoid a flood of bug reports from users who've overridden critical methods. Forking is usually the best option if you want to go further off-piste than the library allows out of the box.

**Comment by Michels10** [comment]
I'll do that, thanks for your feedback!  Hopefully it'll help to reduce the number of questions going forward about the integration with Picasso.
