### ISSUE TITLE
Some gesture problem

### ISSUE THREAD

**Issue by wenmingvs** [davemorrissey/subsampling-scale-image-view#237]
Hi，I use your library in my project  https://github.com/wenmingvs/WeiBo  and it work prefect ! Can you add my icon into your  README list ?

By the way, I still got some problem about the gesture。 When I press the image for a moment，then move fast on the screen ，the image didn't follow the finger movement.Can you tell me how to fix this problem？

Please give me some advice ,Thanks!

**Comment by davemorrissey** [comment]
I can't reproduce that problem, can you provide any more details? Are you using any gesture detectors or event listeners?
