### ISSUE TITLE
Loading bitmaps into the image view

### ISSUE THREAD

**Issue by hackjedi** [davemorrissey/subsampling-scale-image-view#239]
I would like to use your image view in order to load a very big bitmap. Normal ImageViews have a .setImageBitmap function, but I cannot find such a function in your project. Is it possible to load bitmaps into your project or is it not suitable for my purpose?

**Comment by ubelab** [comment]
In order to load Bitmaps directly you can use this method:

`
imageView.setImage(ImageSource.bitmap(yourBitmap));
`

but pay attention that if the bitmap is "very big" you might run into out of memory issues.

**Comment by tianzhijiexian** [comment]
subsampling-scale-image-view support for large picture@hackjedi
