### ISSUE TITLE
Topcrop sometime not work in recyclerview

### ISSUE THREAD

**Issue by wenmingvs** [davemorrissey/subsampling-scale-image-view#242]
I use subsamplingScaleImageView In RecyclerView,and I use this code to show topcrop effect

``` java
longImg.setZoomEnabled(false);
longImg.setPanEnabled(false);
longImg.setQuickScaleEnabled(false);
longImg.setImage(ImageSource.uri(file.getAbsolutePath()), new ImageViewState(0, new PointF(0, 0), 0));
longImg.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP);
```

It work fine at the beginning。like this :

![correct](https://cloud.githubusercontent.com/assets/10514788/17687145/31ef80ea-63a5-11e6-875c-3538271834d6.png)

But when I scroll to other position item,then scroll back ,it became like this :

![error](https://cloud.githubusercontent.com/assets/10514788/17687314/8717e49e-63a6-11e6-99da-e162e19ad665.png)

seem like longImg.setImage(ImageSource.uri(file.getAbsolutePath()), new ImageViewState(0, new PointF(0, 0), 0)) not work again .

Can your tell me How to fix this bug?
the image url is there:http://ww2.sinaimg.cn/mw690/70e7cafajw1f6sbcioktqj20c846k4pm.jpg

**Comment by davemorrissey** [comment]
I haven't been able to reproduce this, I think it will only happen in a list view like this and I don't have a suitable app to test with. Please can you supply more of the code for your list adapter, and try debugging your app to see what method calls are being made to the view?
