### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by schrek1** [davemorrissey/subsampling-scale-image-view#243]
I want use this lib for indor navigation, but I don't know can I rotate image less than 90 degrees?

**Comment by schrek1** [comment]
Ok I found rotate method, but when i rotate some parts of images are crooped. Zoom out or drag not help, still invisible...

**Comment by xietansheng-unnoo** [comment]
Use exif, it will auto rotate：
`SubsamplingScaleImageView.setOrientation(SubsamplingScaleImageView.ORIENTATION_USE_EXIF)`
