### ISSUE TITLE
Image zooming/panning lag with 4096x4096 pixels image on Nexus 5X

### ISSUE THREAD

**Issue by ubelab** [davemorrissey/subsampling-scale-image-view#244]
Hi,
I noticed that in this scenario:

- 4096x4096 pixels image
- on Nexus 5X

the image gestures lag a lot and the zooming/panning is practically unusable.

This does not happen with a 6000x4000 pixels image or bigger images.
This does not happen on smaller devices (Nexus One).

I tried storing the image both in asset folder and internal memory.

Maybe this is a corner case (almost square image) or something related to very high density screens?

Thank you.
Best,
Marco

**Comment by davemorrissey** [comment]
Please see the discussion on #218 - particularly my last comment. The short answer is yes, it's related to high density screens.

**Comment by ubelab** [comment]
Thanks @davemorrissey, setMinimumTileDpi(160) solved my issue. =)
