### ISSUE TITLE
NullPointerException requestDisallowInterceptTouchEvent(boolean)

### ISSUE THREAD

**Issue by fkirc** [davemorrissey/subsampling-scale-image-view#245]
I am not sure why this is happening, and it seems to appear pretty random.
I use a custom onTouchListener on the SubsamplingScaleImageView to detect swipe gestures and a ViewAnimator to create swipe animations between images.

> FATAL EXCEPTION: main
>                                                                                         PID: 31476
>                                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestDisallowInterceptTouchEvent(boolean)' on a null object reference
>                                                                                             at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onTouchEvent(SubsamplingScaleImageView.java:591)
>                                                                                             at android.view.View.dispatchTouchEvent(View.java:9377)
>                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
>                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
>                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554) ......

**Comment by davemorrissey** [comment]
Which version of the library are you using? There's nothing on line 591 in the current version.

**Comment by fkirc** [comment]
I am using `'com.davemorrissey.labs:subsampling-scale-image-view:3.5.0'`

**Comment by davemorrissey** [comment]
I think what must have happened is the view is detached from its parent when this happens. It it's still on screen I'm not sure how that can happen. To stop the exception being thrown I've added some null safety.

**Comment by fkirc** [comment]
Thanks I think this should fix the issue
