### ISSUE TITLE
Shared element transition: center image while animating

### ISSUE THREAD

**Issue by Zeliret** [davemorrissey/subsampling-scale-image-view#246]
Hi there! First of all this is a great lib! Thank you! 
I faced up a little problem with activity shared element transition. 
There are an ImageView on the the first activity with a CenterCrop option. When I click on it I can see a transition between activities where the ImageView is changing it bounds and expands to the second activity (ViewPager). You can see this transition in the Google Photo app as example. 
If I use ImageView for the transition destination it is look fine. But when I use SubsamplingScaleImageView the image is not centered while animating. It looks like the image is not scaling with the view while animating. 

Sorry for my bag English. Here is a gif: 
[http://imgur.com/a/qIgWi](http://imgur.com/a/qIgWi)

**Comment by davemorrissey** [comment]
I can't provide much help with specific uses like this, but it sounds like you might need to create a subclass and override the default behaviour of `onSizeChanged`. There's no single correct behaviour for that method so I kept it simple and better suited to small size changes, and left it up to developers to customise it as they need.

**Comment by AvatarQing** [comment]
@Zeliret Hi, did you solved the problem? Can you share your code
