### ISSUE TITLE
An issue in PhotoViewAttacher.setBaseRotation

### ISSUE THREAD

**Issue by VolliUJ** [davemorrissey/subsampling-scale-image-view#247]
Hello!
I have found a little issue in method PhotoViewAttacher.setbaseRotation.
If you set mAttacher.setBaseRotation(90); It will be rotatet by 180 degrees.

Thank you.
Best,
Volli

**Comment by davemorrissey** [comment]
What is PhotoViewAttacher?

**Comment by VolliUJ** [comment]
Oh so sorry! I've made mistake, I thought about chrisbanes/PhotoView framework.
Issue for delete.

Regards
Volli

**Comment by davemorrissey** [comment]
No worries!
