### ISSUE TITLE
zoom image which is smaller than the SubsamplingScaleImageView

### ISSUE THREAD

**Issue by chk58** [davemorrissey/subsampling-scale-image-view#251]
how can i zoom an image which is smaller than the SubsamplingScaleImageView?

**Comment by s-a-davidovich** [comment]
i also have this problem to stretch small image within view

**Comment by yellowapps** [comment]
The default behaviour as described in the [configuration docs](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/07.-Configuration) is the whole image is visible at minimum scale, with both dimensions of the image equal to or less than the corresponding dimension of the view. The image is then centered in the view.

You can overcome your problem with following config:

imageView.setMinimumScaleType(SCALE_TYPE_CUSTOM);
imageView.setMinScale(0.5f);

**Comment by davemorrissey** [comment]
The view doesn't handle very small images particularly well because it was intended for huge images, but you can get around this by setting a large maximum scale value.

    imageView.setMaxScale(10f);
