### ISSUE TITLE
android.view.InflateException: Binary XML file line #65: Binary XML file line #65: Error inflating class com.davemorrissey.labs.subscaleview.sample.extension.views.PinView

### ISSUE THREAD

**Issue by rantoine78** [davemorrissey/subsampling-scale-image-view#252]
hello, 
I'm trying your sample, but when i want to test the extension view the app crash and i've got an fatal error : 

> android.view.InflateException: Binary XML file line #65: Binary XML file line #65: Error inflating class com.davemorrissey.labs.subscaleview.sample.extension.views.PinView

i think it's caused by a too big assets or drawable, but i don't know wich.

if someone can help me, it will a pleasure.

PS: excuse me for my bad english, i'm french and i'm 15.

**Comment by davemorrissey** [comment]
That's a class from the sample project, the library doesn't include it. Copy it into your project in any package you like, and change the layout XML to use your package name.
