### ISSUE TITLE
Tile background offset initally

### ISSUE THREAD

**Issue by laurencedawson** [davemorrissey/subsampling-scale-image-view#253]
Evening!

So tonight I've been playing with calling ".setTileBackgroundColor();" but noticed when called with:

```
.setImage(
              // image source,
              // image bitmap
          );
```

The background color flashes before the image is shown. Poking around it looks like it's maybe drawn a little under where it's supposed to be (perhaps when the preview bitmap is drawn) and then correctly once the full image is subsampled.

Cheers!

**Comment by davemorrissey** [comment]
There was a glitch in the matrix.

**Comment by laurencedawson** [comment]
Cheers!
