### ISSUE TITLE
not displayed

### ISSUE THREAD

**Issue by yeming1001** [davemorrissey/subsampling-scale-image-view#255]
I need to show a lot of big pictures，There will be not show 

tips：
SubsamplingScaleImageView not displayed because it is too large to fit into a software layer (or drawing cache), needs 25492320 bytes, only 8294400 available

**Comment by davemorrissey** [comment]
Please post your code and details of the images you're trying to display.

**Comment by yeming1001** [comment]
@davemorrissey     Click to get URL from WebView Pass to another Activity  to display.（To display a large picture）

Glide.with(this).load(url)
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.RESULT)
                .into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                previewImg.setImage(ImageSource.bitmap(resource));
            }
        });

**Comment by davemorrissey** [comment]
If you preload a bitmap, there's nothing the view can do to reduce memory usage. Save it to disk, and pass the URI of the file, which enables subsampling.
