### ISSUE TITLE
Can't display this RGB Image in Xiaomi device

### ISSUE THREAD

**Issue by gabrieljuan** [davemorrissey/subsampling-scale-image-view#258]
My designer checked the image and it is RGB, 

![all_halls](https://cloud.githubusercontent.com/assets/11532297/19713968/6fe9b346-9b74-11e6-888d-6d359883024c.jpg)

The error log would be like this 

`10-26 11:33:41.272 20436-20715/com.mirai_apps.pri D/skia: --- decoder->buildTileIndex returned false
10-26 11:33:41.281 20436-20715/com.mirai_apps.pri E/SubsamplingScaleImageView: Failed to initialise bitmap decoder
                                                                               java.io.IOException: Image failed to decode using JPEG decoder
                                                                                   at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
                                                                                   at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:116)
                                                                                   at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:60)
                                                                                   at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1415)
                                                                                   at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1391)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)`

and my source code 

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_zoning_layout);
        ButterKnife.bind(this);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
        CommonHelper.setupDrawerLayout(this, mDrawerLayout, mToolbar, mNavigationView, this);
        imageView.setDebug(true);
        imageView.setImage(ImageSource.asset("all_halls.jpg"));

        ArrayAdapter<CharSequence> adapter = new ArrayAdapter<CharSequence>(this, R.layout.holder_zoning_layout_spinner, getResources().getStringArray(R.array.zoning_layout_spinner_item));
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        spinner.setAdapter(adapter);
        spinner.setSelection(11);
        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
                CharSequence item = (CharSequence) adapterView.getItemAtPosition(i);
                if(item.equals("Hall 1")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_1));
                }else if(item.equals("Hall 2")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_2));
                } else if(item.equals("Hall 3")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_3));
                } else if(item.equals("Hall 3a")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_3a));
                } else if(item.equals("Hall 5")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_5));
                } else if(item.equals("Hall 6")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_6));
                } else if(item.equals("Hall 7")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_7));
                } else if(item.equals("Hall 8")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_8));
                } else if(item.equals("Hall 9")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_9));
                } else if(item.equals("Hall 10")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_10));
                } else if(item.equals("Hall C")){
                    imageView.setImage(ImageSource.resource(R.drawable.hall_c));
                } else if(item.equals("All Halls")){
                    imageView.setImage(ImageSource.asset("all_halls.jpg"));
                }
            }

            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
        });

        long hallNumber = getIntent().getLongExtra(ZONING_AND_LAYOUT_HALL_NUMBER_EXTRA_KEY,100);
        if(hallNumber != 100){
            if(hallNumber > 11){
                spinner.setSelection(11);
            }else {
                spinner.setSelection((int) (hallNumber - 1));
            }
        }

        footNoteClose.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                footNoteLayout.setVisibility(View.GONE);
            }
        });
    }

and this is my layout

`<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <Spinner
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:spinnerMode="dropdown"
            android:id="@+id/zoning_and_layout_spinner"
            android:background="@drawable/background_spinner_zoning_layout"
            android:layout_marginLeft="16dp"
            android:layout_marginRight="16dp"
            android:layout_marginTop="16dp"/>
        <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            android:layout_marginTop="16dp"
            android:id="@+id/zoning_and_layout_subsampling_image" />
    </LinearLayout>`

If I run it on other device, this log won't even appear. I'm using Xiaomi Mi5 for testing. 

I searched on google but won't find anything for Region Decoder / Skia library problem with xiaomi devices.

Could you help ?

Thanks

**Comment by davemorrissey** [comment]
The skia project have fixed a lot of bugs like this recently but the vast majority of shipped Android phones won't receive this update. Your best option is to save the JPG using a different application, which will in most cases result in it being in a format skia handles properly.

**Comment by gabrieljuan** [comment]
yup, I used another compressor and it solved the problem. To be honest, I don't know exactly what is the problem. Is it because xiaomi devices that don't get skia updates or the skia requirement to handles the image properly. Anyway, thanks for your answer. 

P.S : if anyone curious for the compressor I used to solved this problem, I used compressor.io

**Comment by davemorrissey** [comment]
Great, glad to hear you've solved it! This is a bigger problem for developers displaying images they don't control, e.g. reddit browsers. Most manufacturers don't release updates for their phones and I don't know whether the skia update will be included in patches for anything earlier than Nougat, so we just have to wait for the older phones to go out of circulation.
