### ISSUE TITLE
How to check if SubsamplingScaleImageView is in panning/zooming mode?

### ISSUE THREAD

**Issue by luskan** [davemorrissey/subsampling-scale-image-view#260]
Hi,

I'am trying to use SubsamplingScaleImageView  with OnSwipeTouchListener (http://stackoverflow.com/questions/4139288/android-how-to-handle-right-to-left-swipe-gestures).

It almost works, but to finish it I need to know when SubsamplingScaleImageView  is in zoomed mode, this is when user has double clicked on the view (then gestures should be disabled in OnSwipeTouchListener). 

I dont see any such functions from public interface, but I probably overlooked. I checked private variables like isQuickScaling, isPanning, .. (by reading them with reflection), but they are sometimes false in zoomed mode.

thanks

**Comment by davemorrissey** [comment]
Is it specifically the double tap zoom you need to know about, or do you also need to know when the user has zoomed in using pinch or the one finger gesture?

**Comment by davemorrissey** [comment]
The next build will include an `OnStateChangedListener` interface which allows you to receive scale changed events. Hopefully that does what you need.
