### ISSUE TITLE
Weird Problem.

### ISSUE THREAD

**Issue by TayfunCesur** [davemorrissey/subsampling-scale-image-view#263]
![dog](https://cloud.githubusercontent.com/assets/16436048/20032672/26e6ee9e-a398-11e6-875a-bb39d980fa48.png)
Hi. Firstly, thanks for this useful library and congrats!. I have really strange thing. When I was testing your library, I got this : I was triyng to load this image. [http://www.3discimaging.com/wp-content/uploads/2015/09/Cranium_Lateral_Large.jpg](url). But nothing loaded to your imageview. Any ideas?

**Comment by davemorrissey** [comment]
There are several reports like this in past issues. Please search them and you should find a solution.

**Comment by TayfunCesur** [comment]
Hey. Thanks for fast reply. And as you said I found a soluiton. I tried setMinimumTileDpi method and it worked. But what this method did ?
