### ISSUE TITLE
getting bitmap from onImageLoaded

### ISSUE THREAD

**Issue by TayfunCesur** [davemorrissey/subsampling-scale-image-view#264]
Hey. I am working on lut filters on images. But It takes very long time to get every pixel from huge bitmap. And I have an idea. As I see, you are not loading all pixes. You are loading part by part according to zooming. How can I get bitmap after first loaded and when zoomed ?

**Comment by davemorrissey** [comment]
I'm sorry, I don't understand the question!

**Comment by TayfunCesur** [comment]
Sorry for my English. Do we have any callback that returns us part of zoomed image's as bitmap?

**Comment by davemorrissey** [comment]
No, but have you read the wiki? There are methods to convert view coordinates to image coordinates and that's all you need to decode part of an image yourself.

**Comment by TayfunCesur** [comment]
I read that and I know how can I get clicked coordinates. My problem was I didn't imagine how can I create bitmap from clicked coordinates. But I will work on this thanks. By the way,let me know how can I do that?. 
Thanks. Best regards.

**Comment by davemorrissey** [comment]
https://developer.android.com/reference/android/graphics/BitmapRegionDecoder.html
