### ISSUE TITLE
[Bug] When zoomed in and at the border of an image, moving your finger down will call requestDisallowInterceptTouchEvent(false)

### ISSUE THREAD

**Issue by laurencedawson** [davemorrissey/subsampling-scale-image-view#269]
So just to reclarify:

1. Zoom in an image
2. Move to the left or right edge of the image
3. Swiping / moving your finger down will allow the parent to intercept the touch event

The expected behaviour is:

1. Zoom in an image
2. Move to the left or right edge of the image
3. Swiping / moving your finger down will do nothing
4. Swiping / moving your finger left / right will allow the parent to intercept the touch event

**Comment by davemorrissey** [comment]
I assume this would happen because when you swipe down there's still a small horizontal component to the swipe in most cases. The simple fix is probably to only call `requestDisallowInterceptTouchEvent(false)` if `dx > dy` at line 824. I don't have an app I can test this in easily, if I made that change would you be able to test it?

**Comment by laurencedawson** [comment]
Yup, if you dump it in a gist or here I'll test straight away. Cheers.

**Comment by davemorrissey** [comment]
Change line 824 from `} else if (dx > offset) {` to `} else if (dx > offset && dx > dy) {`. This is partly guesswork!

**Comment by laurencedawson** [comment]
Hmm not quite. 

This stops the described issue but now swiping down will never pass on the touch event...

**Comment by davemorrissey** [comment]
Okay, so it needs the same edge detection on the Y axis as it has on the X axis? That would allow a vertical scrolling view pager.

**Comment by laurencedawson** [comment]
I think so.

**Comment by davemorrissey** [comment]
Fixed by PR #302, will be in the next version.
