### ISSUE TITLE
repetition of image in thumbnail when clicked other thumbnail

### ISSUE THREAD

**Issue by sachitkarki** [davemorrissey/subsampling-scale-image-view#270]
When i click on any thumbnail it repeats the thumbnail in bottom viewpager. the image is attached below . Please review this.
![screenshot_2016-11-23-15-01-06 1](https://cloud.githubusercontent.com/assets/12908960/20556209/16046198-b18e-11e6-94bb-402e938f3a10.png)

**Comment by davemorrissey** [comment]
I don't think that's anything to do with this library.

**Comment by sachitkarki** [comment]
i would be pleased if you run this demo , you will see the problem.

**Comment by davemorrissey** [comment]
What demo? I've never seen this before. The thumbnails at the bottom are not a feature of this library or the sample.

**Comment by thaindq** [comment]
@sachitkarki: may I know how to make that thumbnails?
