### ISSUE TITLE
Zooming this image will repeatably cause a crash

### ISSUE THREAD

**Issue by laurencedawson** [davemorrissey/subsampling-scale-image-view#271]
URL:

https://cdn-daytripfinder.netdna-ssl.com/wp-content/uploads/2016/11/Every-Countrys-Tourism-Slogan-large.png

Error:

`11-27 01:12:48.390: A/libc(2669): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x30 in tid 2886 (AsyncTask #3)
`

**Comment by davemorrissey** [comment]
On my Nexus 5X (Nougat) this image is displayed without any problems. On my HTC One S (KitKat) when zooming in, tiles can't be decoded but there is no crash and no segfault. I assume this is a skia bug that's been fixed, so as with the others I can't resolve it myself and will close this.
