### ISSUE TITLE
How to make the width of the image is full of the viewport.

### ISSUE THREAD

**Issue by iboying** [davemorrissey/subsampling-scale-image-view#273]
1、This is my code:
```
detail_image = getViewById(R.id.detail_image);
detail_image.setMinimumScaleType(SCALE_TYPE_CUSTOM);
detail_image.setScaleX(1.0f);
...
Glide
    .with(context).load(imageUrl)
    .downloadOnly(new SimpleTarget<File>() {
          @Override
          public void onResourceReady(File resource, GlideAnimation<? super File> glideAnimation) {
                    detail_image.setImage(ImageSource.uri(Uri.fromFile(resource)), new ImageViewState(1.0f, new PointF(0, 0), 0));
});
```

2、This is my screenshot:
![image](https://cloud.githubusercontent.com/assets/10523771/20699551/d9796dcc-b642-11e6-8b81-40f79dc5ce0c.png)

**Comment by iboying** [comment]
Hi, Dave:
This is a really great repository. And it is used for my project.
Yesterday, I have try `setMinimumScaleType(SCALE_TYPE_CENTER_CROP)` and fix my issue.

There is a new issue:
**A short image can not fill the device width.**

And this is the issue screenshot:
![image](https://cloud.githubusercontent.com/assets/10523771/20737118/cb1fbdaa-b6e5-11e6-94b6-3f9baf9ce704.png)

Use the Android Imageview and set `android:scaleType="fitStart"`, it is like this:
![image](https://cloud.githubusercontent.com/assets/10523771/20737349/1275e9c6-b6e7-11e6-9a1b-c6973664a6ba.png)

Can the repository have some configurations like `android:scaleType="fitStart"`?

**Comment by xmliu** [comment]
tks, @iboying ,setMinimumScaleType(SCALE_TYPE_CENTER_CROP) is a great method,but it is not fit my requirement,as you say, no attribude like fitStart

**Comment by jayleco** [comment]
@iboying 你好，我遇到跟你一样的问题，请问你是如何解决的？能分享下吗？

**Comment by thorb-redweb** [comment]
I ended up doing it like this:

    public void instantiateItem() {
        ....
        detail_image.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
        detail_image.setMinScale(getFitWidthScale());
        ....
    }
    private float getFitWidthScale(){
        float viewWidth = App.getWindowWidth();
        return = viewWidth/getImageWidth();
    }

    private float getImageWidth(){
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        BitmapFactory.decodeFile(_file.getAbsolutePath(), options);
        return options.outWidth;
    }

**Comment by kingideayou** [comment]
You could use `setImage(ImageSource imageSource, ImageViewState state)` method.

see: https://stackoverflow.com/a/47048047/4756955

**Comment by davemorrissey** [comment]
The next release will support `setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_START)`, which will set the minimum scale so no black bars are visible and show the top of a tall image and the left of a wide image. Hopefully this meets everyone's needs.

**Comment by vihuela** [comment]
last version：under code is corect running
`Glide.with(mContext)
                        .load(tarItem.img)
                        .downloadOnly(object : ViewTarget<SubsamplingScaleImageView, File>(biv) {
                            override fun onResourceReady(resource: File?, glideAnimation: GlideAnimation<in File>?) {
                                currentStaticImage[tarItem.img] = resource
                                if (resource != null) {
                                    biv.setMinimumScaleType(SCALE_TYPE_CUSTOM)
                                    val w = ScreenUtils.getScreenWidth() * 1f / getFileWidth(resource)
                                    biv.maxScale = w
                                    biv.setImage(ImageSource.uri(Uri.fromFile(resource)), ImageViewState(w, PointF(0f, 0f), ORIENTATION_0))
                                }
                            }
                        })`
