### ISSUE TITLE
Image would be fly out of the screen

### ISSUE THREAD

**Issue by cc11235** [davemorrissey/subsampling-scale-image-view#274]
I have a very long image, and I set padding left and paddding right, at the first time when the image inited, when I double tap image, it should be zoom in with an animation, but the image just fly out of the screen and when it come back it become a larger image in the corrent palce....but zoom out is ok, I think it's a bug.

**Comment by davemorrissey** [comment]
I couldn't reproduce this. Please can you provide your image, layout XML, configuration code and if possible, a video showing the problem?
