### ISSUE TITLE
DoubleTapZoom doesn't work,when the value of minScale  is between doubleTapZoomScale and doubleTapZoomScale * 0.9

### ISSUE THREAD

**Issue by lomoya90** [davemorrissey/subsampling-scale-image-view#284]
DoubleTapZoom doesn't work,when the value of minScale   is between doubleTapZoomScale and doubleTapZoomScale * 0.9.

`boolean zoomIn = scale <= doubleTapZoomScale * 0.9;`
`float targetScale = zoomIn ? doubleTapZoomScale : minScale();`

**Comment by davemorrissey** [comment]
I think this is a rare edge case but I've added a quick fix - if the current scale is at the minimum, a double tap is always interpreted as a zoom in.
