### ISSUE TITLE
Implement onSingleTapListener and onDoubleTapListener

### ISSUE THREAD

**Issue by SSeanSS** [davemorrissey/subsampling-scale-image-view#286]
In my case, i need to detect onSingleTap to toggle the visibility of my layout and hide the layout during onDoubleTapListener.

**Comment by davemorrissey** [comment]
Implement your own GestureDetector. Please read the wiki before opening new issues. https://github.com/davemorrissey/subsampling-scale-image-view/wiki/09.-Events
