### ISSUE TITLE
How to disable double taping and allow only pinch gesture?

### ISSUE THREAD

**Issue by mercadopatricio** [davemorrissey/subsampling-scale-image-view#289]
The opposite of: #198 , how to disable double taping and allow only pinch gesture?

Parent (an AdapterViewFlipper that have a GestureDector object) have a custom behavior with double tap. Even with a GestureDetector#onDoubleTap() returning false in SubsamplingScaleImageView object event won't bubble up.

And the same thing with a single tap. Is the correct way to add a GestureDetector? Wiki say "safe" for single, but prevent work properly with double tap.
Any hint?

**Comment by davemorrissey** [comment]
I've looked into this, and I don't think I can fix it, and if I can it would take a long time. The need for the view to work inside view pagers required it to intercept and filter all events that the parent view might interpret as a swipe, as well as handle all events that could be pan and zoom gestures, which includes the individual taps of a double tap. You can add your own GestureDetector with an onDoubleTap method that returns false, and add custom behaviour to that, but triggering the parent's GestureDetector will be harder.

**Comment by davemorrissey** [comment]
After looking at this again I think I'm not going to be able to find a suitable solution. Making the view transparent to certain events is very difficult and would stop the view's gestures - not just double tap zoom, but probably also quickscale - working as expected. I'm going to close this as unfixable, sorry!
