### ISSUE TITLE
How to get position and setImage at SubsamplingScaleImageView?

### ISSUE THREAD

**Issue by PeterPhyo** [davemorrissey/subsampling-scale-image-view#291]
I have a GridView and then click it, go to FullScreenActivity. 

GridView clicklistener, 

`public void onItemClick(AdapterView<?> parent, View v, int position, long id) {
      Intent i = new Intent(getApplicationContext(), FullImageActivity.class);
      i.putExtra("id", position);
      startActivity(i);
}` 

FullScreenActivity 

`Intent i = getIntent();
int position = i.getExtras().getInt("id");
SubsamplingScaleImageView imageView = (SubsamplingScaleImageView)findViewById(R.id.imageView);
imageView.setImage(ImageSource.resource(position)); // error`

**Comment by davemorrissey** [comment]
This is a question for StackOverflow.

**Comment by PeterPhyo** [comment]
How to solve this question? Sir..

**Comment by davemorrissey** [comment]
`position` is an index, not a resource identifier. This is not a bug in this library, please ask this kind of question on StackOverflow.

**Comment by PeterPhyo** [comment]
Thanks, Sir. I solve this error. 😄 But I have another problem. SubsamplingScaleImageView is look good and can use double tap to zoom in and out in my phone. But @ Tablet Screen Size, SubsamplingScaleImageView  is not look good and can't use double. How to get for those screen size reasonable? 

<Phone>

![phone](https://cloud.githubusercontent.com/assets/16751250/23063245/e53ee3e2-f537-11e6-8ab8-ea622129531b.png)

<Tablet>

![tablet](https://cloud.githubusercontent.com/assets/16751250/23063261/f889269c-f537-11e6-954e-52b6832cd4c5.png)
