### ISSUE TITLE
How to add a customized pin?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [davemorrissey/subsampling-scale-image-view#294]
Suppose I want to add multiple images as pins, and also be able to animate them when they are added, how do I do this?
It could be great to know instead of a bitmap, how to put a view as a pin.

**Comment by davemorrissey** [comment]
Take a look at the sample code and extend it as you need. I can fix bugs in this library but can't help developers build their apps. If you get stuck, try asking questions on StackOverflow.

**Comment by AndroidDeveloperLB** [comment]
But the sample shows it for a single one. :(

**Comment by davemorrissey** [comment]
Indeed, but I can't help you build your app, or do your research for you.
