### ISSUE TITLE
How to avoid centering the image on load?

### ISSUE THREAD

**Issue by Saketme** [davemorrissey/subsampling-scale-image-view#295]
Hey Dave, thanks for this fantastic library. I was wondering if there are any plans for setting the gravity to the top of ImageView instead of always centering it?

**Comment by davemorrissey** [comment]
The next release will support `setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_START)`, which will set the minimum scale so no black bars are visible and show the top of a tall image and the left of a wide image. Hopefully this meets everyone's needs.
