### ISSUE TITLE
Avoid calling requestDisallowInterceptTouchEvent() when image isn't zoomed in

### ISSUE THREAD

**Issue by Saketme** [davemorrissey/subsampling-scale-image-view#296]
Hey, so I have my image inside a ViewGroup which supports some touch gestures. Since `SubsamplingScaleImageView` calls `requestDisallowInterceptTouchEvent()` as soon as it receives a touch event, it's impossible for the parent ViewGroup to ever receive the touch events. 

Can we modify this behavior so that `requestDisallowInterceptTouchEvent()` only gets called when the image is zoomed in? I imagine that's when the user is interacting with the image and the parent need not intercept the touch events.

**Comment by Hezj** [comment]
Maybe you can take a look at my modification in #302.

**Comment by Saketme** [comment]
@Hezj your PR looks nice, but is there any reason you're only doing it for vertical gestures instead of both vertical Anna horizontal?

**Comment by davemorrissey** [comment]
I think PR #302 mostly fixed this problem. It allows touch events to bubble up to the parent if you are at the top or bottom of the image (both of which apply when zoomed out). This allowed vertical view pagers to work, and also supports multiple image views in a `ScrollView`. Can you confirm whether there is still a problem here and describe your layout and what gestures are not working?

**Comment by Saketme** [comment]
@davemorrissey @Hezj will it be possible to include horizontal swipes as well?

**Comment by davemorrissey** [comment]
The view supported horizontal swipes years ago, and the change @Hezj made added support for vertical. There are horizontal and vertical view pagers in the sample app and both work as I expect them to - try it for reference. What's the problem you're having?

**Comment by Saketme** [comment]
Ah sorry. I did a quick read of the PR and did not realize that horizontal was already supported. My bad.
