### ISSUE TITLE
Is it possible to show GIFs?

### ISSUE THREAD

**Issue by Saketme** [davemorrissey/subsampling-scale-image-view#297]
I'd like to display GIFs using Glide. Is it possible to disable tiling so that GIFs work? I'm unable to figure out how to make a custom decoder otherwise.

**Update:** I don't think it's possible to display GIFs even with a custom decoder becuase they work with Bitmaps. Is there any other way to make this happen?

**Comment by davemorrissey** [comment]
See [the wiki](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images) for instructions on disabling tiling. This should enable GIF support. Bear in mind that animated GIFs are not supported.
