### ISSUE TITLE
SubsamplingScaleImageView inside ScrollView

### ISSUE THREAD

**Issue by wizardkhinz18** [davemorrissey/subsampling-scale-image-view#299]
how to be smooth scrolling inside of scrollview?

**Comment by Saketme** [comment]
I've tried doing this and this looks to be difficult because SubsamplingScaleImage consumes all touch events it receives, without any support for nested scrolling. The only solution is to intercept touch events in the parent ScrollView.

**Comment by Saketme** [comment]
I've tried doing this and this looks to be difficult because SubsamplingScaleImage consumes all touch events it receives, without any support for nested scrolling. The only solution is to intercept touch events in the parent ScrollView.

**Comment by davemorrissey** [comment]
I think PR #302 mostly fixed this problem. It allows touch events to bubble up to the parent if you are at the top or bottom of the image (both of which apply when zoomed out). This allowed vertical view pagers to work, and also supports multiple image views in a vertical `ScrollView`. Can you confirm whether there is still a problem here and describe your layout and what gestures are not working?

Note if an image is zoomed in, swiping up on that image will pan it up until you reach the bottom. Then a second swipe is needed to scroll the parent view up. That's the intended behaviour.
