### ISSUE TITLE
Zoom to fit screen

### ISSUE THREAD

**Issue by abangfadli** [davemorrissey/subsampling-scale-image-view#300]
Is it possible to set the zoom level to fit the screen width?
I'm thinking of using `samplingImageView.setScaleAndCenter();` but can't figure out what to fill in for the scale.

**Comment by Saketme** [comment]
You can get the image width (`SamplingImageView#getSWidth()`) and your screen width, calculate a resize factor by doing `screenWidth/imageWidth` and supply it to `setScaleAndCenter()`.

**Comment by abangfadli** [comment]
Yes I've tried that before but the resulting scale make the image zoomed in too much. It appears that the default scale was not 1, so I had to multiply the current scale with 'screenWidth/imageWidth' to ge the correct scale. Thanks!
