### ISSUE TITLE
scrolling with arbitrary rotation

### ISSUE THREAD

**Issue by milmanal** [davemorrissey/subsampling-scale-image-view#304]
Hi Dave

ive been using your great library for a while now and lately ive managed to mostly complete my belonged wish of implementing free rotation to work with your library
the only brick im missing in the puzzle is making the gestures work with the rotated view - and in particular the scrolling (panning).
To implement the rotation view i have subclassed your view. then i tried to implement the SimpleOnGestureListener and override onScroll , rotate the values , sending them to a GestureDetector. but that doesnt seem to do anything since looks like the scrolling (panning) is handled by the main view.
is there a way to disable it? do you have any specific advice to for me of what would be the coarse of action to do this?
I know youve been very sceptical of the whole free rotation thing and avoided diving into it, but i thought since im very close to wrapping it up maybe share your ideas on the final part.

Would appreciate any help 
Michael

**Comment by milmanal** [comment]
ok I am able to intercept the touch events in my subclass and prevent them from going into the parent view but not able to do any scrolling 
`    private class InnerGestureDetectorListener extends GestureDetector.SimpleOnGestureListener {

        @Override
        public boolean onDown(MotionEvent e) {
            return true;
        }

        @Override
        public boolean onFling(MotionEvent e1, MotionEvent e2, float velocityX, float velocityY) {
            return super.onFling(e1, e2, velocityX, velocityY);
        }

        @Override
        public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
            double headingRadians = -mAnimatedRotation * Math.PI / 180;
            PointF distancePoint = new PointF();
            double n1 = distanceX*Math.cos(headingRadians);
            double n2 = distanceY*Math.sin(headingRadians);
            distancePoint.x = (float)(n1-n2);
            n1 = distanceX*Math.sin(headingRadians);
            n2 = distanceY*Math.cos(headingRadians);
            distancePoint.y = (float)(n1+n2);
            return super.onScroll(e1, e2, distancePoint.x, distancePoint.y);
        }
    }`

**Comment by davemorrissey** [comment]
I was a little skeptical about how many developers would need free rotation of images large enough to need subsampling, but a few have asked for it now. My main reason for not doing it was it's incredibly complicated! Unfortunately I doubt I can offer much assistance with this because it's now 2 or 3 years since I built the core of this library and it's not fresh in my memory, and making a change like this probably involves changing the core assumptions the code is based around.

I've noticed there seems to be some good progress towards this on this fork, is it yours? https://github.com/IndoorAtlas/subsampling-scale-image-view/commits/feature_rotation

**Comment by milmanal** [comment]
Thanks Dave - I understand your pov. 
narrowing it down to a more basic tip you may have - ive managed to implement almost everything - including the pan gestures with free rotation. but i cannot set the viewport translate values if i handle this in an extending class since they are private. so if user drags the rotated view and i need to handle it - the viewport values dont change after this action. 
Any idea how to overcome it? 
I could, of course, fork this and change the vTranslate modifiers to have an access from my subclass view, but then i would lose the advantage of having an access to your pure library as it is - tested and wrapped, and of course any potential future updates

> I've noticed there seems to be some good progress towards this on this fork, is it yours? 
No but its an interesting discovery! i know the guys from indooratlas and their use case is very similar to mine. the only bummer is that looks like the version they are implementing supports rotation around the center, while the version i need should rotate around a rotation point (like the user location on the view which would not necessarily be at the center)

**Comment by davemorrissey** [comment]
I think you're best off working on a fork. vTranslate is part of the internal state of the class and I've been very careful what's exposed to subclasses so they can't get the view into an unexpected state, and to preserve backwards compatibility. If vTranslate was exposed I couldn't make these guarantees, and as rotation is a fundamental change I think it's best done on a fork. Merging updates should be easy though, not much changes!

**Comment by davemorrissey** [comment]
Closing now as this isn't a bug or enhancement request, but add a comment if you have a fork with this working, it might be useful for others!

**Comment by milmanal** [comment]
I have a fork with this working :)
but need to do some tidying work to isolate it from my code and commit. if anyone looking for some assistance on this feature you can contact me
