### ISSUE TITLE
Inputstream

### ISSUE THREAD

**Issue by rcketscientist** [davemorrissey/subsampling-scale-image-view#305]
Any particular reason why the constructor doesn't support `Inputstream`?  I have raw images I convert on the fly.  Currently the code passes streams, but I just attempted to convert via a `ContentProvider` and `Uri`, but the pipes seem to be way more effort than they're worth.  Any pitfalls if I add `InputStream` myself?

**Comment by davemorrissey** [comment]
InputStreams are not guaranteed to support the random access needed for reading tiles from a large image, so providing a constructor that accepts one is a recipe for confusion. The view would have to disable tiling (and probably EXIF orientation) automatically, leaving developers confused why the large image support is broken or the view simply crashes with an OOME. I prefer to avoid this confusion.

If a developer knows what the InputStream is, they can add a few lines of code to either decode it themselves, or write it to a file. This produces a much more predictable result.

**Comment by rcketscientist** [comment]
Maybe I'm missing something...where is the stream resuse?

Image:
```
ContentResolver contentResolver = context.getContentResolver();
inputStream = contentResolver.openInputStream(uri);
bitmap = BitmapFactory.decodeStream(inputStream, null, options);
```

Region:
```
ContentResolver contentResolver = context.getContentResolver();
inputStream = contentResolver.openInputStream(uri);
decoder = BitmapRegionDecoder.newInstance(inputStream, false);
```

BRD has a native copy of the image, there isn't a need to retain the stream which in fact you're closing immediately.  Can the Uri be opened more than once?

**Comment by davemorrissey** [comment]
Hmm that's true, I got my wires crossed there. However I would still prefer not to accept an input stream because it could be partially read, blocking or already closed, and I'd then have to handle the error states. It will also change the interfaces for the decoder classes. Technically it can be made to work, so you could fork it, but I don't plan to make the change here.

**Comment by rcketscientist** [comment]
Fair enough.  As (in:InputStream) is fairly standard I wanted to double-check there wasn't a hidden reason why it wouldn't work.  I attempted to slip a decoded image (bytes) through a `ContentResolver`, but the necessary pipes just didn't work.  I'll fire off a fork.
