### ISSUE TITLE
Elastic shrinkage

### ISSUE THREAD

**Issue by XiaoQiWen** [davemorrissey/subsampling-scale-image-view#307]
i hope add Elastic shrinkage,when  the size of the minScale  or maxScale，scale continue

**Comment by davemorrissey** [comment]
I'd like to do that, and did once look at how I could do it, but because of the way the view works it's quite complicated to do. I'll keep this open and hopefully have another look some day.

**Comment by XiaoQiWen** [comment]
I think can do it

in this method 
```
onTouchEventInternal() -->ACTION_MOVE   scale = Math.min(maxScale, (vDistEnd / vDistStart) * scaleStart);
change to scale = Math.min(maxScale*1.5, (vDistEnd / vDistStart) * scaleStart);
```
Remember to deal with fitToBounds（） and limitedScale()
Last modified ACTION_UP if(scale>maxscale) start animation

minScale as well

I hope my Suggestions can help you

**Comment by davemorrissey** [comment]
The difficulty is in changing `fitToBounds` and `limitedScale` so that they work differently when there is a gesture in progress, also calculating the "resistance" and the center position the image should spring back to on release.

**Comment by davemorrissey** [comment]
I'm closing this now because I'm not working on the library and won't be able to add complex enhancements like this.
