### ISSUE TITLE
A suggestion for gif

### ISSUE THREAD

**Issue by XiaoQiWen** [davemorrissey/subsampling-scale-image-view#308]
If the image is a GIF,The current will not display
You can add judgment：
```
public static boolean isGif(byte[] bytes) {

        if (bytes == null || bytes.length < 6) {
            return false;
        }

        byte[] info = new byte[6];

        System.arraycopy(bytes, 0, info, 0, 6);

        return new String(info).equalsIgnoreCase("GIF89A");

    }
```
and add a SkiaImageGifDecoder 
Finally add a GIF switch
I believe that a lot of people hope

**Comment by davemorrissey** [comment]
This is not really a priority. This view's purpose is to display huge images, and there is no support for decoding tiles from a GIF in Android's built in `BitmapRegionDecoder` class. The GIF format is not suited to large images, and animated GIFs could not be supported. Alternatives are available for developers who want to show small animated GIFs.

**Comment by davemorrissey** [comment]
By the way, if you disable tiling, small GIFs can be displayed.
