### ISSUE TITLE
Is it possible to get the image matrix?

### ISSUE THREAD

**Issue by EpiphX** [davemorrissey/subsampling-scale-image-view#309]
On a project, I needed to do some manipulations on the image matrix associated with the bitmap. Normally, on an ImageView I could call its getImageMatrix() method. 

To achieve a similar effect with this library, I added a getter for the private matrix field in a fork of this library. I was curious if there were any specific reasons why a getter to this matrix would not be made available and if there were any dangers in doing so.

**Comment by davemorrissey** [comment]
The matrix private field applies only to each individual tile so changes each time a tile is rendered. It might just about work if the image is small enough to be rendered without tiling, but there are no guarantees about its state or what it represents.
