### ISSUE TITLE
[RuntimeException] when using widget in recyclerview

### ISSUE THREAD

**Issue by gromiloff** [davemorrissey/subsampling-scale-image-view#312]
Using very simple: create list (recyclerview) of images (SubsamplingScaleImageView). All images are loading from remove server (without cache). So, when view state is visible - I try to load image.
All works fine,  but in one case (fast scrolling down and up) I get:

```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@1232b229
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:589)
at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1073)
```

version of lib:
'com.davemorrissey.labs:subsampling-scale-image-view:3.6.0'

**Comment by davemorrissey** [comment]
I don't think this is a bug with the library. You'd probably get the same kind of error using an ordinary ImageView. Can you change your code to make sure the view is not loaded with an image that's been recycled?
