### ISSUE TITLE
Rotate image issue

### ISSUE THREAD

**Issue by andresuarezz26** [davemorrissey/subsampling-scale-image-view#316]
I have been trying to rotate an image with the library but I noted that there is a reestriction with the angles. Does someome has a way of rotate a created bitmap (For example a pin) with any angle? Thanks.

**Comment by davemorrissey** [comment]
Duplicate of #16, #304. Check the forks listed in #304, they may do what you need, but if it's an overlay you're trying to rotate, check StackOverflow for answers on image rotation.
