### ISSUE TITLE
Can't invalidate cache

### ISSUE THREAD

**Issue by DennyWeinberg** [davemorrissey/subsampling-scale-image-view#318]
While using Glide, I can use setSignature in order to invalidate the cache for a single Image.
This isn't possible with this library, so I can't use it.

Is there any chance to add a feature like this?

**Comment by davemorrissey** [comment]
I haven't used Glide so don't know what this means. This library doesn't have a way to know when you're done with an image and it should be dropped from a cache, can't you do that from your Activity?
