### ISSUE TITLE
Maven integration

### ISSUE THREAD

**Issue by tom91136** [davemorrissey/subsampling-scale-image-view#32]
Hi, would it be possible to upload this library to maven central?

**Comment by DrOptix** [comment]
see also #31 

The issues are related because Gradle is using Maven repositories.

**Comment by davemorrissey** [comment]
Okay, there are enough people using this now that I should release it properly! I'm too busy right now but will do it as soon as I can.

**Comment by davemorrissey** [comment]
I have published the library aar file to the central maven repository with coordinates `com.davemorrissey.labs:subsampling-scale-image-view:2.2.0`. My apps are using a mix of old build systems and SDKs so could someone please confirm everything works as expected?

**Comment by davemorrissey** [comment]
Pom bug fixed and 2.2.1 is deployed. I've tested this with a new gradle project.

**Comment by Saketme** [comment]
@davemorrissey do you want to mention this in your wiki/readme?

**Comment by Saketme** [comment]
@davemorrissey any updates on sources?

**Comment by davemorrissey** [comment]
Opened #402 for sources. There's nothing new to release at the moment.
