### ISSUE TITLE
Visibility problem in ViewPager

### ISSUE THREAD

**Issue by jack-cook** [davemorrissey/subsampling-scale-image-view#320]
Image not show in next page when the next page is loaded but not visible, until next page is visible the image then be loaded, user will see nothing first.

**Comment by jack-cook** [comment]
I think the reason about this problem is that ViewPager will not draw page newly created page off screen until that page becomes visible. I guess this widget start to load image when onDraw called.

**Comment by webserveis** [comment]
I same poblem, in the page view, when swipe fast, appear image with retard.

**Comment by webserveis** [comment]
Here small solution https://github.com/davemorrissey/subsampling-scale-image-view/issues/37

**Comment by dmitrikudrenko** [comment]
@jack-cook Do you have a solution?

**Comment by webserveis** [comment]
Yo use `FragmentStatePagerAdapter`?

Add preload pages with `mViewPager.setOffscreenPageLimit(2);`

**Comment by dmitrikudrenko** [comment]
Yes, I do
