### ISSUE TITLE
Need to extend touch interface to SubSamplingImageView

### ISSUE THREAD

**Issue by el4711** [davemorrissey/subsampling-scale-image-view#322]
Wanted to base a new ImageView class on SubSamplingImageView and totally change the touch behaviour. SSIV cannot be extended in that regard, because everything is jumbled up in that big class, and a lot of the inner workings are intermingled with the gesture detector and onTouchEventInternal.

The following methods would need to go from private to protected:
- reset
- GestureDetector
- onTouchEventInternal

Also, a lot of the variables that are being used would need to go from private to protected, too, namely everything that is being touched inside the touch event evaluation.

This would, of course, be the hacky solution. A better way would be to split the class up, if that's even possible.

I am using a copied+(cleaned-up)+changed class for the time being, but I'd really like to simply override what needs to be overriden. I am not sure if anybody even likes the idea, and whether anyone or myself would do the honours. Since this is just a pet project for myself...

Cheers, Elmar.

**Comment by davemorrissey** [comment]
I prefer the library to have a simple public interface that works for most people, so it's hopefully impossible to corrupt its internal state by subclassing it, but easy to do common things like draw overlays with examples I can document clearly. Another concern is that I can't guarantee backward compatibility without a well defined interface.

I don't want to spend a lot of time responding to requests for help on how to achieve complex things, or fielding bug reports where it doesn't work the way somebody wants, so my approach has been to keep this library clean and simple and appropriate for most use cases, while encouraging those who need something different to fork it, and start hacking. Hope that makes sense!
