### ISSUE TITLE
SSIV for a game board + animated pieces

### ISSUE THREAD

**Issue by micabytes** [davemorrissey/subsampling-scale-image-view#326]
I wonder if a extended version of this would work for displaying a boardgame with game pieces on it (that may be moved and "animated" in the opposing players turn). Have this feeling that trying to invalidate a full-screen imageview 30-60 times a second wouldn't work out all that well, but the animation demo suggests that it should be possible to run it that way. Any thoughts on this?

**Comment by davemorrissey** [comment]
It's worth trying, but my experience has been that the view with no overlays drawn on top performs very well, and once you start adding overlays it takes a lot longer to render. I never worked out why.

**Comment by micabytes** [comment]
I already have a DIY view component based on SurfaceView (though I'll not take credit for it - much is inspired by [WorldMap](https://github.com/johnnylambada/WorldMap)), but I'm impressed with how smooth you managed to make this ImageView work which is why I'm thinking of looking into this (Good job, btw). I do worry what the fps will be like with overlay draws - will have to find some time for experimentation. Thanks for the feedback.
