### ISSUE TITLE
Image not show

### ISSUE THREAD

**Issue by tellezcoo** [davemorrissey/subsampling-scale-image-view#328]
Good day.

Sorry for my English.

I have a problem using the widget in a TabLayout with ViewPager to create tabs.

For some reason the image is not displayed.

```
SubsamplingScaleImageView imageViewSS = (SubsamplingScaleImageView) rootView.findViewById(R.id.imageViewPhoto);
ImageViewSS.setImage(ImageSource.uri (path));
```

In a normal activity it works.

**Comment by davemorrissey** [comment]
Please check logcat for errors, and search through closed issues for possible solutions. You should also attach the image you're having a problem with, and try other images to see if they're affected.
