### ISSUE TITLE
abstract BitmapRegionDecoder so that other implementations can be used

### ISSUE THREAD

**Issue by tom91136** [davemorrissey/subsampling-scale-image-view#33]
Android's skia library is pretty problematic in many ways(certain PNG file fails, color profile are not respected on some JPGs, random segfaults, low res images.....), some implementations like [RapidDecode](https://github.com/suckgamony/RapidDecoder) falls back to external libraries  such as libpng which solves all the problems.

Would it be possible to make BitmapRegionDecoder an interface and allow us to implement it?

**Comment by davemorrissey** [comment]
I've had a few bugs reported that I traced backed to skia and I agree it's pretty poor and getting worse, which makes my library unreliable for developers who don't control the format of the image they're displaying. This seems like a good solution. I'm busy starting a new job at the moment but will look at this when I can.

**Comment by davemorrissey** [comment]
I've been working on this but I've found that RapidDecoder has serious problems decoding JPGs using its own decoder. With large images it runs out of memory when loading tiles, which never happens with BitmapRegionDecoder. Also, when loading a tile that isn't at the left hand edge of the image, it decodes the wrong part of the image. That means RapidDecoder is unusable when you don't know the type or dimensions of the image, a common problem with gallery browsers.

With that in mind, I'm not sure there's much point in doing this, unless there are other libraries that have better JPG support. I will complete the work anyway and put it on a branch for review.

**Comment by davemorrissey** [comment]
I've pushed changes to the branch [`decoder-interface`](https://github.com/davemorrissey/subsampling-scale-image-view/tree/decoder-interface). You can implement the `ImageRegionDecoder` interface (your class must have a public default constructor) and call `imageView.setDecoderClass(MyImageRegionDecoder.class)` to use it. There's an example implementation using RapidDecoder [here](https://github.com/davemorrissey/subsampling-scale-image-view/blob/decoder-interface/sample/src/com/davemorrissey/labs/subscaleview/sample/imagedisplay/decoders/RapidImageRegionDecoder.java) but it does have critical bugs with JPG decoding as I mentioned above.

**Comment by davemorrissey** [comment]
The region decoding bug has been fixed. RapidDecoder is still slow with large JPGs and can run out of memory, but it does offer better format support. Changes merged to master and released (2.3.0). See the README for details.
