### ISSUE TITLE
Add this doc to wiki

### ISSUE THREAD

**Issue by HR** [davemorrissey/subsampling-scale-image-view#331]
Since many have already asked the question of how to get a Bitmap of the visible region, I have written the following docs after figuring it out myself. Please add it to the wiki so it can help others :)

---
--- Rendered ---
### Getting a Bitmap of the visible region

You can obtain a Bitmap of the current visible region (in the image view) of the source image by using the `viewToSourceCoord` for each diagonal coordinate of the rectangular image view (e.g. top left and bottom right) in order to map the view coordinates to the source image coordinates. Forming a `Rect` from the result, the [BitmapRegionDecoder](https://developer.android.com/reference/android/graphics/BitmapRegionDecoder.html) can then be used to decode the visible region to a rectangular Bitmap.

```java
SubsamplingScaleImageView imageView = (SubsamplingScaleImageView)findViewById(id.imageView);

// Get visible region source coordinates
PointF leftTopCoord = imageView.viewToSourceCoord(new PointF(0, 0));
PointF rightBottomCoord = imageView.viewToSourceCoord(new PointF(imageView.getWidth(), imageView.getHeight()));

// Create visible region rectangle from source coordinates
RectF visibleRectF = new RectF(leftTopCoord.x, leftTopCoord.y, rightBottomCoord.x, rightBottomCoord.y);
final Rect visibleRect = new Rect();

// Convert RectF to Rect (as required by BitmapRegionDecoder)
visibleRectF.round(visibleRect);

BitmapRegionDecoder decoder = BitmapRegionDecoder.newInstance(sourceImageFileStream, false);

// Decode the visible region to a Bitmap
Bitmap visibleWallBitmap = decoder.decodeRegion(visibleRect, null);
```
**Note that** when the image is zoomed out and has a border, converting a view coordinate that is in the border will return a source coordinate that isn't valid (either a negative x or y coordinate, or an x/y coordinate greater than the width/height of the image) and could cause decode failure.

--- Raw ---
```
### Getting a Bitmap of the visible region

You can obtain a Bitmap of the current visible region (in the image view) of the source image by using the `viewToSourceCoord` for each diagonal coordinate of the rectangular image view (e.g. top left and bottom right) in order to map the view coordinates to the source image coordinates. Forming a `Rect` from the result, the [BitmapRegionDecoder](https://developer.android.com/reference/android/graphics/BitmapRegionDecoder.html) can then be used to decode the visible region to a rectangular Bitmap.

```java
SubsamplingScaleImageView imageView = (SubsamplingScaleImageView)findViewById(id.imageView);

// Get visible region source coordinates
PointF leftTopCoord = imageView.viewToSourceCoord(new PointF(0, 0));
PointF rightBottomCoord = imageView.viewToSourceCoord(new PointF(imageView.getWidth(), imageView.getHeight()));

// Create visible region rectangle from source coordinates
RectF visibleRectF = new RectF(leftTopCoord.x, leftTopCoord.y, rightBottomCoord.x, rightBottomCoord.y);
final Rect visibleRect = new Rect();

// Convert RectF to Rect (as required by BitmapRegionDecoder)
visibleRectF.round(visibleRect);

BitmapRegionDecoder decoder = BitmapRegionDecoder.newInstance(sourceImageFileStream, false);

// Decode the visible region to a Bitmap
Bitmap visibleWallBitmap = decoder.decodeRegion(visibleRect, null);
```
```
**Note that** when the image is zoomed out and has a border, converting a view coordinate that is in the border will return a source coordinate that isn't valid (either a negative x or y coordinate, or an x/y coordinate greater than the width/height of the image) and could cause decode failure.
```

**Comment by davemorrissey** [comment]
Looks good, thanks! However I think it would make sense to add a `getVisibleRect` or `viewToSourceRect` method to the class which would make this much easier, so I'll try to find some time to do that.

**Comment by HR** [comment]
Great! There was a `viewToSourceRect` method a time ago  but was removed in https://github.com/davemorrissey/subsampling-scale-image-view/commit/757552dc43f1a7f58a22b57e138c8f6497bba624

**Comment by HR** [comment]
Just bring it back 😉

**Comment by davemorrissey** [comment]
Yeah it was private, and I refactored the class to re-use `Rect` and `Point` instances.

**Comment by davemorrissey** [comment]
I've added `viewToFileRect` and `visibleFileRect` methods which will return a rectangle from the source file that correctly takes into account the image orientation, the region displayed, and the actual width and height of the file.

Methods that return `source` coordinates don't take these into account so the old `viewToSourceRect` method wasn't suitable for this purpose. It does work fine if you're displaying the whole image in its native orientation, and only then because `BitmapRegionDecoder` handles negative coordinates.

I'll write a wiki article once this is released.
