### ISSUE TITLE
how could i get drawable like in imageview

### ISSUE THREAD

**Issue by superyxw** [davemorrissey/subsampling-scale-image-view#332]
i want get the drawable of the first tile

**Comment by AllanWang** [comment]
The imageview only ever holds a bitmap, and it's private. Notice that setting the image typically involves passing it from a file, uri, or bitmap. You can get the images once you have any of those and add it to your view.

**Comment by davemorrissey** [comment]
I'm not really sure what you mean by this - do you mean the whole image subsampled, or the top left tile for cases where rendering in tiles is required? Either way this is highly variable and depends on the phone's screen density and size as well as the view's settings. If you want to get part of your image, just use `BitmapRegionDecoder` from the Android SDK.
