### ISSUE TITLE
Can you please add simple click listeners in the code itself?

### ISSUE THREAD

**Issue by jahirfiquitiva** [davemorrissey/subsampling-scale-image-view#333]
So, instead of creating another custom view overriding some gestures/touch events, we could have something easier to use like:
`setOnSingleClickListener()`
`setOnLongClickListener()`
`setOnDoubleTapListener()`

or something like that, where one could call super or implement our own code but in an easier way

Thanks in advance

**Comment by davemorrissey** [comment]
Developers are going to want different things from the callbacks (e.g. view coordinates, image coordinates, current scale etc.) so I don't think there's a single simple listener interface that will work for everyone. There is already support for `OnClickListener` and `OnLongClickListener` and for those who require something more complicated, there are samples in the code and examples on the wiki with blocks of code that can be used, giving access to whatever state the developer needs.
