### ISSUE TITLE
Out of Memory Exception with Tiling Enabled

### ISSUE THREAD

**Issue by cedarbob** [davemorrissey/subsampling-scale-image-view#334]
I ran into an OOM exception trying to display a large, but not huge, photo.  At a glance, it looks like the code attempted to load the entire bitmap at once rather than as series of tiles, despite having tiling enabled.
I've attached the relevant logcat output.
[logcat-excerpt.txt](https://github.com/davemorrissey/subsampling-scale-image-view/files/1166607/logcat-excerpt.txt)

**Comment by davemorrissey** [comment]
Please try `setMinimumTileDpi(240)` (choose a number that's appropriate for you).
