### ISSUE TITLE
Zoomable viewGroup using same concept

### ISSUE THREAD

**Issue by vipulyaara** [davemorrissey/subsampling-scale-image-view#335]
I am sorry if this is totally unrelated and I do not know how to tag it as a question.

This library provides a very smooth zooming experience. Would you be able to create a zoomable viewGroup using the same layout? I have tried to make many changes to it and I am close but I cannot get the final desired results.
I have tried more than a dozen zoomable layouts and none of them work properly. Maybe you can give a try to it if you want. Or simply tell me if you think this is not possible using this library.

I apologise again for an unrelated question.

**Comment by davemorrissey** [comment]
I don't think it's possible using this library, about 99.9% of the code would be different if images were changed to Views :-)

**Comment by vipulyaara** [comment]
Oh okay. Thank you for the response. Please keep in mind that there is not even one good working open source zoomable layout if you are in mood to create another library in future :)
Have a nice day.
