### ISSUE TITLE
Image viewport too small, funky pan and zoom.

### ISSUE THREAD

**Issue by janneoksanen** [davemorrissey/subsampling-scale-image-view#339]
Hi, I'm having a little problem that I haven't been able to solve. If the image that I put in the SubSamplingScaleImageView is smaller than the screen, then the whole image container is apparently scaled down to the size of the image. Then if you pan or zoom some of the image just goes outside the invisible bounds and is not shown at all. It's hard to explain so I'll just give you some screenshots.

Here's the image initially:
![screenshot_20170808-100433](https://user-images.githubusercontent.com/11737110/29067625-b2ed48ec-7c33-11e7-89b8-f51d9e2bde15.png)

Here's the image when panned:
![screenshot_20170808-100442](https://user-images.githubusercontent.com/11737110/29067662-cd61151e-7c33-11e7-8ae6-03b88ca64f1e.png)

And here's the image when zoomed in a bit:
![screenshot_20170808-100453](https://user-images.githubusercontent.com/11737110/29067672-d3f73818-7c33-11e7-925e-061b4131f23d.png)

Is there a work-around to make the image container bigger, preferably the size defined in the layout XML?

**Comment by davemorrissey** [comment]
It's hard to see what's happening here because I don't know what the bounds of the view are, what the bounds of its parent are, or what your layout XML looks like. I think you just need to check your layout because this doesn't seem to be a bug with the view.

**Comment by janneoksanen** [comment]
They're set to match_parent to make it take up the whole screen. Somehow, however, the view gets resized to wrap_content.

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:gravity="center"
              android:orientation="vertical">

    <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone"
    />


    <ProgressBar
        android:id="@+id/progressBar"
        style="?android:attr/progressBarStyleLarge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:visibility="visible"/>

</LinearLayout>

**Comment by davemorrissey** [comment]
Try using Hierarchy Viewer to find the boundaries of each element, or for a quick and dirty method, put a background color on each element to see where it is.

**Comment by davemorrissey** [comment]
Did you manage to solve this?

**Comment by janneoksanen** [comment]
If I remember correctly I wasn't able to make it work 100% to my
satisfaction. I'm no longer working on the project so I can't double check.
Thanks for your help anyway.

Janne
