### ISSUE TITLE
Switch to page on zoomed image not always works

### ISSUE THREAD

**Issue by Chesteer89** [davemorrissey/subsampling-scale-image-view#34]
SubsamplingScaleImageView, line 539.

Changed to:
```java
if (lastX == vTranslate.x || (lastY == vTranslate.y && dy > 10) ){
   isPanning = true;
} else if (dx > 5 || lastX != vTranslate.x) {
   // Haven't panned the image, and we're at the left or right edge. Switch to page swipe.
   maxTouchCount = 0;
   handler.removeMessages(MESSAGE_LONG_CLICK);
   getParent().requestDisallowInterceptTouchEvent(false);
 }
```

**Comment by davemorrissey** [comment]
This looks good, I'll do some more testing before committing it.

**Comment by davemorrissey** [comment]
I've noticed this change causes the same problem I've described in #29 - a pan gesture can cause the next image to suddenly appear half way across the screen. Because I couldn't find a solution for this, I decided to make it necessary to pan to the edge of the image, lift and pan/swipe again to move to the next image. Unfortunately that doesn't work reliably, so I'll try to work out why.

**Comment by Chesteer89** [comment]
Yes, you're right. It works fine for me on SubsamplingSIV, but on SIV it sometimes change page in a middle of a resized image. Maybe just calculate is resized image near edge (+-5px)?

**Comment by Chesteer89** [comment]
Ok, you can fix it by simple add lines:
```java
// Detect flings, taps and double taps
        if (detector == null || detector.onTouchEvent(event)) {
            isZooming = false;
            isPanning = false;
            maxTouchCount = 0;
            return true;
        }
```
in both classes. The problem was that on fling finish isPanning was not setted to false.

**Comment by davemorrissey** [comment]
Yes I realised the same thing last night, I'll try this fix later.

**Comment by davemorrissey** [comment]
I've made this change and another adjustment that detects a horizontal one finger move at the edge. This greatly improves the behaviour but there may still be some tweaks that could perfect it.

**Comment by Chesteer89** [comment]
Cool, i'll try a new version but after my small changes it works fine. Good job.
