### ISSUE TITLE
1024*27000 picture can't be displayed

### ISSUE THREAD

**Issue by yorkwang** [davemorrissey/subsampling-scale-image-view#340]
Maybe 27000 is too long, is there any way to fix it?

**Comment by davemorrissey** [comment]
I cannot help with this kind of problem unless you include details - error messages, what gets displayed, the image you're using, the phone you have a problem with, whether other phones are affected etc.

**Comment by yorkwang** [comment]
Here is an example picture: http://imanga.co/img/d39dd2e38939b39e/12/1.jpg, 
several users which are using my app reported this problem to me, and I have tested on my phone, it can't be displayed, but the smaller pictures(<20000) can be displayed. Maybe it's a tile size issue.

**Comment by yorkwang** [comment]
Now I got it, it will be displayed after about 5s because the pictures are too long. Sorry about it!
