### ISSUE TITLE
Load Image From Archive

### ISSUE THREAD

**Issue by sethchhim** [davemorrissey/subsampling-scale-image-view#341]
I am trying to load an image from archive without writing to disk. I have access to the inputstream, is it possible to load directly from inputstream? Thanks for any recommendations!

**Comment by davemorrissey** [comment]
The only way to do this at the moment is to create instances of `ImageRegionDecoder` and `ImageDecoder` that contain your input stream and read from it. You would then pass any dummy URI to `setImage` to make the view load from the input stream.

I'm not sure how well this will work in practice. A lot depends on the lifecycle of the input stream and whether it supports random access, as required for tiling. If any other thread reads from or closes the input stream the view will stop working. If your image is not large enough to require tiling - anything under 3000x3000 should be fine on most modern devices - it's best to decode it yourself using `BitmapFactory`.

Here's an example of custom decoders using an input stream: https://gist.github.com/davemorrissey/1f247d415e21ed10fddfd7fee49b4ff3
