### ISSUE TITLE
Add "top padding" to image only

### ISSUE THREAD

**Issue by broakenmedia** [davemorrissey/subsampling-scale-image-view#343]
I'm expanding on the PinView extension, such that when the image is loaded it also generates 1-X pins, these pins can be dragged and placed on a position on the image to "Mark the spot".

However as you can see, these pins are displayed on-top of the image and while visible on this particular image will likely not have enough contrast on others to see them properly. I'm hoping to find a solution that would allow me to simply push the start of the image down something like 50px.

I tried using padding-top for this but it also affects the left right and bottom spacing.

There was also this "mega-hack":

    canvas.clipRect(canvas.getClipBounds().left, 50, canvas.getClipBounds().right, 
    canvas.getClipBounds().bottom, Region.Op.REPLACE);
        super.onDraw(canvas);
    canvas.clipRect(canvas.getClipBounds().left, 0, canvas.getClipBounds().right, 
    canvas.getClipBounds().bottom, Region.Op.REPLACE);

But that of course clips part of the image itself.

--------------------

![capture](https://user-images.githubusercontent.com/1523918/29575452-721dce02-875c-11e7-8455-da7abef9cab3.PNG)

**Comment by xbroak** [comment]
Just as i posted this i gave this a shot:

```
canvas.translate(0, 50);
super.onDraw(canvas);
canvas.translate(0,-50);
```

While it does actually appear to work, still feels like a massive hack!

**Comment by davemorrissey** [comment]
Why not give the pins an outline or drop shadow so they'll show up, and/or draw a semi-opaque dark circle underneath them until they're moved?

Padding is kind of a tricky concept when you can zoom in to the image, so it's hard to get the right behaviour for everyone. It's not really well supported and generally expects equal top/bottom padding.

**Comment by broakenmedia** [comment]
Yeah, that's what i've resorted to for the time being but it's not really my call sadly, hopefully the feedback is positive and i won't have to spend another 2 days looking for solutions aha.

It's definitely a tricky one, i even tried using a Picasso transformation to modify the source image it self, drawing a white bar along the top for the markers to sit on, but as you mentioned, it wasn't consistent when zooming in/out.

**Comment by broakenmedia** [comment]
Looks like they were happy! My only problem now is that because they're pins, the top left corner of the view is where it's being scaled around, meaning when zooming the tip of the arrow never aligns with the correct part of the image

**Comment by davemorrissey** [comment]
Is that something you can fix by offsetting the image to place the arrow in the correct place? The sample code does that.

**Comment by broakenmedia** [comment]
It is indeed something i can do... thanks for that, no idea why i didn't see it, saved me my evening!
