### ISSUE TITLE
Large, irregular size images

### ISSUE THREAD

**Issue by Chesteer89** [davemorrissey/subsampling-scale-image-view#35]
Hi,

Did you tested SubsamplingScaleImageView on irregular size images, for example 480x4000? I know it should worked, but is it optimized? I'm looking for an idea to display it, cause making listview with N splited images is not a best workaround, especially when you want to zoom and pan.

**Comment by davemorrissey** [comment]
Yes, it's optimised for images like that.

**Comment by Chesteer89** [comment]
E/SubsamplingScaleImageView﹕ Failed to initialise bitmap decoder
    java.io.IOException: Image failed to decode using JPEG decoder
            at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
            at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:123)
            at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:149)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapInitTask.doInBackground(SubsamplingScaleImageView.java:1022)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapInitTask.doInBackground(SubsamplingScaleImageView.java:998)
            at android.os.AsyncTask$2.call(AsyncTask.java:264)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)

JPG file, 600x6600.

**Comment by davemorrissey** [comment]
Please attach the image.

**Comment by Chesteer89** [comment]
http://static.bezuzyteczna.pl//static//content//807fa2a3ba7ed3a0cd9a.jpg

**Comment by davemorrissey** [comment]
I can't look at this in detail until later on, but that error usually means the image is in a format Android's native decoder cannot handle. One possibility is it's in CMYK format, so try RGB and make sure it is not indexed.

**Comment by davemorrissey** [comment]
The image didn't work for me either, so I opened it in GIMP, and saved it again with no changes. ImageMagick's identify command showed no differences in attributes between the original and new versions, but the new version worked fine. BitmapRegionDecoder and the Skia library it uses are quite unstable but sometimes re-exporting an image like this can fix problems.

Alternatively, I've added an option to use a custom decoder, but the only suitable decoder I know of (RapidDecoder) doesn't handle this image well because it's too large.

This isn't a bug in my library, it's a problem with Android.

**Comment by Chesteer89** [comment]
Unfortunatelly it looks like BitmapRegionDecoder have some problem with some images. It works fine on iOS, WP, on web too, so it's android problem only. Can we add new method to handle errors, for example:

 // Handle errors
private static final int MESSAGE_ERROR = 2;

// Error listener
private OnErrorEventListener onErrorListener;

public interface OnErrorEventListener{
    public void onError(Exception e);
}

public void setOnErrorListener(OnErrorEventListener eventListener) {
    onErrorListener=eventListener;
}

to get errors? And send events in doInBackground:

if(view != null && view.onErrorListener!=null)
   view.onErrorListener.onError(e);

**Comment by davemorrissey** [comment]
An error listener is of limited use because many of the decoding problems the skia library has don't result in any error, they just return a corrupt or blank image, and there's no way to detect this. Please see my comments above, you can simply load and save the image again in another editor, or replace the decoder implementation.

**Comment by Chesteer89** [comment]
I mean we can use listener to handle exception in main activity. It could be useful on applications, when you cannot modify image - base on what you get. I understand i can use another decoder, but it looks like there's no even one, which can handle big images. In my case i can simple handle error in main activity and remove or display error. It's useful when you're working with viewpager etc.

**Comment by davemorrissey** [comment]
The decoder silently fails and returns a corrupt or blank image in more than half the cases I've seen. I don't want to add an error listener when there's no way to detect the majority of errors, but you could add this to your own fork if you need it.

**Comment by JWBlueLiu** [comment]
http://n.sinaimg.cn/auto/transform/20160316/AgOL-fxqhmve9261797.jpg
load fail
Failed to initialise bitmap decoder

**Comment by zondaOf2012** [comment]
I think you can refer to [this](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/04.-Custom-decoders).
Besides, [this](https://gitee.com/zonda89/subsampling-scale-image-view) is my solution, we want to help!

**Comment by kaycool** [comment]
SubsamplingScaleImageView: Failed to initialise bitmap decoder
    java.io.IOException: Image failed to decode using JPEG decoder



https://tdata.quanziapp.com/files/syBmmnB/E56F3098-D99E-422C-A1F0-638AD4275B95.jpg?x-oss-process=image/resize,w_214/format,jpg/interlace,1
