### ISSUE TITLE
Upgrade to the latest version（3.7.0）DoubleTapZoom can not work with 'imageView.setImage(ImageSource.uri(uri));'

### ISSUE THREAD

**Issue by 16fangougou** [davemorrissey/subsampling-scale-image-view#350]
Yesterday I upgraded to the latest version (3.7.0) and found that it was not working properly.

```
imageView.setImage(ImageSource.uri(uri));
```
But in 3.6.0,it can work good anymore.

Does the new version need to be configured to  change?

@davemorrissey

**Comment by 16fangougou** [comment]
My current solution is：
Use glide to load the image.
```
@Override
    public void loadImage(Context context, final int resizeX, int resizeY, final SubsamplingScaleImageView imageView, final Uri uri) {
//	    imageView.setImage(ImageSource.uri(uri));
	    Glide.with(context)
			    .load(uri)
			    .downloadOnly(new SimpleTarget<File>() {
				    @Override
				    public void onResourceReady(File resource, GlideAnimation<? super File> glideAnimation) {
					    imageView.setImage(ImageSource.uri(Uri.fromFile(resource)));
				    }
			    });
    }
```

**Comment by davemorrissey** [comment]
I can't see any problems with double tap zoom using the sample library. That doesn't use URIs to load the image but I don't know of any reason why that would make a difference. Please could you describe the problem in more detail - what exactly are you trying, what happens and is there any error message? Can you try loading a resource or asset instead to see if that makes a difference?

**Comment by 16fangougou** [comment]
@davemorrissey 
Same picture, and use 'imageView.setImage(ImageSource.uri(uri))'.

3.7.0 zoom fail, logs:
![image](https://user-images.githubusercontent.com/17920617/31872143-f74ca0ba-b77e-11e7-8452-35d36412acc2.png)


3.6.0 zoom success. no log.

**Comment by 16fangougou** [comment]
@davemorrissey

**Comment by davemorrissey** [comment]
What is the URI you're using? It looks like it must start with `android.resource://` and that resource doesn't exist.

**Comment by 16fangougou** [comment]
The URI like this:```content://media/external/images/media/6580```, and it exits.

**Comment by davemorrissey** [comment]
Can you debug this and find out why `SkiaImageRegionDecoder` is reaching line 70 if your URI doesn't contain `android.resource`? That's a mystery to me.

**Comment by 16fangougou** [comment]
Is this useful?

![image](https://user-images.githubusercontent.com/17920617/31993682-98f7e36e-b943-11e7-8680-7d39d09cd8fd.png)

**Comment by davemorrissey** [comment]
Please can you try version 3.7.1?

**Comment by 16fangougou** [comment]
👌,I will try it.Thanks~

**Comment by 16fangougou** [comment]
3.7.1 can double tap zoom, but OOM:
![image](https://user-images.githubusercontent.com/17920617/32033822-7bb9d6d6-b9d4-11e7-831f-92ad39bb59ed.png)

**Comment by davemorrissey** [comment]
Release 3.7.2 is available and should fix this problem. The 3.7.0 release contained a jar instead of an aar, so was missing the meta information for the custom attributes. 3.7.2 uses updated build scripts but contains the aar.

**Comment by 16fangougou** [comment]
thank you very much! The latest version solves all my problems.👏

**Comment by davemorrissey** [comment]
Thanks!
