### ISSUE TITLE
imageView.setImage(ImageSource.uri(uri)) not working

### ISSUE THREAD

**Issue by genyue** [davemorrissey/subsampling-scale-image-view#351]
```
private void initialiseImage() {
        SubsamplingScaleImageView imageView = (SubsamplingScaleImageView)findViewById(id.imageView);
        Uri uri = Uri.fromFile(new File("/storage/emulated/0/Download/2015 IMG_0005.JPG"));
        imageView.setImage(ImageSource.uri(uri));
}
```

where did i go wrong?
i cannot get it to load my image. its showing nothing

![imagesourcenotworking](https://user-images.githubusercontent.com/33000392/31861791-4762ce3e-b75d-11e7-843e-89bd15e72b15.png)

**Comment by davemorrissey** [comment]
Any logs?

**Comment by genyue** [comment]
![imagesourcegradlelog](https://user-images.githubusercontent.com/33000392/31869442-38b45f36-b7d2-11e7-98bf-dcbf6f36c8d5.png)
is this the log u  are looking for?

**Comment by davemorrissey** [comment]
No, the logs from the device when you try to load the image.

**Comment by genyue** [comment]
![imagesourcelogcat](https://user-images.githubusercontent.com/33000392/31881190-04d7fa2a-b80d-11e7-9bed-82f6b55e89b8.png)
LogCat?

**Comment by davemorrissey** [comment]
Please search StackOverflow and Google for guides on using logcat to debug problems.
