### ISSUE TITLE
3.7.0 Exception Caused by: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by Shakezulla57** [davemorrissey/subsampling-scale-image-view#354]
I'm getting this exception when moving from 3.6 to 3.7. The exception is not happening in 3.6.

```
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 5 to color: type=0x1
	at android.content.res.TypedArray.getColor(TypedArray.java:473)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.<init>(SubsamplingScaleImageView.java:328)
```

Here's the xml, its in a stand alone file.

```
<com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

```

Here's the code that instantiates it

```
// exception thrown at this line
view = getLayoutInflater().inflate(R.layout.full_screen_image, container, false);
final SubsamplingScaleImageView imageView = (SubsamplingScaleImageView) view;
```

**Comment by davemorrissey** [comment]
There's a common theme with other bugs in 3.7.0 - the constructor is being called with an `AttributeSet` with spurious data in it. I can't see why this would happen and haven't changed any code related to it, but I did merge a PR that updated all the build tools and maybe that's caused an issue. I can't reproduce this and haven't found any answers yet so I'll probably try rolling back the build tools change.

**Comment by Shakezulla57** [comment]
@davemorrissey That's pretty strange, thanks for the feedback.

**Comment by davemorrissey** [comment]
Please can you try version 3.7.1?

**Comment by Shakezulla57** [comment]
I tried 3.7 again quick just as a baseline before I tried 3.7.1. This time 3.7 worked, however the build it wasn't working on was a release build with proguard on. So that could be the issue; if I have time today I'll run a proguarded version.

**Comment by davemorrissey** [comment]
Okay thanks - let me know how you get on! 3.7.0 included an update of all the build tools, but also added a proguard config file with a simple "keep everything" rule. I've assumed the build tools caused the problem but maybe it was the proguard config. One other developer reported 3.7.1 fixed their related issue but didn't elaborate on whether they were testing a release build.

**Comment by davemorrissey** [comment]
Release 3.7.2 is available and should fix this problem. The 3.7.0 release contained a jar instead of an aar, so was missing the meta information for the custom attributes. 3.7.2 uses updated build scripts but contains the aar.
