### ISSUE TITLE
How to add marker/cluster?

### ISSUE THREAD

**Issue by Balaje1408** [davemorrissey/subsampling-scale-image-view#358]
How to add marker/cluster in the subsampling-scale-image-view? and handle it same as like maps cluster. for example, on click of the cluster, drag the marker, resize marker on zoom change?

**Comment by davemorrissey** [comment]
I'm sorry but I can't provide help with the development of your app, please ask questions on StackOverflow.

**Comment by Balaje1408** [comment]
fine. Is it possible to add those things in the view? Just give me assurance whether the library is flexible to do those things. I will work out.

**Comment by davemorrissey** [comment]
It's flexible, so you should be able to do this.
