### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SherlockGougou** [davemorrissey/subsampling-scale-image-view#359]
I suggest adding ``` hardwareAccelerated = true ``` in project's AndroidManifest.xml, If minSdkVersion above 11(Android 3.0).

```
        <activity
            android:name=".ImagePreviewActivity"
            android:hardwareAccelerated="true"
            android:theme="@android:style/Theme.Black.NoTitleBar"/>
```

It will Improve fluency very well. You can add it in README or WiKi to tell coders

Sorry my english is not good.T_T

Do you understand?

**Comment by davemorrissey** [comment]
Hardware acceleration is on by default for apps targeting SDK 14+, which should be all apps by now. It will only be disabled if a developer has chosen to disable it, so I don't think there's a need to document this.
