### ISSUE TITLE
Regional bitmap coding

### ISSUE THREAD

**Issue by imi5** [davemorrissey/subsampling-scale-image-view#36]
hi
can i write regionally several images on a big blank jpeg image(10000*10000 pixel) on device's storage using this library and read the final image? 
exactly the opposite of what BitmapRegionDecoder does in it(without out of memory error).
thanks

**Comment by davemorrissey** [comment]
Unfortunately I can't help with this, my library is for displaying images, not writing them. I recommend asking this question on stackoverflow.

**Comment by imi5** [comment]
Thank you anyway :)
