### ISSUE TITLE
Possible to pan while zoomed programmatically?

### ISSUE THREAD

**Issue by braydondavis** [davemorrissey/subsampling-scale-image-view#364]
Is it possible to pan around an image with code while the image is zoomed in? I've tried using View.SetX/View.SetY which works for moving around on the image, however, it does not refreshing the tiling, so only a little rectangle is loaded and can move around.

I have a canvas that draws on top of the SubsamplingScaleImageView which is blocking the functionality of the built in panning an zooming which is why I'm trying to do it with code.

**Comment by davemorrissey** [comment]
Have you read the wiki? There are instructions there on how to do this.
