### ISSUE TITLE
This method setMinScale() doesn't work?

### ISSUE THREAD

**Issue by tyl210110** [davemorrissey/subsampling-scale-image-view#368]
This method setMinScale() doesn't work?

**Comment by davemorrissey** [comment]
Please state expected and actual behaviour, details of the test device, and supply your code and image when raising bugs.

**Comment by tyl210110** [comment]
Has resolved,must add this method   .setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
