### ISSUE TITLE
quick initial render for very large images?

### ISSUE THREAD

**Issue by arpruss** [davemorrissey/subsampling-scale-image-view#37]
I would like to use this library for some very large jpeg images (20480x20480, about 20mb). Putting one of the images into your sample, I see that the initial load takes 5 seconds on my Nexus 7. That's pretty decent for such a large image (my laptop takes two or three seconds, too), but I wonder if there would be a way to extend your library to allow for a pre-scaled smaller image to be displayed while the library is working away on a large one, for the sake of instant user gratification. After the initial render, your library's scrolling is really smooth, and it could make for a great improvement in my app (LunarMap, which currently uses a kludgy method with lots of pre-rendered tiles at different zoom levels).

I could extend your library in this way, but you will know a lot better how to most neatly implement it, and how it would most neatly fit with your ideas how the API works. Advice would be appreciated.

**Comment by davemorrissey** [comment]
Hi arpruss, there is a trick you can use to get this effect without any changes to the view. Using a relative layout you can have an ordinary image view that displays a low resolution preview with scale type CENTER_INSIDE (or FIT_CENTER), and overlay subsampling on top in exactly the same place.

The subsampling view is transparent while loading, so the preview will show through until the loading is complete. After that, the subsampling view's image should appear in exactly the same place at minimum scale, so the preview can't be seen. You could also have a loading message or graphic between the preview and the subsampling view.

This would look roughly like this:

    <RelativeLayout>
        <ImageView android:src="@drawable/preview"/>
        <TextView android:text="Loading..."/>
        <SubsamplingScaleImageView/>
    </RelativeLayout>

**Comment by arpruss** [comment]
That's a really nice and simple idea. But the ideal solution would, I think, be integrated into the subsampling imageview, so that the user could already begin scrolling and zooming. It would make the app feel more responsive.

**Comment by davemorrissey** [comment]
That approach would allow interaction earlier but unfortunately there are complications. Until the BitmapRegionDecoder is initialised - which accounts for around half the time it takes to display the base layer - the dimensions of the full size image aren't known so it isn't possible to pan and zoom. That's why I'd normally recommend using a preview underneath the view - blocking gestures until it's loaded could be an advantage.

The workaround for this would be allowing the developer to declare the dimensions, which is okay as long as they provide the right values and a preview image that closely matches the w:h ratio. This feels like a hack to me, and it might be fragile.

I'd like to avoid over-complicating the view (well, more than I have already) and want to be sure that new features are generic enough for everyone, and I'm not convinced I have the right solution to this problem. It needs more thought.

**Comment by arpruss** [comment]
A memory-costly method might be to underlay a subsample scaled view of the smaller image under the larger one, and then to kill it when the larger one becomes available. Or would the overlaid image block controls from working on the lower one?

**Comment by davemorrissey** [comment]
The two views would not be linked so one would not scale the other, and yes, the lower one would not receive touch gestures. This would look and behave the same as an ordinary image view underneath.

**Comment by davemorrissey** [comment]
I've been experimenting with built in preview support, and it will make the view a lot more complicated and less stable. It breaks rules about which fields can be trusted at each phase of the view's lifecycle, and that makes troubleshooting problems much harder. I'd rather not add this feature, and I think the static preview underlay is the best I can suggest.

It might be possible to overlay the preview in a ScaleImageView with its maxScale set a high value, then when the full image is ready, hide the overlay and use its scale and center to calculate a new scale and center for the full image.

**Comment by laurencedawson** [comment]
Would it be possible to perhaps get a callback once the SubsamplingImageView has drawn the initial image. That way we could load the image quickly and then switch off once SubsamplingImageView has loaded.

**Comment by davemorrissey** [comment]
Not a bad idea, could be useful for some other things, but it doesn't help in this situation. It wouldn't enable scaling of the image before the dimensions of the full size image are known, so it doesn't improve on the suggestion of using a preview image positioned underneath the subsampling view.

**Comment by arpruss** [comment]
Is there a way to enable the initial scaling to be faster when the dimensions of the full size image are known? Is there other data besides dimensions that one could cache to speed up loading on subsequent occasions?

**Comment by davemorrissey** [comment]
Yes, provided the developer knows the size of the full size image they can provide that along with a preview, however I was investigating this as a solution and it complicates the view significantly, adding several possible loading states, and size values that can't be trusted. I'm still planning to try this approach anyway but don't have the time at the moment.

**Comment by davemorrissey** [comment]
An mostly untested cut of this feature is on branch `preview-image`. This needed significant refactoring but also provided an opportunity to combine the two view classes into one. There are some quite minor backwardly incompatible changes so it will be released as a major version bump once I've finished testing.

**Comment by arpruss** [comment]
Thanks! I'll have a look at it.

I've been playing with the thought of implementing this via a custom decoder class. Start a thread loading the big image, but until that thread completes, serve rescaled data from the small image. Then send a refresh to the view when the thread completes.

p.s. I also tried using a progressively encoded jpeg, and init was 5x slower than for a non-progressive one.

**Comment by davemorrissey** [comment]
Released in v3.0.0.

**Comment by davemorrissey** [comment]
BTW LunarMap is a great app and I'd like to include it on the readme if you'll be using this view and that's okay with you?

**Comment by arpruss** [comment]
I've been too busy with other projects to convert LunarMap to use the
library. It's a high priority but my day job has a higher priority.
Thanks so much for updating the library!
I should have LunarMap updated in a month or so and will let you know.
