### ISSUE TITLE
I want the view with viewpager same scale;

### ISSUE THREAD

**Issue by Chenshuai770** [davemorrissey/subsampling-scale-image-view#370]
in my project ,i have two image ; now, i need lerft to right ,the left image has changed ,and the rigth is same change as left;and when rigth to left ,also; thank you very much;my english is not very well;

**Comment by Chenshuai770** [comment]
and i want to kenw
 Log.d("FourActivity", "mIvFour1.getTranslationX():" + mIvFour1.getTranslationX());
when i translation the result is 0;how can i get reslut with same in Debug;

**Comment by Chenshuai770** [comment]
in my viewpage ,i have not use the fragment

**Comment by davemorrissey** [comment]
There is a wiki and a sample project. Please read these before opening issues. If you need further help, it is better to ask on StackOverflow.
