### ISSUE TITLE
I hava to Image to compare,but the translation is not same;

### ISSUE THREAD

**Issue by Chenshuai770** [davemorrissey/subsampling-scale-image-view#372]
in my item ,i have two Image in LinearLayout the orientation is vertical; i want to scale one ,and the same sacle in two;i use the way to come true it ;
but i find i can not do the way of singe move;
when i move the first image ,the second image was not move to first way; so i want to kenw how can i do it;
thank you very much!

**Comment by Chenshuai770** [comment]
i use the code to come true the scale ,but i can not come true the same translate;
        mIvTen1.setOnStateChangedListener(new SubsamplingScaleImageView.OnStateChangedListener() {
            @Override
            public void onScaleChanged(float v, int i) {
               //mIvTen2.setImage(ImageSource.resource(R.mipmap.bbb),mIvTen1.getState());

               mIvTen2.setScaleAndCenter(v,mIvTen1.getCenter());
            }

            @Override
            public void onCenterChanged(PointF pointF, int i) {

            }
        });


        mIvTen2.setOnStateChangedListener(new SubsamplingScaleImageView.OnStateChangedListener() {
            @Override
            public void onScaleChanged(float v, int i) {
                mIvTen1.setScaleAndCenter(v,mIvTen2.getCenter());
            }

            @Override
            public void onCenterChanged(PointF pointF, int i) {

            }
        });

**Comment by Chenshuai770** [comment]
i use the code to come true the same scale but i can not come true the same translate

**Comment by davemorrissey** [comment]
Please read the contributing guidelines before opening an issue. There is a wiki and javadoc available, and I'm unable to help you build your app if you get stuck.
