### ISSUE TITLE
6.0以下手机加载大图图片缓慢，查看大图后等待一会才会出来7.0手机很快，要是能解决一下这个问题就好了

### ISSUE THREAD

**Issue by wutongmo** [davemorrissey/subsampling-scale-image-view#373]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Insufficient information provided.
