### ISSUE TITLE
Update to SDK 27 not pushed to Maven

### ISSUE THREAD

**Issue by createS0ftware** [davemorrissey/subsampling-scale-image-view#374]
Hi 

The latest release 3.9.0 does not appear to have the latest gradle update from earlier this week and it's causing a Gradle error "exact same version specification..."

Specifically com,android.support.exifinterface:26.1.0 

Can you please update it ?

Thanks

**Comment by davemorrissey** [comment]
You'll need to add your own exifinterface dependency for the correct version for your project. I assume this is the standard way of solving this problem, since not all projects will track the latest support lib versions.
