### ISSUE TITLE
How to load image with url. Picasso not working. 

### ISSUE THREAD

**Issue by cihangulx** [davemorrissey/subsampling-scale-image-view#378]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Insufficient information provided, please complete the provided template. Please also view the wiki and closed issues before opening a new issue - you are very likely to find the answer to your question there.

**Comment by davemorrissey** [comment]
No further information has been provided, so I’ll close this now.

**Comment by naguchennai** [comment]
there is no documents about loading image from url .. that means its not work with network image only work with local image

**Comment by lx5475** [comment]
To load an image from image URL, you should use Universal Image Loader(https://github.com/nostra13/Android-Universal-Image-Loader).

try this:
```java
ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(this).build();
        ImageLoader imageLoader = ImageLoader.getInstance();
        imageLoader.init(config);

        imageLoader.loadImage("your image url", new SimpleImageLoadingListener() {
            @Override
            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                // Do whatever you want with Bitmap
                pinView.setImage(ImageSource.bitmap(loadedImage));
            }
        });
```

**Comment by davemorrissey** [comment]
That solution will cause an OutOfMemoryError if the image is big. There's a page on this in the wiki: https://github.com/davemorrissey/subsampling-scale-image-view/wiki/X.-Picasso,-Glide,-Fresco
