### ISSUE TITLE
How to change  pin image when click on it 

### ISSUE THREAD

**Issue by tranminhlan** [davemorrissey/subsampling-scale-image-view#379]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
This is a question about how to build your own extension to the library, which unfortunately I can’t help with. Questions like this should usually be asked on StackOverflow, but I’ll leave it open for a week to see if another developer can help you.
