### ISSUE TITLE
How to listener zoom method  in activity

### ISSUE THREAD

**Issue by tranminhlan** [davemorrissey/subsampling-scale-image-view#380]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Insufficient information provided. Please complete the template and describe what you are trying to do, and what you have tried.

**Comment by tranminhlan** [comment]
Thanks for your response.
 I have find solution for handle event when  zoom photo.
I use it for get info current zoom of image. 
  imageView.setOnStateChangedListener(new SubsamplingScaleImageView.OnStateChangedListener() {
            @Override
            public void onScaleChanged(float newScale, int origin) {
                Toast.makeText(getApplicationContext(), "Scale" + newScale, Toast.LENGTH_SHORT).show();

            }

            @Override
            public void onCenterChanged(PointF newCenter, int origin) {

            }
        });

**Comment by davemorrissey** [comment]
That looks right. What’s the problem you’re having?

**Comment by davemorrissey** [comment]
Closing because it's unclear what you're asking.
