### ISSUE TITLE
Subsampling-scale-image-view Can load gif?

### ISSUE THREAD

**Issue by MrBoudar** [davemorrissey/subsampling-scale-image-view#383]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Duplicate of #208, #297, #308. Please read the contributing guidelines before opening new issues, and do not leave the template blank.
