### ISSUE TITLE
How to implement drag pin using pinView extension.

### ISSUE THREAD

**Issue by kdreamix** [davemorrissey/subsampling-scale-image-view#385]
Thanks for creating such a great library, I have already modified it to add multiple pins on the view and it works well. But I am having a hard time on implementing pin dragging. Since overriding onTouchEvent seems to inhibit other functionalities such as zooming and double tap.

What would you suggest to implement such feature? Thanks.

**Comment by kdreamix** [comment]
Figured it out.

**Comment by samernady** [comment]
@kdreamix : 
Would you please explain how did you implement this.
I am stuck with this for the last few days

**Comment by crjacinro** [comment]
Hi @kdreamix  @samernady  @davemorrissey, can you please explain how to implement this ?

**Comment by ElyDantas** [comment]
@kdreamix lmao the guy vanished and took the answer with him, come back here gollum  😳
