### ISSUE TITLE
Crashes at BitmapRegionDecoder

### ISSUE THREAD

**Issue by tibbi** [davemorrissey/subsampling-scale-image-view#386]
Since upgrading to 3.9.0 users are getting some native crashes related to BitmapRegionDecoder. It is happening on Android 7.0 and Android 7.1 only, nowhere else. It was happening even before me switching to using the support exifinterface (related to #369). Im not using any custom BitmapRegionDecoder, Subsampling is used at https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/kotlin/com/simplemobiletools/gallery/fragments/PhotoFragment.kt#L246 . I see in changelogs that something related to that has been updated right in 3.9.0, has anyone reported something similar? It isnt a critical crash as it crashed like 3k times in a month, but it is still the most frequent right now. Thanks
![bitmapregiondecoder](https://user-images.githubusercontent.com/528931/35476194-421ba95a-03ac-11e8-8392-3150acdc12f9.png)

**Comment by davemorrissey** [comment]
The only published app I have using this lib is the sample app so I can't confirm any increase in crashes. This is another thing nobody else has reported, which I would have expected to be reported if it was a common problem. Maybe try using the SERIAL_EXECUTOR and call `setEagerLoadingEnabled(false)` to revert to old behaviour?

**Comment by tibbi** [comment]
Alright I will try setting both and see the result. Thanks

**Comment by tibbi** [comment]
Alright, seems like it helped. I added both suggestions and the crashes stopped, so not sure which solved it, but it is solved :) Thanks

**Comment by davemorrissey** [comment]
Interesting, and a bit worrying. I wonder if this would have somehow stopped your EXIF crashes too? I may need to check the conclusion I reached that BitmapRegionDecoder is thread safe in all recent versions of Android.

**Comment by tibbi** [comment]
I dont think they would. The exif crashes were clearly in the Subsampling code as Out of memories, I dont think it was anyhow related to threading.

**Comment by davemorrissey** [comment]
Normally I'd agree, but the exact same versions of Android were affected by both problems. Seeing as I have no explanation for either, who knows whether it's something related.
