### ISSUE TITLE
Problem With Draw Rect Below Nougat(7.0)

### ISSUE THREAD

**Issue by patelkeyur7279** [davemorrissey/subsampling-scale-image-view#390]
PointF startRect = sourceToViewCoord(data.getStartX(), data.getStartY());
PointF endRect = sourceToViewCoord(data.getEndX(), data.getEndY());

RectF rectF = new RectF(startRect.x, startRect.y, endRect.x, endRect.y);

float xPos = rectF.centerX();
float yPos = rectF.centerY();

matrix.reset();
matrix.setRotate(data.getRotation(), xPos, yPos);
canvas.setMatrix(matrix);

canvas.drawRect(rectF, paint);

### Expected behaviour
![whatsapp image 2018-02-03 at 6 59 55 pm](https://user-images.githubusercontent.com/36129317/35777526-5dd9003c-09d5-11e8-82ea-9de7730f68cb.jpeg)

I'm creating indoor navigation system and an above-attached image showing the actual want result.

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

Below Nougat(7.0) Android version has not worked properly I attached an image below.
(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)
![screenshot_1517747101](https://user-images.githubusercontent.com/36129317/35777545-a2d02e9a-09d5-11e8-8f08-c260bef72853.png)

**Comment by davemorrissey** [comment]
What have you done to try to solve this problem and what makes you sure it's a bug with this library and not your code?

**Comment by patelkeyur7279** [comment]
I trying to resolve it manually add some value to sourceToViewCoord(),  but it's not good for all devices and sourceToViewCoord() is return perfect values but image pointF not perfect and below 7.0 android version zoom in and zoom out all rect overlap.

**Comment by davemorrissey** [comment]
The sample app uses the same methods to add overlays and works on all supported versions of Android. Please try that and confirm it works on your test phones.

**Comment by patelkeyur7279** [comment]
I have tested 5.1.1, 6.0, 7.0, 8.0 version phones, and trying to solve this problem and I see canvas start draw from the top of the screen and under the toolbar, but we want to draw on image want to start point (0,0) from an image.

**Comment by davemorrissey** [comment]
Fix your layout so the view is not underneath the toolbar.

**Comment by patelkeyur7279** [comment]
=> Activity Layout

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="minder.testimageview.MainActivity">

    <minder.testimageview.SampleSubScalImageView
        android:id="@+id/ssvid"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</LinearLayout>

=> And this is Main Image Class

public class SampleSubScalImageView extends SubsamplingScaleImageView {

    private Matrix matrix = new Matrix();
    private List<NavigationMapLabels> mRect = null;

    public SampleSubScalImageView(Context context, AttributeSet attr) {
        super(context, attr);
    }

    public SampleSubScalImageView(Context context) {
        super(context);
    }

    @SuppressLint("DrawAllocation")
    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        if (mRect != null) {
            for (NavigationMapLabels data : mRect) {

                Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG | Paint.DITHER_FLAG | Paint.FILTER_BITMAP_FLAG);
                paint.setColor(Color.GREEN);
                paint.setAntiAlias(true);
                paint.setStyle(Paint.Style.STROKE);
                paint.setStrokeWidth(5);

                PointF startRect = sourceToViewCoord(data.getStartX(), data.getStartY());
                PointF endRect = sourceToViewCoord(data.getEndX(), data.getEndY());

                if (startRect != null && endRect != null) {
                    RectF rectF = new RectF(startRect.x, startRect.y, endRect.x, endRect.y);

                    float xPos = rectF.centerX();
                    float yPos = rectF.centerY();

                    matrix.reset();
                    matrix.setRotate(data.getRotation(), xPos, yPos);

                    canvas.setMatrix(matrix);
                    canvas.drawRect(rectF, paint);

                    TextPaint textPaint = new TextPaint(Paint.ANTI_ALIAS_FLAG | Paint.DITHER_FLAG | Paint.FILTER_BITMAP_FLAG);
                    textPaint.setAntiAlias(true);
                    textPaint.setColor(Color.parseColor(data.getColor()));
                    textPaint.setTextSize(40);
                    textPaint.setTextAlign(Paint.Align.CENTER);
                    textPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_OVER));
                    textPaint.setShadowLayer(1f, 0f, 1f, Color.WHITE);

                    String label = data.getLabel();

                    int width = (int) rectF.width();
                    Log.e("Text :", " --=> Width : " + width + " Text : " + label);
                    Layout.Alignment alignment = Layout.Alignment.ALIGN_NORMAL;
                    float spacingMultiplier = 1;
                    float spacingAddition = 0;
                    boolean includePadding = false;

                    // init StaticLayout for text
                    StaticLayout textLayout = new StaticLayout(label, textPaint, width, alignment, spacingMultiplier, spacingAddition, includePadding);

                    //Log.e("Text :", " -> H 1 -> " + textLayout.getHeight() + " -> " + rectF.height());
                    //Log.e("Text :", " -> H 1 -> " + textLayout.getText() + " -> " + rectF.height());
                    if (textLayout.getHeight() <= Math.abs(rectF.height())) {
                        //Log.e("Text :", " -> H 2 -> " + textLayout.getText());
                        float yPos1 = (yPos) - (textLayout.getHeight() / 2);

                        //canvas.drawRect(rectF, paint);
                        canvas.translate(xPos, yPos1);

                        textLayout.draw(canvas);
                    }
                }
            }
        }

    }

    public void setRectanglesWithText(List<EntityNavigationMapLabels> data){
        this.mRect = data;
        invalidate();
    }

}


Now, Please Tell me if any wrong in this code, because I'm not getting what's problem below 7.0.

**Comment by davemorrissey** [comment]
I don't know. But you're in a better position to debug your app than I am.
