### ISSUE TITLE
DoubleTap to zoom not working for zooming in

### ISSUE THREAD

**Issue by Sdghasemi** [davemorrissey/subsampling-scale-image-view#391]
Sometimes double tap to zoom not working on some particular images. However zooming out with double tap works fine, but it seems zooming in depends on how fast you touch the screen or not working for some images at all, regardless of how you try. And for some images double tapping works with multi small steps until it reaches the proper amount of zoom which had to get done by a single double-tap and then the next double-tap will zoom out the photo completely.
Here is a not-working-at-all sample tested on Samsung Galaxy S8:
[Problem Sample](https://i.imgur.com/L9IUcY8.gif)

I'd be glad if anyone could help me with the issue!

**Comment by davemorrissey** [comment]
Usually this is because the image isn't big enough to need zooming, and you're already at or very near the max scale.

**Comment by Sdghasemi** [comment]
Actually the images are big enough too zoom like 1080x1920 pixels and also I've set the max scale factor to `10f` which brings a huge amount of space to zoom. Also as I mentioned in some cases the zooming in process works with 5 or 6 double taps step by step until it reaches the `10f` zoom amount I've set, then the next double tap causes the full zoom out (with a single one); which totally proves the zoom in failure!

**Comment by sepehr1014** [comment]
We're also having the exact same problem. Any updates on this issue?

**Comment by davemorrissey** [comment]
Double tap zoom doesn't work in stages - it zooms in to the double tap zoom scale or out to the minimum scale, and is not interruptible. I cannot reproduce what you've described.

When you opened this issue you deleted the standard defect template. Please can you complete it with sample images, affected devices, your code, and detailed steps to reproduce.
