### ISSUE TITLE
NullPointerException While Building Animation

### ISSUE THREAD

**Issue by Vivek65** [davemorrissey/subsampling-scale-image-view#393]
Hello, I tired to set Animation on Pinview but it is throwing an null-pointer error. Image and Pin are working properly but on the same object it is throwing the error.

`import kotlinx.android.synthetic.main.activity_main.mapZoomView

class MainActivity : AppCompatActivity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)

    val pinView = mapZoomView
    pinView.setImage(ImageSource.resource(R.drawable.bassmap))
    pinView.setPin(PointF(1920f, 1920f))
    pinView.animateScaleAndCenter(2f,PointF(1920f,1920f))
        .withDuration(1000)
        .withEasing(SubsamplingScaleImageView.EASE_OUT_QUAD)
        .withInterruptible(false)
        .start()
  }
}`

Error

 **Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$AnimationBuilder com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$AnimationBuilder.withDuration(long)' on a null object reference**

**Comment by aa86799** [comment]
```
mScaleImageView.setOnImageEventListener(new SubsamplingScaleImageView.OnImageEventListener() {
            @Override
            public void onReady() {
                mScaleImageView.animateScaleAndCenter(2, new PointF(100,100))
                        .withDuration(2000)
                        .withEasing(SubsamplingScaleImageView.EASE_IN_OUT_QUAD)
                        .withInterruptible(false)
                        .start();
            }
     ....
});
```
