### ISSUE TITLE
Not zooming out after the animation is complete.

### ISSUE THREAD

**Issue by Vivek65** [davemorrissey/subsampling-scale-image-view#394]
The image is stuck at the same scale where the animation ends. After the animation completes not able to perform any gestures.

**MainActivity**

<pre>
override fun onMarkerDrwan(pointF: PointF) {
    mapZoomView.animateScaleAndCenter(1.5f, pointF)
        .withDuration(100)
        .withInterruptible(false)
        .start()
  }
</pre>

**PinView**

<pre>
public class PinView extends SubsamplingScaleImageView {

  private final Paint paint = new Paint();
  private final PointF vPin = new PointF();
  private PointF sPin;
  private PointF tempPin;
  private Bitmap pin;
  private AnimationView animationView;
  private ArrayList<PointF> multiplePins;
  private Handler handler;
  private int count = 0;
  private TimerTask timerTask;
  public PinView(Context context) {
    this(context, null);
    animationView = (AnimationView) context;
  }

  public PinView(Context context, AttributeSet attr) {
    super(context, attr);
    animationView = (AnimationView) context;
    initialise();
  }

  public void setPin(PointF sPin) {
    this.sPin = sPin;
    initialise();
    invalidate();
  }

  public void setMultiplePins(ArrayList<PointF> multiplePin) {
    multiplePins = new ArrayList<>();
    handler = new Handler();
    this.multiplePins = multiplePin;
    initialise();
    invalidate();
  }

  private void initialise() {
    float density = getResources().getDisplayMetrics().densityDpi;
    pin = BitmapFactory.decodeResource(this.getResources(), R.drawable.bass_marker_40x40);
    float w = (density / 420f) * pin.getWidth();
    float h = (density / 420f) * pin.getHeight();
    pin = Bitmap.createScaledBitmap(pin, (int) w, (int) h, true);
  }

  @Override
  protected void onDraw(Canvas canvas) {
    super.onDraw(canvas);

    // Don't draw pin before image is ready so it doesn't move around during setup.
    if (!isReady()) {
      return;
    }

    paint.setAntiAlias(true);

    if (multiplePins != null && pin != null) {

      for (int i = 0; i < multiplePins.size(); i++) {
        tempPin = multiplePins.get(i);

        sourceToViewCoord(tempPin, vPin);
        float vX = vPin.x - (pin.getWidth() / 2);
        float vY = vPin.y - pin.getHeight();
        canvas.drawBitmap(pin, vX, vY, paint);
      }

    }
    animationView.onMarkerDrwan(multiplePins.get(0));
  }
</pre>

**Comment by davemorrissey** [comment]
I think your code has an infinite loop.
