### ISSUE TITLE
Support for EditText or TextView

### ISSUE THREAD

**Issue by abhinav272** [davemorrissey/subsampling-scale-image-view#396]
Not a Bug..!!

Just a simple question, can it be used for textView or an editText as well ??

**Comment by davemorrissey** [comment]
Can you explain what you mean?

**Comment by abhinav272** [comment]
I am working on a camera app, where the user can enter text on preview and can drag over the preview, resize the text and place it anywhere while recording.
Then I will add it as a watermark to video.

**Comment by davemorrissey** [comment]
That doesn't sound related to what this view does. However you might be able to use classes from the sample as a starting point for drawing on a zoomable image.
