### ISSUE TITLE
Image visible only when touch or slide

### ISSUE THREAD

**Issue by tree1891** [davemorrissey/subsampling-scale-image-view#397]
When load remote png image 3780x2072 using PicassoDecoder, PicassoRegionDecoder with SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP, the image is visible only when touch or slide.
It does work on small image (716x822) or without SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP.
Is there any refresh method manually?

**Comment by davemorrissey** [comment]
Please don't delete the issue template when opening an issue, it provides useful information. I didn't write PicassoRegionDecoder and have never used it so I'm not able to help fix problems with it. I recommend trying the library without any extensions first.

**Comment by tree1891** [comment]
Is it possible to load url without picasso?

**Comment by davemorrissey** [comment]
Not directly but you could try a local image for testing, or just some code that downloads an image to a file.

**Comment by tree1891** [comment]
I have tried a local image, but it has same issue.
![luxembourg1](https://user-images.githubusercontent.com/1282201/36642625-36620360-1a7d-11e8-8c1e-b39e87e67495.png)

**Comment by davemorrissey** [comment]
Please complete the issue template.

**Comment by tree1891** [comment]
### Expected behaviour
show image

### Actual behaviour
image visible only when touch or slide

### Affected devices
LG G5, SDK 27, android 7


### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Your code?

**Comment by tree1891** [comment]
`            final SubsamplingScaleImageView scaleView = view.findViewById(R.id.image);
            scaleView.setOnImageEventListener(new SubsamplingScaleImageView.OnImageEventListener() {
                @Override
                public void onReady() {
                    scaleView.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_START);
                }

                @Override
                public void onImageLoaded() {
                    pb.setVisibility(View.GONE);
                }

                @Override
                public void onPreviewLoadError(Exception e) {

                }

                @Override
                public void onImageLoadError(Exception e) {

                }

                @Override
                public void onTileLoadError(Exception e) {

                }

                @Override
                public void onPreviewReleased() {

                }
            });

            scaleView.setImage(ImageSource.asset("Luxembourg1.png"));`

**Comment by davemorrissey** [comment]
Set the scale type before loading the image, not when it's ready.

**Comment by tree1891** [comment]
It does work.
Thank you very much
