### ISSUE TITLE
Can't it be used in recyclerView with PagerSnapHelper?

### ISSUE THREAD

**Issue by LongAgoLong** [davemorrissey/subsampling-scale-image-view#399]
Can't it be used in recyclerView with PagerSnapHelper?

**Comment by davemorrissey** [comment]
I don't know. Have you tried it?

**Comment by LongAgoLong** [comment]
I have tried.But it can't set click and long click.

**Comment by davemorrissey** [comment]
If you are reporting a problem, please use the issue template. You deleted it when opening this.

**Comment by LongAgoLong** [comment]
Okay,thanks.
