### ISSUE TITLE
Conflict between Move of the image and Swipe of ViewPager

### ISSUE THREAD

**Issue by dancefire** [davemorrissey/subsampling-scale-image-view#4]
I'm working on a gallery project, which can show photos one by one, pinch and zoom to see the details, and swipe to the previous or the next photo.

So, I put SubsamplingScaleImageView into a fragment, and using ViewPager to do the swipe thing. Both zoom and swipe works, however, when I zoom in the photo, and try to move horizontally, it will trigger the swipe event, so, the move failed and the UI go to the next photo. 

Move the photo vertically will not trigger the swipe event, and if I move vertically first, without release my finger, and then move horizontally, it will not trigger the swipe event, either. 

I think the more logical behavior should be that, when zoomed in, move horizontally will not trigger the swipe event, until it reach the boundary of the photo.

**Comment by CrazyCoderAndroid** [comment]
@dancefire Have you got the solution? I am also facing that issue. needs help

**Comment by android-bash** [comment]
@CrazyCoderAndroid Did you find solution?
