### ISSUE TITLE
Add OnFailed Listener

### ISSUE THREAD

**Issue by luisriq** [davemorrissey/subsampling-scale-image-view#40]
Hi, could you please add a listener to do something when this method:
``` java
BitmapInitTask.doInBackground()
```
catches an exception and sends the message: ```E/SubsamplingScaleImageView﹕ Failed to initialise bitmap decoder```

it would be really useful to load a default resource, hide the view, etc. in case the image cannot be displayed

**Comment by davemorrissey** [comment]
Hi Luis, I had a similar discussion a couple of weeks ago and decided not to do this, because it's very common for the decoder to return a corrupt image, which can't be detected. This seems to happen as often as exceptions. I didn't want to add a feature that only works half the time.

**Comment by luisriq** [comment]
I understand, though i still want the behavior described above, so probably i'll modify the library by myself to achieve it.

Thanks for your time!.

**Comment by davemorrissey** [comment]
Thanks, extending a local copy is the best option for now. I will keep this under consideration. The previous suggestion was to put it on the tile decoder, which was going to be particularly unreliable, and your suggestion of putting it on the init task make more sense, mainly to capture the cases when you supply a file that isn't an image (which could happen in things like a reddit browser).

**Comment by davemorrissey** [comment]
I've implemented an error and event listener interface now.

**Comment by davemorrissey** [comment]
Released in v3.0.0.
