### ISSUE TITLE
setToTop or setToBottom feature?

### ISSUE THREAD

**Issue by LomikXP** [davemorrissey/subsampling-scale-image-view#405]
Hello, thanks for great android component!
What about setToTop and setToBottom functions and animation?
And what getCenter returns? Why its not from up to down coordinates?

**Comment by davemorrissey** [comment]
Can you explain what setToTop and setToBottom would do?

The getCenter method is explained in the javadoc and the wiki for this project: it returns the source coordinates currently at the center of the screen. I'm not sure exactly what you mean by up to down coordinates, but the center works well regardless of image aspect ratio and makes handling orientation changes easy.

**Comment by LomikXP** [comment]
Ok, thanks for fast and good explain.
setToTop - set view to top part of image
setToBottom - set view to top bottom image

**Comment by davemorrissey** [comment]
How that works would be dependent on whether the image and view aspect ratios. Have a look at the wiki, there are methods to move the image anywhere you want it.
