### ISSUE TITLE
Showing image with wrong orientation

### ISSUE THREAD

**Issue by unlemci** [davemorrissey/subsampling-scale-image-view#407]
### Expected behaviour
Correct image with correct rotation

### Actual behaviour
Showing image with wrong orientation

### Solution

Add this util https://gist.github.com/9re/1990019
After when you are showing bitmap, use this code `ExifUtil.Companion.rotateBitmap(imagePath, bitmap);` for showing right orientation

### Affected devices
All of it
### Affected images
some rotated images from camera

**Comment by davemorrissey** [comment]
Can you attach examples of affected images and show the code you're using to configure your view please?

**Comment by unlemci** [comment]
I'm using latest BigImageView and it doesn't use bitmap factory it uses this library...

So i'm just giving path of image and it doesn't show correct with correct orientation.

**Comment by davemorrissey** [comment]
Have you read the wiki?

https://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images#orientation

**Comment by unlemci** [comment]
Sorry i didn't use this project i'm going to notify to BigImageView author.

**Comment by davemorrissey** [comment]
You should be able to fix this by calling `getSSIV()` to get the SSIV instance, then following the instructions in the wiki to enable EXIF orientation. However you haven't provided your code or images so I can't say for sure. Closing this now.

**Comment by prashantsaini1** [comment]
@crzyBrown @davemorrissey I found a quick and easy fix for this issue. Use below code snippet for loading all images using BigImageView.
```
BigImageView imageView = (BigImageView) view.findViewById(R.id.image_view);

imageView.showImage(current_image_path);

// use this line to force SSIV lib to auto-rotate the image as per EXIF data.
// It's exactly what's written in SSIV docs here: https://github.com/davemorrissey/subsampling-scale-image-view/wiki/07.-Configuration
imageView.getSSIV().setOrientation(ORIENTATION_USE_EXIF);
```

**Comment by pranavj7Z** [comment]
@davemorrissey I am facing the same problem. Couldn't solve with any of the above methods.
I am trying to load the image from a folder created in the external storage.
some images are rotated 360 while some 90.
Here is the code.
imageView.orientation = SubsamplingScaleImageView.ORIENTATION_USE_EXIF
imageView.setImage(ImageSource.uri(FileProvider.getUriForFile (this.context!!, "com.app.appname.FileProvider", File(path))))
