### ISSUE TITLE
Problems with pins

### ISSUE THREAD

**Issue by ghost** [davemorrissey/subsampling-scale-image-view#408]
I updated android studio (now I have 3.1 version) and something wrong with pins. I did everything just like here: https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/sample/src/main/java/com/davemorrissey/labs/subscaleview/test/extension/views/PinView.java

Before the update everything worked. But now on hdpi and mdpi for example completely different results. My pins began to go away and the coordinates began to be calculated in a strange way. I have a suspicion that the error in the function sourceToViewCoord.

**Comment by davemorrissey** [comment]
Hi James, you've deleted the issue template so there's not enough information here. Please can you provide your source code, affected Android versions and devices, a more detailed description of the problem, screenshots etc.

**Comment by james4591** [comment]
Ok, sorry.
1) My PinView is absolutely the same as the link above.
2) MainActivity.java

public class MainActivity extends AppCompatActivity {
    private PinView imageView;

    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        this.imageView = findViewById(R.id.pin_view);
        this.imageView.setImage(ImageSource.resource(R.drawable.cat));
        this.imageView.setPin(new PointF(264f, 66f));
    }
}

3) activity_main.xml

<?xml version="1.0" encoding="utf-8"?>

    <com.app.test.test.PinView
        android:id="@+id/pin_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        xmlns:android="http://schemas.android.com/apk/res/android" />
4) Results
![1](https://user-images.githubusercontent.com/38045860/38294103-3cb8919a-3803-11e8-8517-c637d3513c89.PNG)
![2](https://user-images.githubusercontent.com/38045860/38294111-42725f1c-3803-11e8-829e-4d32e9345de6.PNG)

**Comment by davemorrissey** [comment]
I suspect this is because you've put the image in a density specific resources directory, and not in assets as recommended. Android may be scaling the image and causing unpredictable results.

**Comment by james4591** [comment]
Yes, thanks it helped. Strange but before everything worked with ImageSource.resource
