### ISSUE TITLE
Question: can this be used for cropping images?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [davemorrissey/subsampling-scale-image-view#409]
If so, what is needed to be done?

**Comment by davemorrissey** [comment]
Whether this library is suitable as the basis for an image cropping tool is dependant on how you want it to work. I'd imagine it will help in some cases, but you will need to decide for yourself. I can fix bugs but can't help developers build their apps, sorry!

**Comment by AndroidDeveloperLB** [comment]
I was just wondering if I can use it somehow.
Maybe take the current content of what's shown..
Anyway, thank you .
