### ISSUE TITLE
Stop allocating objects in draw

### ISSUE THREAD

**Issue by ansman** [davemorrissey/subsampling-scale-image-view#41]
Currently there are a lot of objects that are created in each call to `draw`.

For example the `for ( .. : ..)` creates an iterator and there are plenty of `Rect`'s that are created, it would be great if some/all could be created once instead.

**Comment by davemorrissey** [comment]
I'll try this but I suspect making a significant dent in the number of Points and Rects created will take a lot of work. Are you seeing performance issues caused by this?

**Comment by ansman** [comment]
I've only tested on lollipop but this will surely cause problems on low end devices. The GC absolutely kills performance.

I'll see if I can create a pull request that uses temporary, pre allocated, points and rects instead of creating new ones.

**Comment by davemorrissey** [comment]
Thanks for the looking at this, I'm interested to see what you come up with but there's a chance I won't accept the PR. It may quite significantly affect the design of the class and as I'm pretty much the only contributor I need to make sure I understand everything about how it works! No-one has reported a performance issue yet, my own phone is three years old and has no problems, but I do agree the object creation is wasteful.

**Comment by ansman** [comment]
Fair enough, though I hadn't planned on changing it in a major way.

**Comment by davemorrissey** [comment]
I'm not sure whether a large number of small objects or a small number of large objects are GC'd more efficiently but it's worth remembering that this view constantly loads and discards tile bitmaps, especially on low end devices, so it does trigger regular GC, and the extra object allocation may not be particularly significant in comparison. I've no way of knowing until I try it.

**Comment by ansman** [comment]
I don't mean more objects take longer time to GC but rather allocating objects will cause more frequent GCs.

Bitmaps are a bit special since they don't take up much java heap space but mostly native memory which doesn't affect JVM memory pressure.

**Comment by davemorrissey** [comment]
That used to be the case but according to the docs, bitmap pixel data has been stored in the heap since API 11. For an image large enough to require tiling, GC triggered by bitmap recycling will vastly outweigh that caused by other objects, but for smaller images where only one bitmap is loaded the other objects become a bit more significant. However, Android's concurrent GC may make the pauses unnoticeable.

I will take a look at this when I can, but it's not critical because no-one has reported any issues with pauses, and I'm not sure it will make any visible difference to the majority of users.

**Comment by davemorrissey** [comment]
Done. I won't release this for a while, it needs more testing.

**Comment by ansman** [comment]
Awesome! I'll try it in my project and see how it works.

**Comment by davemorrissey** [comment]
Released in v3.0.0.
