### ISSUE TITLE
request : move  "minSdkVersion" and "targetSdkVersion" into gradle files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [davemorrissey/subsampling-scale-image-view#410]
It shouldn't be in manifest files...

**Comment by davemorrissey** [comment]
Does this cause a problem when you include the compiled aar file as a dependency in your app?

**Comment by AndroidDeveloperLB** [comment]
@davemorrissey Haven't tried yet. I got this error/warning when cloning and importing the project :

![image](https://user-images.githubusercontent.com/5357526/38465540-b9af95f2-3b25-11e8-869e-0a0a06984d61.png)

Putting those attributes in the manifest is a very old development behavior. Gradle file is the way to go these days.

**Comment by davemorrissey** [comment]
Odd, Android Studio has never even given a lint warning about this and compiles for me. I knew the standard had changed and use it for other projects but I'm not actively developing this one. You can submit a PR if you want.

**Comment by AndroidDeveloperLB** [comment]
ok here:
https://github.com/davemorrissey/subsampling-scale-image-view/pull/414

**Comment by AndroidDeveloperLB** [comment]
Why closed?
