### ISSUE TITLE
Question: How to get current rectangle of what's shown on the screen?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [davemorrissey/subsampling-scale-image-view#413]
Suppose I chose to view a large image, and I zoom and pan, etc...
And at some point, I wish to know which part of the image is actually shown. Meaning the rectangle that's visible to me.

Is it possible?

**Comment by davemorrissey** [comment]
This repository has a detailed wiki, complete javadoc for every public method, and answers to questions including this one in closed issues. The contributing guide links to these. Please check them before opening new issues, thanks!

**Comment by AndroidDeveloperLB** [comment]
I've looked at it, but I'm not sure. Is it this one:

http://davemorrissey.github.io/subsampling-scale-image-view/javadoc/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.html#visibleFileRect-android.graphics.Rect-

?
The wiki doesn't seem to mention this.
I also can't find how to set the rectangle, if I want to.

**Comment by AndroidDeveloperLB** [comment]
Speaking of the wiki, I was curious about custom decoders, but both of the first links here (of " RapidImageDecoder and RapidImageRegionDecoder" ) are dead:
https://github.com/davemorrissey/subsampling-scale-image-view/wiki/04.-Custom-decoders

**Comment by davemorrissey** [comment]
The doc says "Find the area of the source file that is currently visible on screen". You can't directly set the rect, you can set the center and scale with some maths of your own. I don't recommend rapid decoder any more but the interface is very simple and thoroughly documented.

Please bear in mind I don't earn anything from this library and it's really helpful if you do a little research and experimentation before opening issues to ask questions - I can't support 4,000 developers this way. Alternatively you could try asking questions on StackOverflow where the community can help. Thanks!

**Comment by davemorrissey** [comment]
A setter for visibleFileRect cannot work for everyone because the aspect ratios would not match and the bounds might break other restrictions. All the methods you need are there and well documented, and I cannot write the code for your app because you need to work out how you want to handle edge cases. Please ask any further questions on StackOverflow.

**Comment by AndroidDeveloperLB** [comment]
This makes sense, but still, it is possible to overcome this, by using one of the dimensions as the one to force visibility on.
Anyway, thank you for the help.
