### ISSUE TITLE
Cannot avoid bitmap recycling

### ISSUE THREAD

**Issue by ArLabDev** [davemorrissey/subsampling-scale-image-view#415]
A bitmap displayed using the method
   setImage( ImageSource.bitmap(bitmap) );

will be always recycled at the end of the usage (when a new image will be displayed or when method "recyle" is called).

This break the possibility to show Bitmap loaded with Glide. It does not allow call of recycle on Bitmaps that it loads.

It would be useful a way to tell to the ImageView that it has no the ownership of the bitmap passed and no responsibility to call Bitmap.recycle method.

I think that it should be the default behavior for ImageSource.bitmap.
To do not break compatibility a second parameter could be provided to ImageSource.bitmap to select when to take recycle responsibility.

**Comment by davemorrissey** [comment]
It's always worth checking closed issues before opening a new one - you can used cachedBitmap in this situation.

**Comment by ArLabDev** [comment]
Right, sorry.
