### ISSUE TITLE
Crashes app

### ISSUE THREAD

**Issue by Alexander178** [davemorrissey/subsampling-scale-image-view#416]
Hello, how do I properly load a preview of a smaller image? I have an application crashing if I add a second parameter to the method ( ImageSource.bitmap(preview) ).

SubsamplingScaleImageView SubScaleImgView = (SubsamplingScaleImageView ) this.findViewById(R.id.SubScaleImgView);

        String Img_Path = getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS) + "/1.jpg";

        Bitmap preview;
        BitmapFactory.Options option = new BitmapFactory.Options();
        option.inJustDecodeBounds = true;
        BitmapFactory.decodeFile(Img_Path, option);
        float max = Math.max(((float) option.outWidth) / 1024.0f, ((float) option.outHeight) / 1024.0f);
        if (max > 1.0f) {
            option.inSampleSize = (int) max;
        }
        option.inJustDecodeBounds = false;
        preview = BitmapFactory.decodeFile(Img_Path, option);

        SubScaleImgView.setImage(ImageSource.uri(Img_Path), ImageSource.bitmap(preview));

**Comment by Alexander178** [comment]
The problem is that it is not possible to make a slider without brakes in the ViewPager, when loading large images from a disk. Also, when moving left and right, the black screen first goes, for the time being the image is loaded. It would be desirable instead of the black screen to load the reduced copy of the big image while it is loaded. How can this be done, are there any good code examples?


String[] ListPathNameImg16; //List Image
    
    //Load
    private void open_full_Viewer_image() {
        ViewPagerFixed ViewPagerFixed = (ViewPagerFixed) mapsActivity.findViewById(R.id.ViewPagerFixed);
        ImageAdapter adapter = new ImageAdapter(mapsActivity);
        ViewPagerFixed.setAdapter(adapter);
        ViewPagerFixed.setCurrentItem(0);
        ViewPagerFixed.setOffscreenPageLimit(2); //?
    }
    

    public class ImageAdapter extends PagerAdapter {
        Context context;

        LayoutInflater mLayoutInflater;

        ImageAdapter(Context context){
            this.context=context;
            mLayoutInflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        }
        @Override
        public int getCount() {
            return ListPathNameImg16.length;
        }

        @Override
        public boolean isViewFromObject(View view, Object object) {
            return view == ((LinearLayout) object);
        }

        @Override
        public Object instantiateItem(ViewGroup container, final int position) {
            View itemView = mLayoutInflater.inflate(R.layout.z_maket_pager_item_for_img16, container, false);

            SubsamplingScaleImageView SubScaleImgView_for_Img16 = (SubsamplingScaleImageView) itemView.findViewById(R.id.SubScaleImgView_for_Img16);
            SubScaleImgView_for_Img16.setMaxScale(2.5f);
            SubScaleImgView_for_Img16.setDoubleTapZoomScale ( 0.95f );
            SubScaleImgView_for_Img16.setDrawingCacheEnabled(true);
            SubScaleImgView_for_Img16.setImage(ImageSource.uri( ListPathNameImg16[position] ));
            
            container.addView(itemView);

            return itemView;
        }

        @Override
        public void destroyItem(ViewGroup container, int position, Object object) {
            container.removeView((LinearLayout)object);
        }
    }

**Comment by davemorrissey** [comment]
Your attempt to load a reduced copy is duplicating the same work the view does, so will double any loading delay. You've set the off screen limit already and I don't know of any other fix.
