### ISSUE TITLE
The Zoom Function Is Not Working With Glide

### ISSUE THREAD

**Issue by AreejAlZahrani** [davemorrissey/subsampling-scale-image-view#418]
I want to set the image source of the subsampling-scale-image-view using Glide and I was able to load the image I can't zoom in or out.

what I did: 
1. get the image from firebase Storage using glide as a bitmap and set it to the subsampling-scale-image-view 
Glide.with(context)
                .using(new FirebaseImageLoader())
                .load(mStorageReference)
                .asBitmap()
                .into(new SimpleTarget<Bitmap>() {
            @Override public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                expandedImageView.setImage(ImageSource.bitmap(resource)); } });

** When I used image that is stored in the app resources it works fine using this line:
                expandedImageView.setImage(ImageSource.resource(R.id.image_name));

**Comment by davemorrissey** [comment]
You haven't provided images, screenshots or detailed anything you've tried to resolve this problem so I can't say much. I suspect the image isn't big enough to zoom or Glide is scaling it down, but I can't provide support for Glide.

Please read this: https://github.com/davemorrissey/subsampling-scale-image-view/wiki/X.-Picasso,-Glide,-Fresco
