### ISSUE TITLE
I want to customise onTouchEvent of View. 

### ISSUE THREAD

**Issue by Kunnu123** [davemorrissey/subsampling-scale-image-view#419]
I want to customise onTouchEvent of View. So I override Ontouch event in my Custom View. But when I override the other functionality is not working like double tap zoom, single finger move etc.

**Comment by davemorrissey** [comment]
Please don't delete the issue template. I can't help fix the bugs in your own code, especially when you haven't included it in the question, and I recommend learning more about Android's event handling and when you should pass events up to the SubsamplingScaleImageView class for handling.
