### ISSUE TITLE
Provide an easier way of drawing on top of the image

### ISSUE THREAD

**Issue by ansman** [davemorrissey/subsampling-scale-image-view#42]
I need to be able to draw markers on a very large image, the markers should move and scale as the image moves and scales.

As of now I haven't found any way of doing this since most of the members are private.

Ideally it would be nice to be able to call a function with the coordinates in the full sized image and get the on screen coordinates.

Something like this:
```java
private final Point tempPoint = new Point();
private final Paint markerPaint = new Paint();
private float markerRadius;
private List<Marker> markers;

@Override
public void onDraw(Canvas canvas) {
    super.onDraw(canvas);
    for (Marker : markers) {
        drawMarker(marker, canvas);
}

private void drawMarker(Marker marker, Canvas canvas) {
    transformImageCoordinatesToScreenCoordinates(marker.coordinates, tempPoint);
    canvas.drawCircle(tempPoint.x, tempPoint.y, markerRadius, markerPaint);
}
```

**Comment by davemorrissey** [comment]
Hi Nicklas, you need to extend the class and use the `sourceToViewCoord` method. You can see a complete working example in the demo app, using this class: https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/sample/src/com/davemorrissey/labs/subscaleview/sample/extension/views/PinView.java

**Comment by ansman** [comment]
Ah, my bad. Don't know why but I thought that method was private.
