### ISSUE TITLE
When I set SubsamplingScaleImageView View.GONE or View.INVISIBLE， it will load failure and all callbacks in ImageEventListener could not be executed forever.  

### ISSUE THREAD

**Issue by meikaiss** [davemorrissey/subsampling-scale-image-view#420]
When I set SubsamplingScaleImageView View.GONE or View.INVISIBLE， it will load failure,  and all callbacks in ImageEventListener could not be executed forever.  

I want set SubsamplingScaleImageView not visible when I start loading,  and set SubsamplingScaleImageView visible when I load completed. and set SubsamplingScaleImageView not visible when load failure by some reason like uri file not exists.

My current solution is set SubsamplingScaleImageView always VISIBLE,  and keep loading View、error View covered with my SubsamplingScaleImageView.

So, is there any other way to meet the requirements of the product?

**Comment by davemorrissey** [comment]
The view can't load until it has dimensions. It doesn't have dimensions until it's visible. However it doesn't display anything until it has loaded an image so that doesn't usually matter. The solution you already have is the best one.
