### ISSUE TITLE
Library Import Problem

### ISSUE THREAD

**Issue by powerhi** [davemorrissey/subsampling-scale-image-view#421]
I'm having trouble using the library. I downloaded the aar release and imported it into my project and edited my gradle settings so that it works, and within my layout file its fine. Everything builds fine. However in my code I can't instantiate a SubsamplingScaleImageView object (It doesn't recognize it) and I'm not sure why. I'm new to Android so this might be absurdly easy, but educate me nonetheless

**Comment by davemorrissey** [comment]
This is really a generic Android question that would be better on StackOverflow. You haven't mentioned your IDE, any error messages, how you set up your project, your gradle code, or what you tried to fix the problem, so there's not enough information here to help you.
