### ISSUE TITLE
onDraw does not work unless my image view is wrap_content, but cannot be scaled, and causes error logs

### ISSUE THREAD

**Issue by evbarnett** [davemorrissey/subsampling-scale-image-view#423]
Hello,

I am trying to draw atop the SubsamplingScaleImageView, so I overrode onDraw().

When my SubsamplingScaleImageView is match_parent, everything works as expected, *except* the actions taken in onDraw are *not* shown (I can confirm that onDraw is being called correctly).

When my SubsamplingScaleImageView is wrap_content, onDraw works as expected and is shown. However, the image starts at full zoom and the zoom cannot be scaled at all. Attempting to scale shows the following error logs:

``
05-22 18:03:40.920 14603-14635/com.my.app E/libacryl: Invalid source image size 12873x8610 (limit: 1x1 ~ 8192x8192 )  
05-22 18:03:40.920 14603-14635/com.my.app E/libacryl: Too large source area: (0, 0) -> (12864, 8608)  
05-22 18:03:40.920 14603-14635/com.my.app E/libacryl:         Image full size: 1x1  
05-22 18:03:40.920 14603-14635/com.my.app E/libacryl: Invalid target image size 12880x8624 (limit: 1x1 ~ 8192x8192 )  
05-22 18:03:40.920 14603-14635/com.my.app E/libacryl: Incomplete settting (flags: 0x33) on the target layer
``

Trying to reset the scale / set scale manually, etc. doesn't work.

Thank you for your help!

**Comment by davemorrissey** [comment]
Please include your code.

**Comment by evbarnett** [comment]
I figured it out when using match_parent- I was using sourceToViewCoord / viewToSourceCoord incorrectly.
