### ISSUE TITLE
Awesome library, but doesn't support InputStream as ImageSource

### ISSUE THREAD

**Issue by lucca2011** [davemorrissey/subsampling-scale-image-view#425]
Please add InputStream support, thanks.

**Comment by KnIfER** [comment]
should first ask will a single InputStream suffice?  I am not sure, but I heard media playback like mp4 will request InputStream serveral times when you navigate

**Comment by lucca2011** [comment]
Q: mp4 will request InputStream serveral times when you navigate
A: Yes, but it works for a seekable InputStream.

**Comment by davemorrissey** [comment]
Sorry, there is no plan to support InputStream because it could be partially read, blocking, already closed, or closed while the view is visible. This creates a lot of error conditions the view would have to handle and would result in a lot of unreproducible bugs.
