### ISSUE TITLE
 android_os_Process_getProcessNameByPid pid is 17508     android_os_Process_getProcessNameByPid value is ovo.myanimation

### ISSUE THREAD

**Issue by 378063465** [davemorrissey/subsampling-scale-image-view#428]
E/Process: android_os_Process_getProcessNameByPid pid is 17508
    android_os_Process_getProcessNameByPid value is ovo.myanimation

E/GED: Failed to get GED Log Buf, err(0)

**Comment by 378063465** [comment]
setImage(ImageSource.bitmap(BitmapFactory.decodeResource(getResources(),R.mipmap.long_img)));

**Comment by davemorrissey** [comment]
I don't know what this means. Please complete the issue template, I can't help you if you delete it and provide none of the requested information.
