### ISSUE TITLE
Problem with pan limit it's possible lock the image for scroll only on y-axis?

### ISSUE THREAD

**Issue by Trusted97** [davemorrissey/subsampling-scale-image-view#430]
### Expected behaviour
Image need to scroll only in y-axis inside a viewpager

### Actual behaviour
Image scroll in the entire screen and viewpager doesn't work

### Steps to reproduce
[Custom adapter](https://pastebin.com/mcN6yabp) 
[Element of adapter ](https://pastebin.com/7tqFUhc3)
[Activity Code](https://pastebin.com/gL8C5Q6g)

### Affected devices

Samsung Galaxy S7 (SM-G930F) Api Level 24 Android version 7.0

### Affected images
All image are of different size and it all .png
![index](https://user-images.githubusercontent.com/37697178/42828211-82c2b5b2-89e8-11e8-82f8-f01d35250fc5.png)

**Comment by davemorrissey** [comment]
I think this is because you're using PAN_LIMIT_CENTER, try without it.
