### ISSUE TITLE
Is it possible to translate image from one edge and show blank area

### ISSUE THREAD

**Issue by zahid-arbisoft** [davemorrissey/subsampling-scale-image-view#434]
Is it possible to translate image to left/right or top/bottom by some value and show blank (buffer) area at the edges?

**Comment by davemorrissey** [comment]
You might want to have a look at the fork dhabensky created for PR #424. I'm not developing this library now so I don't know if I'll merge it. Otherwise you can use PAN_LIMIT_CENTER or PAN_LIMIT_OUTSIDE to allow the image to move beyond the default limits.

**Comment by zahid-arbisoft** [comment]
@davemorrissey Thanks, you comment helped. By saying "not developing this library now ", you mean this library is deprecated, and we will no longer get updated in future.

**Comment by davemorrissey** [comment]
It's not deprecated, but I feel it has all the features 99% of developers need and doesn't require much maintenance. I generally suggest that developers who need features that most won't need create their own forks, to avoid over-complicating the master.
If a version of Android is released that breaks the library, I'll try to fix it, but I haven't been an active Android developer for years so I may not notice!

**Comment by zahid-arbisoft** [comment]
Ok. Thanks
