### ISSUE TITLE
support version conflict

### ISSUE THREAD

**Issue by rocketRobin** [davemorrissey/subsampling-scale-image-view#438]
```
dependencies {
    javadocs 'com.android.support:support-annotations:27.1.0'
    javadocs 'com.android.support:exifinterface:27.1.0'
    implementation 'com.android.support:support-annotations:27.1.0'
    implementation 'com.android.support:exifinterface:27.1.0'
}

```

I use support 27.1.1 , so there need an update

**Comment by rocketRobin** [comment]
Hi，is there any news, this problem is block my development. Is this library still updated?

**Comment by perrochon** [comment]
Doesn't this force everything else in the project to use 27.1.1.
Right now I am using

**Comment by perrochon** [comment]
Doesn't the above force the whole project to use 27.1.1? I would like to use the later 28.0.0 and am using the below.

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            details.useVersion '28.0.0'
        }
    }
}

It builds and runs, but I worry about subtle (or eventually less subtle) issues introduced by the mismatch of libraries. Would I have to compile SSIV myself?
