### ISSUE TITLE
Heatmap Generation

### ISSUE THREAD

**Issue by android-bash** [davemorrissey/subsampling-scale-image-view#441]
Thank You. Nice library. Can you please take a look at this and help me how we can add heatmap like adding markers to some coordinates. Like [this](https://www.espatial.com/wp-content/uploads/Hot-Spot-Heat-Map-2.jpg) . If i can add it any way please let me know.

**Comment by davemorrissey** [comment]
That's something you'll need to solve for yourself, or with help from the wider community, but the sample library and wiki should get you started.
