### ISSUE TITLE
support gif

### ISSUE THREAD

**Issue by LastSoul** [davemorrissey/subsampling-scale-image-view#442]
please support gif file 

http://prntscr.com/kuff34

the gif file

https://imgur.com/a/KIcQnge

**Comment by aolphn** [comment]
+1

**Comment by rocketRobin** [comment]
+1

**Comment by reallychenchi** [comment]
+1

**Comment by JiweiMaster** [comment]
plan to support gif???

**Comment by davemorrissey** [comment]
Sorry, GIF support is not a priority because this library was intended for viewing large photos and building plans, not small GIFs. https://github.com/Piasy/BigImageViewer may do what you need.
