### ISSUE TITLE
Freehand View ： line disapper

### ISSUE THREAD

**Issue by liuhu6hu** [davemorrissey/subsampling-scale-image-view#444]
1：Draw a long line on the picture. 
2：Magnify the picture ，The line will disappear

**Comment by davemorrissey** [comment]
This is a known limitation as mentioned in the sample app. The sample is not part of the library and is not supported.

**Comment by shubham-311098** [comment]
how can we remove long line from the picture because i am facing issue while using library. it is drawing a long line over image
