### ISSUE TITLE
image exif orientation problems

### ISSUE THREAD

**Issue by taoszu** [davemorrissey/subsampling-scale-image-view#445]
I read the code,find some problem with the  get exif orientation method.
![5ba1495bc44bcbda7c65f52f672a5c9f](https://user-images.githubusercontent.com/15262319/46925818-9d579280-d060-11e8-8ccc-30f30c10cb2e.jpg)

This method lack the case with the image from resources.

**Comment by taoszu** [comment]
And I find  that  this method is not rigorous because the orientation has 8 case.  This is the [link](https://magnushoff.com/jpeg-orientation.html)

**Comment by davemorrissey** [comment]
EXIF information cannot be read from resources, that's a documented limitation, but if you put an image in your app's resources you'll know what orientation it is.

The flip orientations are very rarely used so I do not support them, because it would make the code too complicated.

**Comment by taoszu** [comment]
val exifInterface = ExifInterface(resources.openRawResource(id)) 
you can use this to get the resource orientation
