### ISSUE TITLE
FreehandView sample not working with orientation changes

### ISSUE THREAD

**Issue by VGJohn** [davemorrissey/subsampling-scale-image-view#446]
Hi Dave,

I'm using the FreehandView extension sample but it doesn't support orientation changes well. The drawing gets offset from where it was originally drawn when the orientation is changed using the setOrientation() method. 

What I want to be able to do is click a button to rotate the image and drawing clockwise and anticlockwise. Doing this through the setOrientation() method shows the drawing in the incorrect position even though the image underneath rotates fine. Is there something extra that needs to be added to FreehandView so this type of functionality is possible?

Thanks,
John

**Comment by davemorrissey** [comment]
The FreehandView is a very basic demo and wasn't intended to handle orientation changes. Points stored are relative to the top left of the image *after* rotation, not before. You can modify the code to translate them according to the current orientation.
