### ISSUE TITLE
decoder.decodeRegion(sRect, options)  cause crash.

### ISSUE THREAD

**Issue by wuzhongyuan** [davemorrissey/subsampling-scale-image-view#448]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Expected behaviour
don't crash.

### Actual behaviour
crash.

### Steps to reproduce
by accident.

(Include your setup code, and where relevant, your layout XML)

### Affected devices
荣耀 DUA AL00，1440×720.
小米 REDMI 6，1440x720.
(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

crash details:
#7373 SIGSEGV(SEGV_MAPERR)
com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:125)

chash point: Bitmap bitmap = decoder.decodeRegion(sRect, options);

**Comment by wuzhongyuan** [comment]
Android SDK version : Android 8.1.0,level 27

**Comment by kindyrain** [comment]
I have the same issue on same type phone

**Comment by huangjiaqiang** [comment]
ImageRegionDecoder  change to SkiaPooledImageRegionDecoder  can fix the problem.
```
private DecoderFactory<? extends ImageRegionDecoder> regionDecoderFactory = new CompatDecoderFactory<ImageRegionDecoder>(SkiaPooledImageRegionDecoder.class);
```

**Comment by davemorrissey** [comment]
Code, layout and images not provided so I'm unable to reproduce.
