### ISSUE TITLE
Can't load image with Picasso with correct EXIF orientation

### ISSUE THREAD

**Issue by CarsonRedeye** [davemorrissey/subsampling-scale-image-view#449]
### Expected behaviour
Image downloaded from a remote url with EXIF orientation set to -90 degrees shows with rotation applied

### Actual behaviour
No rotation applied

I know this behaviour is expected as described in the [docs](http://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images#orientation), but how can I apply the exif rotation?

**Comment by davemorrissey** [comment]
It's not clear how you're downloading the image and configuring the view so unfortunately I can't help.
