### ISSUE TITLE
Error method 'displayImage' when use with Universal Image Loader

### ISSUE THREAD

**Issue by cyclonmaster** [davemorrissey/subsampling-scale-image-view#45]
Get this error:
cannot resolve method 'displayImage .....')

This line got error when use with Universal Image Loader

imageLoader.displayImage(
				((Product) products.get(position)).getImageUrl(), mImageView,
				options, imageListener);

**Comment by davemorrissey** [comment]
The two view classes in my library do not extend ImageView so they will not work directly with universal image loader. To display an image from the web you should first save it to local storage.
