### ISSUE TITLE
How to get cropped image as bitmap after selecting freehandview?

### ISSUE THREAD

**Issue by krtanwar** [davemorrissey/subsampling-scale-image-view#450]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by KnIfER** [comment]
you can tell your phone to take a screenshot

**Comment by davemorrissey** [comment]
Duplicate of #19.
