### ISSUE TITLE
how to get bitmap you have drawn on from freehandview

### ISSUE THREAD

**Issue by dieter115** [davemorrissey/subsampling-scale-image-view#451]
Hey i'm using your library to make a tool to draw on pdf's. I'm already using a custom decoder and region decoder for this. But i don't understand how i can get the bitmap of the pdf page i have signed upon. Because i need to convert it back to a pdf with the drawing on.

**Comment by davemorrissey** [comment]
Sorry there is no export function, you have to write the code to load the bitmap and add the same overlays that are on screen. If an image is big enough to need tiling, you won't be able to do this because it'll be too big to load into memory.
