### ISSUE TITLE
Saving bitmap with layers

### ISSUE THREAD

**Issue by Benyuss** [davemorrissey/subsampling-scale-image-view#452]
Hi @davemorrissey,

I have seen #19 and other issues related to the topic, but I still can't figure out something.
I want to save a map (with the PinMapView), which has a marker on it.
You mentioned in these issues, that I need a [https://developer.android.com/reference/android/graphics/BitmapRegionDecoder](BitmapRegionDecoder).

It's fine, but where do I get an input stream to instantiate that decoder?
It should be the bitmap, which is private in your library.
Or am I completely wrong?
Can you give me a hint please?

Thanks!

**Comment by Benyuss** [comment]
Solved, nvm.

**Comment by deepakkaku** [comment]
@Benyuss Do you mind sharing your solution for this? Even I am trying to extract Bitmap with layers, but unable to do so. Can you share the code you tried to extract the bitmap?
