### ISSUE TITLE
lock viewpager swipe when image is zoomed

### ISSUE THREAD

**Issue by CrazyCoderAndroid** [davemorrissey/subsampling-scale-image-view#454]
I have a view pager that shows images. I want to lock the viewpager swipe when image is zoomed so that when image is zoomed user can not swipe to next image, user have to zoom out and then can swipe to the next image. How to achieve that ?

**Comment by KnIfER** [comment]
achieve by coding man

**Comment by davemorrissey** [comment]
I think you'll need to create your own fork of the library to do this. That's not something I'm able to assist with, but look for references to page swipe and experiment with changing that code.
