### ISSUE TITLE
PinView setPin, how add onclick function ?

### ISSUE THREAD

**Issue by hongtou820** [davemorrissey/subsampling-scale-image-view#457]
@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        // Don't draw pin before image is ready so it doesn't move around during setup.
        if (!isReady()) {
            return;
        }

        paint.setAntiAlias(true);

        if (sPin != null && pin != null&& pointFS != null) {
            for(PointF pointF:pointFS){
                sourceToViewCoord(pointF, vPin);
                float vX = vPin.x - (pin.getWidth()/2);
                float vY = vPin.y - pin.getHeight();
                canvas.drawBitmap(pin, vX, vY, paint);
            }
        }

    }

**Comment by hongtou820** [comment]
after add onDraw, how to add onclickLisener ?

**Comment by fukemy** [comment]
Hi. I did it but use the other way, just get image click and compare click location with pin location. Assume getLengthFromTwoPoint(pinLocation, clickLocation) < 200 -> click to pin

**Comment by davemorrissey** [comment]
You need your own click listener. https://github.com/davemorrissey/subsampling-scale-image-view/wiki/09.-Events
