### ISSUE TITLE
Using Support Library 28.0.0

### ISSUE THREAD

**Issue by perrochon** [davemorrissey/subsampling-scale-image-view#458]
SSIV depends on support libraries 27.1.0. I am overriding this to 28.0.0

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            details.useVersion '28.0.0'
        }
    }
}

+--- com.davemorrissey.labs:subsampling-scale-image-view:3.10.0
|    +--- com.android.support:support-annotations:27.1.0 -> 28.0.0
|    \--- com.android.support:exifinterface:27.1.0 -> 28.0.0
|         \--- com.android.support:support-annotations:28.0.0

It builds and runs, but I worry about subtle (or eventually less subtle) issues introduced by the mismatch of libraries. Should I not worry? Will SSIV just work fine with 28.0.0?

Alternatively I could downgrade everyone else to 27.1.0, but that just moves the concern elsewhere.

This whole thing was triggered by the upgrades to AS3.3 and a new gradle plugin, which is by default stricter in making sure compile time libraries and run time libraries are consistent.

https://developer.android.com/studio/releases/gradle-plugin#new_features

**Comment by hereisderek** [comment]
might as well migrate to androidx jetpack

**Comment by KirkBushman** [comment]
Would you accept a PR migrating to androidx?

**Comment by hereisderek** [comment]
> Would you accept a PR migrating to androidx?

https://github.com/davemorrissey/subsampling-scale-image-view/pull/461
or you can check out my fork here: https://github.com/hereisderek/subsampling-scale-image-view

**Comment by KirkBushman** [comment]
Ah didn't check before writing, would be nice to merge and keep the project going...

**Comment by hereisderek** [comment]
> Ah didn't check before writing, would be nice to merge and keep the project going...

i didn't actually create the PR before you posted

**Comment by devishell** [comment]
try 
    implementation ('com.davemorrissey.labs:subsampling-scale-image-view:3.10.0'){
        exclude group:'com.android.support', module: 'exifinterface'
    }
    implementation "com.android.support:exifinterface:$rootProject.ext.supportLibraryVersion"

**Comment by davemorrissey** [comment]
See #493 for an updated AndroidX build.
