### ISSUE TITLE
cannot change image

### ISSUE THREAD

**Issue by cuichanghao** [davemorrissey/subsampling-scale-image-view#463]
when i reset image to different bitmap then crash!
is subsampling library not support reset bitmap?

> subsamplingScaleImageView?.setImage(ImageSource.bitmap(resource))

crash error:
> A/Bitmap: Error, cannot access an invalid/free'd bitmap here!

**Comment by davemorrissey** [comment]
Your bitmap has already been recycled. Provide a bitmap that has not been recycled.
