### ISSUE TITLE
Can not display large panoramic images

### ISSUE THREAD

**Issue by minmax9493** [davemorrissey/subsampling-scale-image-view#464]
It's not displaying large panoramic pictures. I referred to https://github.com/davemorrissey/subsampling-scale-image-view/issues/35, but none of them worked for me. The picture size is width 8834, height 1532. How can it to display panoramic images?

**Comment by davemorrissey** [comment]
Issue template deleted, no images, code or error messages provided. Without these I can't help, sorry.
