### ISSUE TITLE
FC without warning on large image

### ISSUE THREAD

**Issue by hexlay** [davemorrissey/subsampling-scale-image-view#466]
Image: https://www.nasa.gov/sites/default/files/thumbnails/image/viirs_9apr2015.jpg
Size: 16.50mb, 15kx15k
I used byte array with output stream to reduce file size up to 3mb from 16, but still it loads with delay (understandable) and when zoom is started, it immediately exits app without logger info...

P.S i also tried open original without reducing and result is the same

**Comment by davemorrissey** [comment]
Closing because the issue template has been deleted so I don't know how you're configuring the view or loading the image.
