### ISSUE TITLE
E/Genrate: Attempt to invoke virtual method 'void com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.setImage(com.davemorrissey.labs.subscaleview.ImageSource)' on a null object reference

### ISSUE THREAD

**Issue by anujkv** [davemorrissey/subsampling-scale-image-view#467]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by anujkv** [comment]
pod_imageview.setImage(ImageSource.bitmap(bitmap));

**Comment by davemorrissey** [comment]
Closing because the issue template has been left blank, and no layout XML or view init code was provided. Your view is null when you try to set the image.
