### ISSUE TITLE
setup library

### ISSUE THREAD

**Issue by jjhesk** [davemorrissey/subsampling-scale-image-view#47]
what is the setup gradle method for this library?

**Comment by davemorrissey** [comment]
I'm not sure what you mean. Are you asking how to add it to your project? Or how to set up an IDE? I don't know a lot about the Android gradle tools.

**Comment by jjhesk** [comment]
yes. I have tried to add to my project but I got an error and stated that the attribute src has been taken. I think it is the issue related to grade settings.

**Comment by davemorrissey** [comment]
I haven't seen this error before, I've used that attribute for a while and you're the first to mention a problem so I don't know what to suggest. Have you tried searching for an answer on stackoverflow and other sites?
