### ISSUE TITLE
View state not restored correctly

### ISSUE THREAD

**Issue by D4no0** [davemorrissey/subsampling-scale-image-view#474]
# Expected behaviour

Zoom state and position should be resored on setImage(@NonNull ImageSource imageSource, ImageSource previewSource) with the previous state.

### Actual behaviour

View state is set to default.

### Steps to reproduce

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_new_act_defect)
        defect_pin.setImage(ImageSource.resource(R.drawable.test_drawing), model.imageViewState)
}

override fun onSaveInstanceState(outState: Bundle) {
        model.imageViewState = defect_pin.state
        super.onSaveInstanceState(outState)
    }
```

Variable model is a ViewModel class that saves the state of the View.

**Comment by davemorrissey** [comment]
You haven't shown what your model field is, but I think it's being deleted on rotate. See https://github.com/davemorrissey/subsampling-scale-image-view/wiki/05.-Orientation-changes

**Comment by D4no0** [comment]
I can confirm that the state was saved after configuration change. Take a look at this commit https://github.com/D4no0/subsampling-scale-image-view/commit/ad1a87b3412618703c2d4f712a056cb1e644a04e . I wanted to make a PR, however I was not sure whether the change was not breaking anything else.
