### ISSUE TITLE
Child Views Is Not zooming 

### ISSUE THREAD

**Issue by rupeshgaud11** [davemorrissey/subsampling-scale-image-view#477]
Hi,
I putted some  Imageviews over SubsamplingScaleImageView. But When I am performing zooming functionality, only SubsamplingScaleImageView is zooming not the views which I putted on top of that one.
What I want is that when I will perform zoom, whatever views which I drawn or putted on top of SubsamplingScaleImageView, they also should zoom with that one.

So, could you please help me, how to achieve that.

**Comment by hereisderek** [comment]
If I understand correctly, both the views aren't linked in anyway (other than sharing the same parent), there's no way for one to change along with the other.

you'll need to let your image view listen to the ssiv's viewport change event and reposition/scale accordingly

**Comment by davemorrissey** [comment]
The view is unaware of child views. You will need to handle scaling of any child views yourself.
