### ISSUE TITLE
OOM still exist while show big picture some times

### ISSUE THREAD

**Issue by andasl** [davemorrissey/subsampling-scale-image-view#479]
operation:
1. A big picture 1080 * 12250(height is not exact) and show original pic  use SubsamplingScaleImageView in Activity
2. touch  and scale , slide

repeat 1
result ： is ok
repeat 2
result ： is ok
repeat 3
result ： is ok
repeat 4
result ： is ok
……

repeat n
result ： OOM
Failed to allocate a 13554012 byte allocation with 6428416 free bytes and 6MB until OOM'

**Comment by andasl** [comment]
3.10.0

**Comment by davemorrissey** [comment]
Code, image and affected devices not provided so I cannot reproduce.
