### ISSUE TITLE
SCALE_TYPE_CUSTOM caused OOM

### ISSUE THREAD

**Issue by andasl** [davemorrissey/subsampling-scale-image-view#480]
bigPicture.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
            bigPicture.setMinScale(1);
3.10.0

**Comment by andasl** [comment]
sometimes it hapends

**Comment by davemorrissey** [comment]
Closing because the issue template has been deleted and no information about affected images and devices was provided.
