### ISSUE TITLE
When rotation 90 or 270, view's width and height wrong.

### ISSUE THREAD

**Issue by jasa2517** [davemorrissey/subsampling-scale-image-view#482]
My question is in this video, please watch this.

[https://youtu.be/OldON8XbH5A](url)

When i rotation 90 or 270, this image can't full view display.

Can anyone help this question?

Thanks a lot!

**Comment by davemorrissey** [comment]
Please refer to the wiki for instructions on handling rotation. It's up to you to set the scale. As you haven't provided your code or described how you've configured the view, I can't answer this question.
