### ISSUE TITLE
how to scale picture for 125% with code

### ISSUE THREAD

**Issue by kangshifu** [davemorrissey/subsampling-scale-image-view#492]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Closing because no information has been provided.
