### ISSUE TITLE
Poor performance when zooming in on drawn path

### ISSUE THREAD

**Issue by Mike-512** [davemorrissey/subsampling-scale-image-view#497]
I have noticed that when I zoom in closely on drawn paths the performance becomes a lot worse but only as long as the Path is in the View. I have also tested this in your Sample of Freehand drawing and the same problem occurs there.

The Performance is not an issue on my Samsung Galaxy Note 10 Plus but I have tested in on a Samsung Galaxy A7(2017) and a Samsung Galaxy Note 4 where the Performance issues occur.

The image I have loaded at the time did not seem to make a big difference.

**Comment by davemorrissey** [comment]
I'm aware of this but it's a limitation in Android I can't do anything about. There have been experiments with SurfaceView but that has its own issues. You might want to experiment with enabling/disabling hardware acceleration to see if that is better for your app.
