### ISSUE TITLE
quickscale with rotation

### ISSUE THREAD

**Issue by KnIfER** [davemorrissey/subsampling-scale-image-view#499]
when ssiv has some rotation, quickscale won't focus on or surround the initial touch point.  

need to  consider rotation  during quick-scale. 

possible simple fix: 
before:
https://github.com/davemorrissey/subsampling-scale-image-view/blob/c722301997dfb83ba2261d25435c3d030d138581/library/src/main/java/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.java#L798-L822

after:
```
.......
if (panEnabled) {
    vTranslate.x = vTranslateStart.x;
    vTranslate.y = vTranslateStart.y;

    PointF quickScaleVStartNow = sourceToViewCoord(quickScalesStart);
    float xd = quickScaleVStart.x - quickScaleVStartNow.x;
    float yd = quickScaleVStart.y - quickScaleVStartNow.y;

    float dx =  (float) (xd * cos - yd * -sin);
    float dy = (float) (xd * -sin + yd * cos);

    vTranslate.x = vTranslateStart.x + dx;
    vTranslate.y = vTranslateStart.y + dy;
}
......

```
where quickScalesStart is a new variable assigned when the  quickscale starts：`quickScalesStart = viewToSourceCoord(quickScaleVStart);`

this works, but is a bit dirty.

**Comment by davemorrissey** [comment]
By rotation, do you mean the 90 degree orientation settings?

**Comment by KnIfER** [comment]
I mean the free rotation.

**Comment by davemorrissey** [comment]
The view doesn't support free rotation. How are you doing it?

**Comment by KnIfER** [comment]
Oh I'm working on another fork. I forgot about it. Sorry...
#304
