### ISSUE TITLE
com.google.android.material.textfield.TextInputLayout not work

### ISSUE THREAD

**Issue by nico6122** [davemorrissey/subsampling-scale-image-view#500]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Expected behaviour

i want to add the search funcionality over the image from SubsamplingScaleImageView

### Actual behaviour

search bar apear behind SubsamplingScaleImageView, the weird thing is im using too a floating button and it work fine.

### Steps to reproduce

`
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/cl_diagram"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

 <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fab_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>

<com.google.android.material.textfield.TextInputLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|top">
        <com.google.android.material.textfield.TextInputEditText
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:hint="test"/>
</com.google.android.material.textfield.TextInputLayout>

 <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:id="@+id/iv_image"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
`

### Affected devices

sdkversion: 29
im working with androidX library

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
I suspect the view you put last is the one that appears on the top but FloatingActionButton is higher Z index by default. However this is not a bug with this library, it's a general Android question best asked on StackOverflow.
