### ISSUE TITLE
How to update image without zooming out

### ISSUE THREAD

**Issue by sagarrishabh** [davemorrissey/subsampling-scale-image-view#502]
I'm working on an image editor and I wanted to use this view to display the processed bitmap. Once the bitmap is processed, I want to replace the current bitmap with a new processed bitmap. But I'm not able to keep the pan at the same position. Any help will be highly appreciated.

**Comment by davemorrissey** [comment]
You'll have to write your own code the fetches the scale and pan before replacing the image, and restores it afterwards. Replacing the image resets the view because it doesn't know whether the new image will be the same size.

**Comment by sagarrishabh** [comment]
@davemorrissey Thanks for the response, I was able to do this by passing the `ImageViewState`. 

Thanks again for this awesome library :)
