### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by Serpov** [davemorrissey/subsampling-scale-image-view#503]
Please, publish library to maven without old android.support dependencies.
Use AndroidX

**Comment by ChristopheCiambella** [comment]
AndroidX is already available for this library, you can use this dependencies :

`
    implementation "com.davemorrissey.labs:subsampling-scale-image-view-androidx:$lastversion"
`

**Comment by Serpov** [comment]
Thanks, could you add this dependency to README?

**Comment by davemorrissey** [comment]
Readme and wiki updated.
