### ISSUE TITLE
Picture shows abnormal

### ISSUE THREAD

**Issue by Yauleisim** [davemorrissey/subsampling-scale-image-view#504]
### Expected behaviour
Picture complete display

### Actual behaviour
The bottom of the picture is a gray block, and it is also gray after zooming

### Steps to reproduce
Open and load pictures

### Affected devices
oppor9s
android 6.0.1

### Affected images

I have no way to upload this picture because this picture is close to 200m

**Comment by davemorrissey** [comment]
What are the dimensions of this image? And can you post your code please?
