### ISSUE TITLE
 网络图片不能加载浏览吗

### ISSUE THREAD

**Issue by shegang** [davemorrissey/subsampling-scale-image-view#506]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by shegang** [comment]
网络图片不能加载浏览吗

**Comment by davemorrissey** [comment]
I'm sorry I don't speak Chinese. Please complete the issue template when reporting issues.

Loading images from the internet is supported by libraries like Glide.
