### ISSUE TITLE
Android crash  on Redmi

### ISSUE THREAD

**Issue by AilsaPeng** [davemorrissey/subsampling-scale-image-view#507]
Affected devices:Redmi 6A(8.1.0)
backtrace:
    r0  84b221a0  r1  00000976  r2  6fb7491c  r3  8a9b7550
    r4  a3aadab0  r5  00000000  r6  00000002  r7  00000000
    r8  00000000  r9  00000002  r10 8ac74ce0  r11 00000000
    ip  00000000  sp  8ac74ba8  lr  acdb2435  pc  acebff4e

    #00 pc 000b8f4e  /system/lib/libandroid_runtime.so (_ZN7android6bitmap12createBitmapEP7_JNIEnvPNS_6BitmapEiP11_jbyteArrayP8_jobjecti+53)
    #01 pc 000fe72f  /system/lib/libandroid_runtime.so
    #02 pc 00a0f4fb  /system/framework/arm/boot-framework.oat (oatexec+4322555)
    #03 pc 00a0fb23  /system/framework/arm/boot-framework.oat (oatexec+4324131)
    #04 pc 003fa175  /system/lib/libart.so
    #05 pc 003ff2e5  /system/lib/libart.so (art_quick_invoke_stub+228)
    #06 pc 000a42f3  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+138)
    #07 pc 001f554f  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE+226)
    #08 pc 001f0add  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
    #09 pc 003e68d3  /system/lib/libart.so (MterpInvokeVirtualQuick+594)
    #10 pc 003f0414  /system/lib/libart.so
    #11 pc 001d7531  /system/lib/libart.so
    #12 pc 001dbbf5  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+148)
    #13 pc 001f0ac5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #14 pc 003e4fc7  /system/lib/libart.so (MterpInvokeInterface+1078)
    #15 pc 003ec894  /system/lib/libart.so
    #16 pc 001d7531  /system/lib/libart.so
    #17 pc 001dbbf5  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+148)
    #18 pc 001f0ac5  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+568)
    #19 pc 003e68d3  /system/lib/libart.so (MterpInvokeVirtualQuick+594)
    #20 pc 003f0414  /system/lib/libart.so
    #21 pc 001d7531  /system/lib/libart.so
    #22 pc 001dbb3d  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+92)
    #23 pc 003d9cc5  /system/lib/libart.so (artQuickToInterpreterBridge+924)
    #24 pc 003fe6f1  /system/lib/libart.so
    #25 pc 00d31dfd  /system/framework/arm/boot-framework.oat (oatexec+7609853)
    #26 pc 004e8937  /system/framework/arm/boot.oat (oatexec+3262775)
    #27 pc 00503a93  /system/framework/arm/boot.oat (oatexec+3373715)
    #28 pc 00510cb1  /system/framework/arm/boot.oat (oatexec+3427505)
    #29 pc 001e54fb  /system/framework/arm/boot.oat (oatexec+103675)
    #30 pc 003fa175  /system/lib/libart.so
    #31 pc 003ff2e5  /system/lib/libart.so (art_quick_invoke_stub+228)
    #32 pc 000a42f3  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+138)
    #33 pc 0034ac4d  /system/lib/libart.so
    #34 pc 0034ba43  /system/lib/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDP6jvalue+322)
    #35 pc 0036b519  /system/lib/libart.so (_ZN3art6Thread14CreateCallbackEPv+836)
    #36 pc 00047507  /system/lib/libc.so
    #37 pc 0001af75  /system/lib/libc.so
at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
    at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:194)
    at subscaleview.decoder.SkiaImageRegionDecoder.a(SourceFile:130)
    at subscaleview.SubsamplingScaleImageView$i.a(SourceFile:1753)
    at subscaleview.SubsamplingScaleImageView$i.doInBackground(SourceFile:1724)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)

**Comment by davemorrissey** [comment]
No details of image or code provided. Please do not delete the issue template.

This is a crash caused by Android code, not an issue with this library.
