### ISSUE TITLE
 crash bug ，please help me，Thanks

### ISSUE THREAD

**Issue by baowenqing** [davemorrissey/subsampling-scale-image-view#509]
> bug
device info : 
model:xiaomi note lte
android6.0
armeabi-v7a
rom:XiaoMi/MIUI

 implementation 'com.davemorrissey.labs:subsampling-scale-image-view:3.10.0'

url :  https://gitee.com/baowenqing/love/raw/master/icon_bg_child_unit.png   [7633*1200]
Some devices will crash  ，please help me，Thanks

```java

// Using the URL above  【R.mipmap.icon_bg_child_unit】
 mBinding.ivBg.setImage(ImageSource.resource(R.mipmap.icon_bg_child_unit).dimensions(7633, 1200))
            mBinding.ivBg.setOnImageEventListener(object :
                SubsamplingScaleImageView.OnImageEventListener {
                override fun onImageLoaded() {
            
                }

                override fun onReady() {
               
                }

                override fun onTileLoadError(e: java.lang.Exception?) {
              
                }

                override fun onPreviewReleased() {
               

                }

                override fun onImageLoadError(e: java.lang.Exception?) {
                
                }

                override fun onPreviewLoadError(e: java.lang.Exception?) {
             
                }

            })



```

#99918 SIGSEGV(SEGV_MAPERR)
com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:121)

#00 pc 00082f58 /system/lib/libandroid_runtime.so (android::Bitmap::getAshmemFd() const+13) [armeabi-v7a]
--
2 #01 pc 00085fef /system/lib/libandroid_runtime.so (GraphicsJNI::createBitmap(_JNIEnv*, android::Bitmap*, int, _jbyteArray*, _jobject*, int)+26) [armeabi-v7a]
3 #02 pc 0008bc55 /system/lib/libandroid_runtime.so [armeabi-v7a]
4 #03 pc 02e887d9 /data/dalvik-cache/arm/system@framework@boot.oat (oatexec+10717145) [armeabi]
5 java:
6 android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:188)
7 com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:84)
8 com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1607)
9 com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1580)
10 android.os.AsyncTask$2.call(AsyncTask.java:295)
11 java.util.concurrent.FutureTask.run(FutureTask.java:237)
12 android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
13 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
14 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

**Comment by davemorrissey** [comment]
Storing images in the mipmap folder is not recommended. Use assets or drawable-nodpi. If this problem continues, it's a problem with your device or with the Skia library - the crash is occurring in Android code.
