### ISSUE TITLE
how to load  image url ?

### ISSUE THREAD

**Issue by Deepshikha01** [davemorrissey/subsampling-scale-image-view#510]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Please read the wiki, past issues, and StackOverflow before opening new issues, and do not leave the issue template blank.

**Comment by Deepshikha01** [comment]
Sorry sir....
