### ISSUE TITLE
when preview is loaded,and origin image has orientation,then preview will be clear

### ISSUE THREAD

**Issue by meanwang** [davemorrissey/subsampling-scale-image-view#511]
version: v3.10

![image](https://user-images.githubusercontent.com/2725966/83741919-5d0cb400-a68b-11ea-8703-3cd54fa1714a.png)

my image real size is { width : 3024 , height : 4032}
but when onTilesInited called ,the param is { width : 4032 , height : 3024 , orientation : 90 }

and then preview bitmap will be recycle,the view becomes black

this is test image file : [lupin.zip](https://github.com/davemorrissey/subsampling-scale-image-view/files/4729109/lupin.zip)

**Comment by davemorrissey** [comment]
Because of the orientation, simply swap width and height when you provide the preview image.
