### ISSUE TITLE
Feature - Need listener while Zooming & Pan and isZoom, isPan

### ISSUE THREAD

**Issue by merlinJeyakumar** [davemorrissey/subsampling-scale-image-view#516]
How to know user Zooming the image?
please add the way to listen that kind of zoom events

**Comment by davemorrissey** [comment]
See setOnStateChangedListener in the source.
https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/main/java/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.java#L2876
