### ISSUE TITLE
About Android10

### ISSUE THREAD

**Issue by ChasingWord** [davemorrissey/subsampling-scale-image-view#524]
How it work in AndroidQ?
How can I load the public pic?

**Comment by davemorrissey** [comment]
Issue template deleted and insufficient information provided. Your questions are unclear.

**Comment by ChasingWord** [comment]
I want to load public pictures.But it haven't permission to load in Android Q.
You throw this Exception in TilesInitTask:
java.io.FileNotFoundException: /storage/emulated/0/MyAppFile/pic/5e38fde6-3290-4f72-bdc8-e65c1ecc713c.jpg: open failed: EACCES (Permission denied)
What should I do?

**Comment by ChasingWord** [comment]
> Issue template deleted and insufficient information provided. Your questions are unclear.

I want to load public pictures.But it haven't permission to load in Android Q.
It throws this Exception in TilesInitTask:
java.io.FileNotFoundException: /storage/emulated/0/MyAppFile/pic/5e38fde6-3290-4f72-bdc8-e65c1ecc713c.jpg: open failed: EACCES (Permission denied)
What should I do?

**Comment by CarsonRedeye** [comment]
@ChasingWord See changes to storage access enforced by android 10 (Q) and 11. This is not related to this library 
https://developer.android.com/about/versions/10/privacy/changes#scoped-storage
