### ISSUE TITLE
Coordinate Mechanics? Is it complex?

### ISSUE THREAD

**Issue by JGuideMaster** [davemorrissey/subsampling-scale-image-view#526]
Usage:
I am using subsampling image view with multiple pinviews, now manually clicked and checked the coordinates in the map to anchor it later from the firebase. Let's say I have 3 different types of pin views but it won't matter here. The problem is devices produces varied coordinate system on the image. I didn't know this as I tried your sample app in the play store with the different devices and it worked well.

Expected behavior:
I am expecting that the coordinates that I saved in the database will be used and be loaded without any problem in the same exact place as originally intended. 

Actual behavior:
Different devices respond differently and create their own coordinate system depending on the screen size? I don't honestly know if it is. So the original pin placements do not match on the other devices.

Steps to reproduce:
There is not much of an important code to check as I did the simplest implementation of this library. 

mapView.setImage(ImageSource.resource(R.drawable.full_map));

Affected devices
1920x1080 various densities, I tried changing it and it just does not really match the original placements. 

I checked the subsampling demo app and it all works fine on any devices without issue and retains the same placement of the pinview I don't know what goes wrong here.

**Comment by davemorrissey** [comment]
Have you read the wiki? There's plenty of information about the helper methods for converting coordinate systems, and the sample app source shows how to use it.

**Comment by JGuideMaster** [comment]
Hi! Thank you so much for the response, I didn't knew you would as I'm expecting you're working in something else. Where is the wiki? Can I get a link for that and yes I checked the source code and I used it as simple as the implementation and didn't do anything. but I'd like to check that wiki for more info.

**Comment by davemorrissey** [comment]
There is a link to the wiki on this page.
