### ISSUE TITLE
Warning: W/od.evomapmarke: Long monitor contention with owner AsyncTask...

### ISSUE THREAD

**Issue by infinitesoft13** [davemorrissey/subsampling-scale-image-view#532]
I use library to preview image size: 16535x10394 19.2 MB.

This is code to load image png:
SubsamplingScaleImageView imgMappa = findViewById(R.id.imaMappa);
imgMappa.setImage(ImageSource.uri(Global.PATH_SD + documenti.getDsRecordID() + ".png"));

When I load image and zoom I have the following log in console:

Warning: W/od.evomapmarke: Long monitor contention with owner AsyncTask #11 (17713) at android.graphics.Bitmap android.graphics.BitmapRegionDecoder.decodeRegion(android.graphics.Rect, android.graphics.BitmapFactory$Options)(BitmapRegionDecoder.java:192) waiters=3 in android.graphics.Bitmap android.graphics.BitmapRegionDecoder.decodeRegion(android.graphics.Rect, android.graphics.BitmapFactory$Options) for 3.147s

Is it due to the size of the image? How can I solve?
Thank you

**Comment by davemorrissey** [comment]
Yes I expect the size of the image causes this and there's nothing that can be done to make it faster, unless you actually are loading from an SD card and have the option of moving it to internal storage. Does the image still load and display correctly? If so then perhaps you can ignore these warnings.

**Comment by infinitesoft13** [comment]
yes the image is loaded correctly!!!

Thanks
Francesco

**Comment by davemorrissey** [comment]
Good, I'll close this because the warnings are normal for such a large image.
