### ISSUE TITLE
native crash

### ISSUE THREAD

**Issue by surcreak** [davemorrissey/subsampling-scale-image-view#534]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Expected behaviour
Load pictures normally

### Actual behaviour
crash

### Steps to reproduce
imageView.setImage(ImageSource.asset("222.png"));
15000 x 15000

### Affected devices
onplus 6t

### Affected images
I can't.

log:

11-24 16:37:41.599 17699 17699 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-24 16:37:41.599 17699 17699 F DEBUG   :     r0  00000000  r1  00004388  r2  00000006  r3  bb7d7be0
11-24 16:37:41.599 17699 17699 F DEBUG   :     r4  bb7d7bf4  r5  bb7d7bd8  r6  00004058  r7  0000016b
11-24 16:37:41.599 17699 17699 F DEBUG   :     r8  bb7d7bf0  r9  bb7d7be0  r10 bb7d7c10  r11 bb7d7c00
11-24 16:37:41.599 17699 17699 F DEBUG   :     ip  00004388  sp  bb7d7bb0  lr  ec60090f  pc  ec600922
11-24 16:37:42.199 17699 17699 F DEBUG   : 
11-24 16:37:42.199 17699 17699 F DEBUG   : backtrace:
11-24 16:37:42.200 17699 17699 F DEBUG   :       #00 pc 0005e922  /apex/com.android.runtime/lib/bionic/libc.so (abort+166) (BuildId: dc42f83dc4923ba221d4d2d85eb935a3)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #01 pc 001cc403  /system/lib/libhwui.so (sk_malloc_throw(unsigned int, unsigned int)+36) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #02 pc 002ab4f7  /system/lib/libhwui.so (SkAutoTMalloc<unsigned char>::reset(unsigned int)+10) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #03 pc 002ae3ad  /system/lib/libhwui.so (SkPngInterlacedDecoder::setRange(int, int, void*, unsigned int)+44) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #04 pc 002ade67  /system/lib/libhwui.so (SkPngCodec::onStartIncrementalDecode(SkImageInfo const&, void*, unsigned int, SkCodec::Options const&)+66) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #05 pc 002a7101  /system/lib/libhwui.so (SkCodec::startIncrementalDecode(SkImageInfo const&, void*, unsigned int, SkCodec::Options const*)+568) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #06 pc 002aebc9  /system/lib/libhwui.so (SkSampledCodec::sampledDecode(SkImageInfo const&, void*, unsigned int, SkAndroidCodec::AndroidOptions const&)+404) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #07 pc 002ae9eb  /system/lib/libhwui.so (SkSampledCodec::onGetAndroidPixels(SkImageInfo const&, void*, unsigned int, SkAndroidCodec::AndroidOptions const&)+686) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #08 pc 002a2da9  /system/lib/libhwui.so (SkAndroidCodec::getAndroidPixels(SkImageInfo const&, void*, unsigned int, SkAndroidCodec::AndroidOptions const*)+500) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #09 pc 000e2d0d  /system/lib/libhwui.so (SkBitmapRegionCodec::decodeRegion(SkBitmap*, SkBRDAllocator*, SkIRect const&, int, SkColorType, bool, sk_sp<SkColorSpace>)+984) (BuildId: 3f8389c02e29c1fc178c962f491c0228)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #10 pc 000f5d7d  /system/lib/libandroid_runtime.so (nativeDecodeRegion(_JNIEnv*, _jobject*, long long, int, int, int, int, _jobject*, long long, long long)+704) (BuildId: 200172d31c0cfbb09790c445f5bd3825)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #11 pc 00294acb  /system/framework/arm/boot-framework.oat (art_jni_trampoline+194) (BuildId: be70fe182dcc3a087951b4456ee81972c0b26be6)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #12 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #13 pc 0043cebf  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+246) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #14 pc 000dff95  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #15 pc 00214963  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+270) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #16 pc 0021182d  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+560) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #17 pc 00436e95  /apex/com.android.runtime/lib/libart.so (MterpInvokeStaticRange+200) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #18 pc 000d2c94  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static_range+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #19 pc 0037e24e  /system/framework/framework.jar (android.graphics.BitmapRegionDecoder.decodeRegion+134)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #20 pc 00432397  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #21 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #22 pc 00118bbc  [anon:dalvik-classes4.dex extracted in memory from /data/app/xxx.xxx.xxx-l8lGg5cmGpXbO5VBLZXMRw==/base.apk!classes4.dex] (xx.xx.xxxxt.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion+64)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #23 pc 0043389d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #24 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #25 pc 00113006  [anon:dalvik-classes4.dex extracted in memory from /data/app/xxx.xxx.xxx-l8lGg5cmGpXbO5VBLZXMRw==/base.apk!classes4.dex] (xxx.xxx.xxx.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground+270)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #26 pc 00432397  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #27 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #28 pc 001130fc  [anon:dalvik-classes4.dex extracted in memory from /data/app/xxx.xxx.xxx-l8lGg5cmGpXbO5VBLZXMRw==/base.apk!classes4.dex] (xxx.xxx.xxx.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground+4)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #29 pc 00432397  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #30 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #31 pc 002e4c78  /system/framework/framework.jar (android.os.AsyncTask$3.call+40)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #32 pc 0043389d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #33 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.200 17699 17699 F DEBUG   :       #34 pc 001ee8a2  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.FutureTask.run+62)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #35 pc 0043389d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #36 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #37 pc 001f98ea  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor.runWorker+158)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #38 pc 00432397  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1226) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #39 pc 000d2814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #40 pc 001f8698  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor$Worker.run+4)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #41 pc 0043389d  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1536) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #42 pc 000d2a14  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+20) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #43 pc 000ec0f0  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Thread.run+8)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #44 pc 001f097f  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.5942017264677920626+166) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #45 pc 001f5393  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+122) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #46 pc 00426807  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+866) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #47 pc 000dc5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #48 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #49 pc 0043cdad  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+248) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #50 pc 000dff81  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+168) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #51 pc 0037d157  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #52 pc 0037deeb  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+302) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #53 pc 003afb4f  /apex/com.android.runtime/lib/libart.so (art::Thread::CreateCallback(void*)+1018) (BuildId: 99f7eb15aadcee6e1b5eab03dbb4ff2f)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #54 pc 000a6aa1  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) (BuildId: dc42f83dc4923ba221d4d2d85eb935a3)
11-24 16:37:42.201 17699 17699 F DEBUG   :       #55 pc 0005fdc9  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: dc42f83dc4923ba221d4d2d85eb935a3)

**Comment by davemorrissey** [comment]
This is a crash from within the skia image decoding library which is part of Android. It's not something I can fix. The best thing you can do is open and re-save that image, which is fairly likely to solve the problem.

**Comment by surcreak** [comment]
The simple test demo I wrote did not have this problem when loading two big pictures, but it appeared in the main project of our company. 
Check that the native memory allocated by the memory usage test demo is higher than the main memory.
please help me.

**Comment by davemorrissey** [comment]
This is likely to be a problem with the specific image. As I suggested, try re-saving the affected image using different software. There is nothing I can do about a native crash caused by an Android component.

**Comment by SmartVive** [comment]
ndk {
            abiFilters 'armeabi','arm64-v8a'
        }
support arm64-v8a it's working for me
