### ISSUE TITLE
Handle cases when DisplayMetrics report incorrect xdpi and ydpi

### ISSUE THREAD

**Issue by theimpulson** [davemorrissey/subsampling-scale-image-view#536]
### Expected behavior

Images get scaled properly even if the device reports incorrect xdpi and ydpi by using the device's density as a comparison.

### Actual behavior

Due to missing checks, the scaling of images is very small.

### Steps to reproduce

- Grab a Nokia 6.1
- Install any custom OS like LineageOS: [Website](https://www.lineageos.org/), [GitHub](https://github.com/LineageOS/), [Downloads](https://download.lineageos.org/PL2) in my case.
- Notice that the device reports incorrect xdpi and ydpi while rest information is correct.

### Affected devices

Nokia 6.1, 420 DPI, Custom OS only

### Affected images

Any images or apps that use this library are affected. Apps like Tachiyomi, Sync for Reddit, Boost for Reddit are notable examples.

### Information reported by the custom OS on the affected device

```
DisplayMetrics{density=2.625,width=1080,height=1920,scaledDensity=2.625,xdpi=4.031,ydpi=4.031}
```

### Expected fix

Use the device density as a condition to compare the reported xdpi and ydpi before scaling the image and use the best one possible.

**Comment by theimpulson** [comment]
Relevant Issue: https://github.com/davemorrissey/subsampling-scale-image-view/issues/505

I opened an issue for this in Tachiyomi as well which is an affected app: https://github.com/inorichi/tachiyomi/issues/4131

**Comment by davemorrissey** [comment]
This a bug in the custom OS, has it been reported to them? Any app that uses xdpi or ydpi will be broken by this so it seems better to fix the root cause.

**Comment by theimpulson** [comment]
I won't say that this is a custom OS issue but a device firmware issue. Other than mine, none of the other devices I am aware of are affected but again this is also a fact that the only device from Nokia that is supporting custom ROMs right now is mine. I noticed some other devices overriding framework values to report an expected xdpi and ydpi:
- [Cristian0808/halium_device_samsung_gtexswifi](https://github.com/Cristian0808/halium_device_samsung_gtexswifi/blob/ee8c7d5df6efe430d7098d20955b0acc72dfedbc/patches/frameworks_native/0001-SPRD-tweaks.patch#L190)

Then there are devices that are using emulator density property to fix this issue:
- https://github.com/naobsd/cm_device_rockchip_rk2818/commit/9d360199c1ed2d0f3430858a1acb6471166905c1

You can notice that in the last commit, the date is from 2011, so I can say that this issue exists for a way long time in devices running custom OS.

For now, I have also decided to use the emulator property to set DPI which overrides the value in the framebuffer and makes the apps using the xdpi and ydpi values works but again it is better to have a fallback in the library in my opinion?
- https://github.com/LineageOS/android_device_nokia_PL2/commit/674cca945c3a7c3c4b33a0b02e957230e361a18c

Hence, closing this issue.
