### ISSUE TITLE
Does any great god teach this how to use it in (react native)?

### ISSUE THREAD

**Issue by wulaizi** [davemorrissey/subsampling-scale-image-view#537]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
I'm sorry I don't use React Native. Perhaps you could ask on StackOverflow?
