### ISSUE TITLE
How do I add pins on ImageView

### ISSUE THREAD

**Issue by osrl** [davemorrissey/subsampling-scale-image-view#54]
Maybe this isn't the right place to ask this question. I want to add some pins, as an ImageView(preferably, because I have to open an info window on click) or as a Drawable. I tried to subclass your view and draw a rect on `onDraw` but the rect is not scrolling. Do you have any idea how to do that? Could you show me a road to do so?

**Comment by davemorrissey** [comment]
Please see the example class [PinView](https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/sample/src/com/davemorrissey/labs/subscaleview/sample/extension/views/PinView.java)

**Comment by osrl** [comment]
Wow, so sorry. I didn't see it.
