### ISSUE TITLE
Seems to be unable to display gif pictures

### ISSUE THREAD

**Issue by wulaizi** [davemorrissey/subsampling-scale-image-view#540]
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by davemorrissey** [comment]
Duplicate of several other issues, please search before raising new ones. Please don't leave the template empty.
