### ISSUE TITLE
I am getting a crash inside SubsamplingScaleImageView draw()

### ISSUE THREAD

**Issue by mostafaimran** [davemorrissey/subsampling-scale-image-view#544]
native: #186 pc 0000000000547e50  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448)
    runtime.cc:655]   native: #187 pc 000000000054830c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92)
    runtime.cc:655]   native: #188 pc 0000000000431e24  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+636)
    runtime.cc:655]   native: #189 pc 0000000000099428  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124)
    runtime.cc:655]   native: #190 pc 00000000000a0880  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+836)
    runtime.cc:655]   native: #191 pc 0000000000003574  /system/bin/app_process64 (main+1324)
    runtime.cc:655]   native: #192 pc 000000000004973c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108)
    runtime.cc:655]   at android.graphics.BaseRecordingCanvas.nDrawBitmapMatrix(Native method)
    runtime.cc:655]   at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:78)
    runtime.cc:655]   at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1111)
    runtime.cc:655]   at android.view.View.draw(View.java:22350)
    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21226)
    runtime.cc:655]   at android.view.View.draw(View.java:22081)
    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21217)
    runtime.cc:655]   at android.view.View.draw(View.java:22081)
    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21217)
    runtime.cc:655]   at android.view.View.draw(View.java:22081)
    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21217)
    runtime.cc:655]   at android.view.View.draw(View.java:22081)
    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    runtime.cc:655]   at android.view.View.draw(View.java:22353)
    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21226)
    runtime.cc:655]   at android.view.View.draw(View.java:22081)
    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21217)
    runtime.cc:655]   at android.view.View.draw(View.java:22081)
    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21217)
    runtime.cc:655]   at android.view.View.draw(View.java:22081)
    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
    runtime.cc:655]   at android.view.View.draw(View.java:22353)
    runtime.cc:655]   at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1998)

**Comment by davemorrissey** [comment]
You have deleted the issue template and not provided most of the requested information.

**Comment by mostafaimran** [comment]
It's crashing on the Line : com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1111)

Inside SubsamplingScaleImageView onDraw()

**Comment by hufeiya** [comment]
Hello friend，I 'm getting the same error with you, have you fixed it?

**Comment by mostafaimran** [comment]
hello @hufeiya I added the SubsamplingScaleImageView inside a FrameLayout. 

Whenever I need to update the bitmap then I do this - 

frameLayout.removeAllViews()
val subsamplingScaleImageView = SubsamplingScaleImageView()
frameLayout.addView(subsamplingScaleImageView)


In this way I overcome the crash.

**Comment by hufeiya** [comment]
> 

Thanks a lot. @mostafaimran
I fixed it by another way:
I used Glide for loading image. Before I use CustomViewTarget<SubsamplingScaleImageView, Bitmap>. Now I use CustomTarget< Drawable > and convert drawable to bitmap. the crash fixed.
