### ISSUE TITLE
Scale over 0.3 produces black (blank) screen

### ISSUE THREAD

**Issue by bio007** [davemorrissey/subsampling-scale-image-view#549]
I'm using cached bitmap image source with bitmap obtained from remote url. The setup is quite simple, I'm not doing anything special with view's parameters.

After I zoom over 0.3 scale the view turns black. After returning to < 0.3 scale the image is visible again. There is no error reported to any callback from the view.

Value 0.3 is not constant but it looks in my case it's the last threshold when it works reliably. Scales bigger than 0.3 can work in some parts of the image e.g. 0.4 is alright when source center is ~ in the middle of the image but after moving / panning to the edge of the image, it suddenly turns black. Moving back or scaling above 0.3 renders the image again.

Any info why is this happening would be appreciated.

![image](https://user-images.githubusercontent.com/144213/115152708-6ff56080-a072-11eb-86f6-98de57086295.png) ![image](https://user-images.githubusercontent.com/144213/115152782-e2664080-a072-11eb-8cea-943061aa70ae.png)

**Comment by davemorrissey** [comment]
If you are using a very large bitmap, it may be larger than the maximum texture size, which is sometimes only 2048px but more commonly 4096px. The view is designed to render tiles to avoid this limitation, but cannot do this with a bitmap, it has to be able to load tiles from the file system.
