### ISSUE TITLE
Fatal signal 11 (SIGSEGV) while debugging.

### ISSUE THREAD

**Issue by osrl** [davemorrissey/subsampling-scale-image-view#56]
This only happens while debugging. Any idea why this happens? Setting a breakpoint to your sample app can reproduce this. 

`Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3d in tid 15818 (JDWP)`

**Comment by davemorrissey** [comment]
The view does a massive amount of loading and rendering of large image objects. I suspect the debugger can't cope with it. I haven't tried using a debugger with the sample app because it's almost impossible to debug touch events and logging works better.

It's very unlikely I'll be able to do anything to resolve this.

**Comment by osrl** [comment]
This makes it impossible to debug anything unrelated to SSImageView. Even if image is not set yet, this error happens. Are you sure it is related to rendering?

**Comment by davemorrissey** [comment]
Please provide full details of your test devices, android version, development environment etc.

**Comment by davemorrissey** [comment]
I also need more details of the error, a full stack trace, logcat preceding the error, anything you have tried to resolve it, and what evidence you have that it's this library causing the problem.

**Comment by davemorrissey** [comment]
Using the sample app, with breakpoints in the activity, and in the view's onTouchEvent and onDraw methods (i.e. the most frequently called methods), debugging is fast and doesn't cause any errors. Tested on HTC One S/Android 4.1.1 and Nexus 7/Android 5.0.2 on OS X Yosemite with Android Studio.

This could be a problem with a particular version of Android, manufacturer modifications to stock Android, your version of the tools or IDE, or many other things. I don't think the view itself is responsible. There is a chance one of the core Android classes it uses could be, but that seems unlikely if you haven't set the image at the point it crashes.

**Comment by davemorrissey** [comment]
Not enough information available to reproduce.

**Comment by osrl** [comment]
Sorry for the delay. My test device is HTC One google_m7 (Google Edition)/Android 5.0.1 on OS X Yosemite with Android Studio. I will test with different devices if I can.

**Comment by davemorrissey** [comment]
Apart from the phone, I tested the sample app on almost exactly this setup. Perhaps it's a problem with HTC's changes to stock Android.

**Comment by osrl** [comment]
This didn't happen on an HTC One/Android 5.0.1 with sense. So it looks like it's a problem with HTC's changes to stock Android.
