### ISSUE TITLE
Couldn't load memtrack module

### ISSUE THREAD

**Issue by cockroach904** [davemorrissey/subsampling-scale-image-view#564]
Hi~I got "Couldn't load memtrack module" error when i setImage~
     but this problem not always happen,
     Is there any to solve the problem?

Glide.with(this@InspectionTagActivity)
            .asBitmap()
            .load("url")
            .into(object : CustomTarget<Bitmap>() {
                override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                    try {
                        viewModel.cacheMapBitMap = resource
                        pin_view.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_START)
                        ImageSource.bitmap(resource).apply {
                            pin_view.setImage(this)
                        }
                    } catch (e: Exception) {
                        Timber.e("onResourceReady: $e")
                    }
                }

                override fun onLoadCleared(placeholder: Drawable?) {
                }
            })

**Comment by davemorrissey** [comment]
You have deleted the issue template and not provided any information about your device.

This may help: https://stackoverflow.com/questions/22629568/couldnt-load-memtrack-module-logcat-error
