### ISSUE TITLE
Listener OnImageEventListener actions are not called when view is invisible.

### ISSUE THREAD

**Issue by osrl** [davemorrissey/subsampling-scale-image-view#59]
I want to show a progress view and hide subsampling scale image view while loading image. But the event listeners are not called when image view is invisible/hidden(that's interesting). Since I can't set image source to null, is there a way to clear image view as a workaround so I don't need to setVisibility of an image view?

**Comment by davemorrissey** [comment]
The view does not load if it is hidden, because onDraw will not be called and it may have no dimensions. It needs to be visible on screen, but you can overlay another view with transparency.

**Comment by osrl** [comment]
I get it, but wouldn't a clear method would be nice?

**Comment by davemorrissey** [comment]
Use `recycle()`

**Comment by osrl** [comment]
I already tried it but it doesn't clear the image. It is still visible. Nothing happened
