### ISSUE TITLE
src attribute conflicts with other libraries

### ISSUE THREAD

**Issue by mariotaku** [davemorrissey/subsampling-scale-image-view#61]
Some libraries (e.g. https://github.com/koral--/android-gif-drawable) has src attribute therefore aapt fails when building.

'src' attribute is too general, I think other name like subsamplingSrc would be better.

**Comment by davemorrissey** [comment]
Changing the attribute name would be backwardly incompatible so I'd rather not to that unless I have to. As this is the first and so far only report of this problem I'll close this for now and keep an eye on it. I'm not sure it will help you, but I recommend not using attributes to configure the view, and instead set the source from code.

**Comment by mariotaku** [comment]
Actually even not using attribute mentioned above, aapt still fails, cause all attributes will be merged into one file first.
