### ISSUE TITLE
How to Scale CENTER_CROP_START ?

### ISSUE THREAD

**Issue by leelei** [davemorrissey/subsampling-scale-image-view#67]

**Comment by davemorrissey** [comment]
What does that mean? I can't find any documentation for that in the ScaleType enum.

**Comment by kyze8439690** [comment]
It maybe means that crop the image at the top. If you view an image which has a huge height, it is much more better to view it at the top instead of view it with CENTER_CROP.

**Comment by leelei** [comment]
just as kyze8439690  said

**Comment by davemorrissey** [comment]
You can set the initial position like this:

    SubsamplingScaleImageView imageView = (SubsamplingScaleImageView)findViewById(id.imageView);
    imageView.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP);
    imageView.setImage(ImageSource.asset("squirrel.jpg"), new ImageViewState(0, new PointF(0, 0), SubsamplingScaleImageView.ORIENTATION_0));

**Comment by tarekk** [comment]
@davemorrissey  this doesn't work . The image is still centered any other way ?

**Comment by xkubow** [comment]
Working like charm, thanks
