### ISSUE TITLE
OutOfMemoryError on SkiaImageRegionDecoder.java:75

### ISSUE THREAD

**Issue by avp2306** [davemorrissey/subsampling-scale-image-view#68]
Hi Dave - hope all is well and your library is growing. We've previously investigated another issue related to image formats (jpeg vs png) that was resulting in blurriness - and I'm glad to report that it has been resolved for good now, have not had a single report since.

I've recently started using crash reporting that comes with the Fabric.io sdk which really gives in depth details when crashes or uncaught exceptions occur, and this has allowed me to track down the following error:

Full Stack trace was too long to post here, I included a link (this also has device stats)
https://drive.google.com/file/d/0B0PB7PKUtmYkazR2clkwenlLV1k/view?usp=sharing

Caused by java.lang.OutOfMemoryError
android.graphics.BitmapRegionDecoder.nativeDecodeRegion (BitmapRegionDecoder.java)
android.graphics.BitmapRegionDecoder.decodeRegion (BitmapRegionDecoder.java:383)
com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion (SkiaImageRegionDecoder.java:75)
com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground (SubsamplingScaleImageView.java:1404)
com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground (SubsamplingScaleImageView.java:1378)

I also noticed that System.GC was called in the stack trace by another thread, assuming system was running out of memory and triggered a garbage collection cycle.

Reporting also shows 160MB average amount of  available ram (based on 10 crash reports so far). 

I feel that out of memory can be hard to control, but what steps or techniques can I employ to minimize the number of these instances?

As always, your help is greatly appreciated.

Thanks,
-Alex

**Comment by davemorrissey** [comment]
I couldn't get much information from that doc, unfortunately it doesn't say what the affected devices were. Assuming you're using a PNG, the first thing to do is make sure it doesn't have an alpha layer. Beyond that, the only way to reduce memory usage is to set a lower minimumTileDpi (e.g. 240 or 320). This trades a bit of quality for a reduced chance of OOME on ultra high resolution screens.

Theoretically, high resolution devices should have enough memory to deal with large images but that doesn't always seem to be the case, and you'll often find the whole image is loaded at native resolution unless you reduce the minimumTileDpi.

**Comment by avp2306** [comment]
Dave - thanks for the reply and reviewing the logs.

I am already using JPEG format and setting minimumTileDpi to 160, for reference here's the code I'm using:

_imgMap = (com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView) findViewById(R.id.imgScaledImageViewMap);
        _imgMap.setDoubleTapZoomDpi(200);
        _imgMap.setMinimumTileDpi(160);
        _imgMap.setOnImageEventListener(null);
        _imgMap.setOnImageEventListener(new SubsamplingScaleImageView.OnImageEventListener() {
            @Override
            public void onReady() { }
            @Override
            public void onImageLoaded() { }
            @Override
            public void onPreviewLoadError(Exception e) {
                L.e(TAG, "setOnImageEventListener.onPreviewLoadError", e);
            }
            @Override
            public void onImageLoadError(Exception e) {
                L.e(TAG, "setOnImageEventListener.onImageLoadError", e);
            }
            @Override
            public void onTileLoadError(Exception e) {
                L.e(TAG, "setOnImageEventListener.onTileLoadError", e);
            }
        });

        _imgMap.setImage(ImageSource.asset("map.jpg"));

Do you think calling System.GC before initializing the image would help ?

**Comment by davemorrissey** [comment]
System.gc is unlikely to help because the VM will run the GC automatically if it is asked to allocate a large object. Also, System.gc runs asynchronously and may not complete before the image is allocated, and is not guaranteed to run at all. You could try it anyway.

It's quite surprising that even with the minimum DPI set so low you're seeing these errors, and it makes me wonder whether there were other memory hungry applications running on the devices that prevented the normal heap from being allocated. I don't know for sure whether Android is guaranteed to reap those processes if necessary.

I have had virtually no reports of OOMEs in the last year, except when the view is used in a view pager so two or more views are in memory at the same time, so that's another thing to check for, though if I remember correctly you only have one image.

The last suggestion I have is to request a larger heap using `android:largeHeap="true"` on your `<Application>` element.

**Comment by avp2306** [comment]
Thanks for suggesting largeHeap flag. After reading up on it, I think its a good idea to try in my situation.

I also took a snapshot of the summary Crashlytics provides and it really seems to come from a verity of devices: http://screencast.com/t/vMLxSBGt

**Comment by avp2306** [comment]
Ok, one more detail, thought I should point it out after you mentioned multiple instances of image / view pager. 

I only have 1 instance of the image control, however I do load 2 separate images. They are identical formats in jpeg and similar size, maybe off by a few pixels. But I have a button allowing the user to alternate between map images displayed. 

Should I perform any cleanup before swapping the images? I load them from assets. 

BTW from stack it would seem it happens onTile so I assume this is when the user is zooming.

Here is the entire code block that I use:

 _imgMap = (com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView) findViewById(R.id.imgScaledImageViewMap);
        _imgMap.setDoubleTapZoomDpi(200);
        _imgMap.setMinimumTileDpi(160);
        _imgMap.setOnImageEventListener(null);
        _imgMap.setOnImageEventListener(new SubsamplingScaleImageView.OnImageEventListener() {
            @Override
            public void onReady() { }
            @Override
            public void onImageLoaded() { }
            @Override
            public void onPreviewLoadError(Exception e) {
                L.e(TAG, "setOnImageEventListener.onPreviewLoadError", e);
            }
            @Override
            public void onImageLoadError(Exception e) {
                L.e(TAG, "setOnImageEventListener.onImageLoadError", e);
            }
            @Override
            public void onTileLoadError(Exception e) {
                L.e(TAG, "setOnImageEventListener.onTileLoadError", e);
            }
        });

        _imgMap.setImage(ImageSource.asset("map.jpg"));

        // Map vs Night Map selection button
        findViewById(R.id.vwMapType).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                boolean hasSubscription = PrefHandler.getPremiumFlag(MapActivity.this);
                ImageView imgBtnMapType = (ImageView)findViewById(R.id.imgBtnMapType);
                TextView tvMapType = (TextView) findViewById(R.id.tvMapType);
                switch (_selectedMapMode) {
                    case MAP_MODE_DAY:
                        if (hasSubscription) {
                            _imgMap.setImage(ImageSource.asset("map_night.jpg")); //Switch to NIGHT MODE
                            _selectedMapMode = MAP_MODE_NIGHT;
                            imgBtnMapType.setImageResource(R.drawable.ic_map);
                            tvMapType.setText("REGULAR MAP");
                            U.makeToast("Night Service", Toast.LENGTH_SHORT);
                            L.ev(C.GA_CATEGORY_ui,C.GA_ACTION_display_screen,"night_map",(long) 0);
                        } else {
                            Intent intent = new Intent(MapActivity.this, UpgradeActivity.class);
                            intent.putExtra("from", "from_night_map");
                            startActivity(intent);
                        }
                        break;
                    case MAP_MODE_NIGHT:
                        _imgMap.setImage(ImageSource.asset("map.jpg")); //Switch to DAY MODE
                        _selectedMapMode = MAP_MODE_DAY;
                        imgBtnMapType.setImageResource(R.drawable.ic_brightness_2);
                        tvMapType.setText("NIGHT SERVICE MAP");
                        U.makeToast("Regular Service", Toast.LENGTH_SHORT);
                        break;
                }
            }
        });

**Comment by davemorrissey** [comment]
The way you're doing this looks fine, switching the image causes the view to recycle all the tiles from the previous image so will not require double the memory. The error is happening during loading of tiles, and that includes the base layer so it could be during the initial load or zooming.

I don't think I've had any reports of OOMEs for a simple use case like this where you've set the minimum tile DPI and only have a single view displayed at once. I believed that I'd completely eliminated errors for this case. This makes me wonder whether something else in your app uses a lot of memory, or (more likely as you haven't seen this error yourself) these phones had something else memory hungry running that Android could or would not kill.

I'm afraid the large heap suggestion is the last one I have!

**Comment by fractalwrench** [comment]
Thanks for a great library! I'm also seeing this crash on some older devices running Android 4. I will attempt the largeHeap suggestion, and can also add some more logging to try and find out what the most common cause of the crash is.

**Comment by nauman404** [comment]
I faced the same issue. Actually i was using 3rd class device for testing. Image resolutions were high that device was not supporting. Anyways, above suggestions helped a lot.

**Comment by mahesh825mahi** [comment]
![ozwqu](https://cloud.githubusercontent.com/assets/11849050/9002132/cb41aea8-377d-11e5-8b64-2ac0ea2f365b.png)

**Comment by davemorrissey** [comment]
I'll close this now as I'm seeing so few reports of OOMEs and the design has improved since it was opened.

**Comment by NammariMarkavip** [comment]
+1
