### ISSUE TITLE
Setting an image by resource returns black and white images

### ISSUE THREAD

**Issue by SalvaP** [davemorrissey/subsampling-scale-image-view#69]
using parts of your example code (ViewPagerActivity - ViewPagerFragment) in another app, but usign drawable-hdpi images (jpgs), the method
            ((SubsamplingScaleImageView)rootView.findViewById(R.id.imageView)).setImage(ImageSource.resource(resID));

returns all black and white images

i copied the assets folder from your project and tested
      ((SubsamplingScaleImageView)rootView.findViewById(R.id.imageView)).setImage(ImageSource.asset("squirrel.jpg"));

this works

**Comment by davemorrissey** [comment]
This is a problem with the image decoder, you'll need to either re-encode the images until it works or try implementing another decoder - see https://github.com/davemorrissey/subsampling-scale-image-view/wiki/04.-Custom-decoders

**Comment by SalvaP** [comment]
Thanks for the quick reply, meanwhile had arrived at the same solution.
I think the problem is related to the use of compression utility like Jpegtran, JPEGOptim and Jpegrescan.

Thanks again!
