### ISSUE TITLE
PinView marker onClick

### ISSUE THREAD

**Issue by DoubleTime** [davemorrissey/subsampling-scale-image-view#71]
Hi,
First of all I will want to thank you for providing such great library !

My question is there a way to detect the marker click at PinView?
And then show a text on top of the marker?

**Comment by davemorrissey** [comment]
You need to override touch handling (there are other samples for this) and detect whether the coordinates overlap your pin, then just render the text above it.

**Comment by venkatesh87** [comment]
Hi Dave, Thanks for this wonderful library.

Could you please point me to the correct sample for marker onClick? I couldn't find it anywhere the application.

**Comment by developerShubhamAgr** [comment]
@DoubleTime  did you solve this?

**Comment by OmarHassan25** [comment]
@DoubleTime  have you solved it?
