### ISSUE TITLE
No error callback when tiling disabled

### ISSUE THREAD

**Issue by HorstFuchs** [davemorrissey/subsampling-scale-image-view#72]
Hi, 
If I disable tiling for an image that is not supposed to load, but to call an error callback, the last thing I get is:

D/skia﹕ --- SkImageDecoder::Factory returned null

not followed by any callback from `SubsamplingScaleImageView#OnImageEventListener()` at all.

Image:
![_4012_1](https://cloud.githubusercontent.com/assets/12443516/7630267/a066580e-fa34-11e4-95f9-73364cf1d5bb.jpg) (corrupted one)
v3.1.3: Nexus6@5.1, SM-T535@4.4.2

**Comment by davemorrissey** [comment]
The Skia decoder often returns a null bitmap instead of throwing an exception, and I didn't report this error to listeners. I have now changed the view to throw an exception if it receives a null bitmap, so listeners will be notified. This is released in v3.1.4.
