### ISSUE TITLE
error in lib in this line  of code 

### ISSUE THREAD

**Issue by erumhannan** [davemorrissey/subsampling-scale-image-view#73]
private DecoderFactory<? extends ImageDecoder> bitmapDecoderFactory = new CompatDecoderFactory<ImageDecoder>(SkiaImageDecoder.class);
    private DecoderFactory<? extends ImageRegionDecoder> regionDecoderFactory = new CompatDecoderFactory<ImageRegionDecoder>(SkiaImageRegionDecoder.class);

The constructor CompatDecoderFactory<ImageDecoder>(Class<SkiaImageDecoder>) is undefined

**Comment by davemorrissey** [comment]
This change hasn't been released yet. How are you including the library? It looks like you haven't copied those classes into your project.

**Comment by erumhannan** [comment]
i copied classes in project but issue still exists my target i to zoomout background image of either button with text ................ or imageview zoomout while my background image is not zooming out how to resolve any idea i want this type of animation http://www.dailymotion.com/video/x2qx2if  pls check

**Comment by davemorrissey** [comment]
I suggest you use a released version of the library instead of copying the classes, I'm unable to support unreleased versions. If you need to copy the classes, you must make sure the package structure is correct.
