### ISSUE TITLE
NullPointerException when using both a preview image and an ImageViewState

### ISSUE THREAD

**Issue by enderminh** [davemorrissey/subsampling-scale-image-view#78]
Not sure if I am doing something wrong, but I can consistently reproduce this bug:

Repro
========
compile 'com.davemorrissey.labs:subsampling-scale-image-view:3.1.3'

1. Use SubsamplingScaleImageView on a fragment
2. Place fragment to activity (via getSupportFragmentManager().beginTransaction().replace([id], myFragment).commit();
3. In the fragment's onCreateView(), load a preview image as well as an ImageStateView:

   mySubsamplingScaleImageView.setImage(
                    ImageSource.resource(myFullImage).dimensions(8000, 8000),
                    ImageSource.resource(myPreviewImage),
                    someNonNullImageViewState);

Expected
========
4. Preview image loads at the desired pan/zoom-state (fine for it to be blurry)
5. Preview image gets replaced with high-resolution image after decoding is done

Actual
=========
App crashes with this stack trace:

E/AndroidRuntime( 6852): java.lang.NullPointerException: Attempt to write to field 'float android.graphics.PointF.x' on a null object reference
E/AndroidRuntime( 6852):        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.preDraw(SubsamplingScaleImageView.java:1147)
E/AndroidRuntime( 6852):        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.checkReady(SubsamplingScaleImageView.java:1012)
E/AndroidRuntime( 6852):        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onPreviewLoaded(SubsamplingScaleImageView.java:1548)
E/AndroidRuntime( 6852):        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.access$5500(SubsamplingScaleImageView.java:59)
E/AndroidRuntime( 6852):        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.onPostExecute(SubsamplingScaleImageView.java:1519)
E/AndroidRuntime( 6852):        at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.onPostExecute(SubsamplingScaleImageView.java:1478)
E/AndroidRuntime( 6852):        at android.os.AsyncTask.finish(AsyncTask.java:636)
E/AndroidRuntime( 6852):        at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/AndroidRuntime( 6852):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/AndroidRuntime( 6852):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6852):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6852):        at android.app.ActivityThread.main(ActivityThread.java:5257)
E/AndroidRuntime( 6852):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6852):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6852):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 6852):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

This problem does not occur if I am only using imageViewState or only using a preview image. It repros only if I use both.

Let me know if I can help debug.

**Comment by davemorrissey** [comment]
Thanks for this very clear bug report! Once I fixed the NPE I found that the tile map was not set up correctly causing the view to run out of memory, so it took a while to fix. I have just released v3.1.4 with this fix.

**Comment by enderminh** [comment]
Awesome Dave. I verified that this is fixed with 3.1.4.

Your library is awesome. Any way I can donate to your via PayPal/Google Wallet/Bitcoin to show some support?

**Comment by davemorrissey** [comment]
That's a very kind offer but no need to worry!
