### ISSUE TITLE
Is there a technical restriction why not to extend from ImageView?

### ISSUE THREAD

**Issue by Upimage** [davemorrissey/subsampling-scale-image-view#81]
I'm developing a photo viewing and managing app. It uses some concepts like memory and file caching and async tasks to load image quickly. I like your library for your implementation of loading big images using tiles. That's a feature I really would like to have in my app, but integrating your View is very hard because your view does not extend ImageView. Dealing with another view extended from ImageView would be very easy in my app.
My question: Is it feasible to extend your view from ImageView?   
Thanx in advance, Markus

**Comment by davemorrissey** [comment]
ImageView is capable of drawing graphics of all sorts, including shape drawables, 9-patches and bitmaps. It also has a lot of options for positioning and scaling the image and adjusting its color, but it is really intended to display a single static image in a fixed position. SSIV is completely different - it's built from the ground up for displaying huge images (bitmaps only) with touch gestures, so there is almost nothing in common with ImageView and most of ImageView's methods cannot be implemented by SSIV.

What's the problem you're having integrating the view? Have you looked at the setup guides?
