### ISSUE TITLE
Animation interrupted by View size change

### ISSUE THREAD

**Issue by Dortamur** [davemorrissey/subsampling-scale-image-view#82]
I have an app where the size of the ImageView can change to make room for another view. If this view size change occurs while I have a pending animateScaleAndCenter animation, then the scale does not occur.

**Comment by davemorrissey** [comment]
There are many possible ways to handle a view resize and I chose to preserve the centre point (repositioned to the new centre) and scale, with both values adjusted if necessary to fit the new bounds. This means the image will normally move on screen when the view is resized, so any animation currently running has to be interrupted.

If you need different behaviour, you can override `onSizeChanged`. Simply overriding it with an empty method may do what you need, but depending on the current position of the image when the resize occurs, the animation may jump.

**Comment by Dortamur** [comment]
Thanks! I shall give that a go.
