### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by kkrishnan90** [davemorrissey/subsampling-scale-image-view#83]
Hi Dave, 
Thanks for this excellent library. Appreciate your work on this. Now, in my case I have a problem in compiling the code in android studio (gradle build). When I add your library and compile/build my code, I have an error which says "Attribute:src is already defined" . I tried lots of ways to fix it. And I even confirmed that only after adding your Subsampling scale image library this error pops up during build. 
Can you to provide me a solution or guide me on how to fix this problem?

**Comment by davemorrissey** [comment]
This was also reported in #61, which I closed because there had only been one report of an error and I'm reluctant to make a backwardly incompatible change. Clearly it's a bit more common than I hoped. Do you know what other library this is conflicting with?

**Comment by kkrishnan90** [comment]
Hi Dave, 
Thanks for your response ! I solved it myself. Wasn't sure about which library it was conflicting with but anyways.. I think its just about clearing the caches and invalidating the android studio.. It worked like charm .. Thanks a lot Dave.. Also, let me know if your image set function supports for views apart from imageviews and imagebuttons like buttons too ? Cuz, I'm planning to set background for buttons which is a dynamic image(HD) and text on top.

**Comment by davemorrissey** [comment]
No that's not supported but you can easily add your own text overlay by creating a subclass. Take a look at the classes in the sample project.

**Comment by kkrishnan90** [comment]
Alright thanks a ton for the library Dave!

**Comment by davemorrissey** [comment]
Sure, just send me the link when it's published.

**Comment by kkrishnan90** [comment]
Hi Dave ! Hope you're doing great ! Thanks a ton for your library ! It just works flawlessly... Definitely I'll be using your library for lot of my upcoming apps. And well here's the good news, the app has been released in Google Play. I am attaching the link for the app, request you to please add it to the hall of fame record of yours.. 
https://play.google.com/store/apps/details?id=com.pst.mrwhipped&hl=en

Thanks a ton once again Dave !  Expecting a lot more libraries from you ... You rock ! Keep going !

**Comment by davemorrissey** [comment]
Thanks for the link, I've added it to the readme!

**Comment by kkrishnan90** [comment]
Thanks a lot Dave ! Wish you could create more revolutionary libraries like these ! My best wishes and thanks again !

**Comment by LuigiPapino** [comment]
Just for reference, here a library that conflict with SubSamplingScaleImageView:

'org.rocko.bpb:library:1.0.0'
