### ISSUE TITLE
PNG not loaded on Nexus 5

### ISSUE THREAD

**Issue by gyatsina** [davemorrissey/subsampling-scale-image-view#86]
Hi, 
When I am trying to user setImage with   .png image on Nexus 5 device (platform 5.1.1) - I see only white screen.
Issue happens only on Nexus 5.  Any exceptions from code is seen.
Did you face with the same issue?
Probably there is an option to overcome it?

Regards,
Galina

**Comment by XBeg9** [comment]
+1

**Comment by davemorrissey** [comment]
You should see something in logcat if the image decoding failed, but if the decoder failed silently and returned a blank image you might not see anything. Please could you attach the image?
Try re-encoding the image with a different graphics package, removing the alpha layer, and if necessary, use a custom decoder as described in the wiki.

**Comment by davemorrissey** [comment]
Closing - insufficient information. Please provide more details.

**Comment by gyatsina** [comment]
Hi

according to my investigation bug is related to this issue:
https://code.google.com/p/android/issues/detail?id=80316


On some Lollipop devices (in my case on Nexus 5) big PNG images were not loaded. 
BitmapRegionDecoder was returning null for decoded image with size 4300*4800.
Resizing of image was not the case. Cause we had on image lots of words. And so after any sufficient resizing quality of font was lost. 

The solution was: 1) to use JPG format
2) image should have 24 bit depth (not 8 bit!)

**Comment by davemorrissey** [comment]
Thanks for that info. I've also raised bugs with Google and the skia library, and they (like this one) have been completely ignored by Google so I'm not optimistic skia will be improved. It's actually getting worse with each release of Android.
