### ISSUE TITLE
Only support JPEG and PNG

### ISSUE THREAD

**Issue by pop1030123** [davemorrissey/subsampling-scale-image-view#87]
when i load the image ,it doesn't display and got the error below:
onImageLoadError:java.io.IOException: Image failed to decode using JPEG decoder

does it only support jpeg and png format?

**Comment by pop1030123** [comment]
07-10 00:17:06.352 D/skia    (28585): --- decoder->buildTileIndex returned false
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): Failed to initialise bitmap decoder
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): java.io.IOException: Image failed to decode using JPEG decoder
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:61)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1370)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1346)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-10 00:17:06.352 E/SubsamplingScaleImageView(28585): 	at java.lang.Thread.run(Thread.java:841)
07-10 00:17:06.352 D/GALLERY:ImageShowFragment:(28585): onImageLoadError:java.io.IOException: Image failed to decode using JPEG decoder

**Comment by davemorrissey** [comment]
You haven't said what format your image is, but yes, only JPG and PNG are supported. Please see this page for details https://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images

**Comment by mittalharsh54** [comment]
i am using png image but I am also getting same error. What should i do pls tell me,
