### ISSUE TITLE
Loading Bitmaps

### ISSUE THREAD

**Issue by bluebery** [davemorrissey/subsampling-scale-image-view#88]
What is the expected behaviour when a bitmap `result`, that has been used for `setImage(ImageSource.bitmap(result))` is modified in an AsyncTask? 

I am getting mixed results - namely, the image in the view is only getting partially updated. The amount it gets updated (anywhere from 10% to 100% of the screen, vertically) appears random. The rest of the view displays the previous `result` bitmap.

I have tried calling `requestLayout` after the bitmap `result` has been updated (following completion of AyncTask), but it has no effect on what is displayed.

Is there something I need to do to get the SubsamplingScaleImageView to re-render the bitmap after the async task has updated it?

**Comment by davemorrissey** [comment]
I've never tried this and it isn't really a supported feature, but I don't really know why it doesn't work. You could try calling the view's `invalidate` method to prompt a redraw.

**Comment by bluebery** [comment]
thanks very much for your reply. Invalidate() didn't help me so I ended up just refactoring to draw to my `result` bitmap on the UI thread; the async task was left to just deal with disk IO

**Comment by davemorrissey** [comment]
Ah, I may have missed something important there - if you're calling `invalidate` from another thread, that won't work, and you need to use `postInvalidate` instead.

**Comment by bluebery** [comment]
I was trying `imageView.invalidate()` from the `onPostExecute` of my Async task so it would have been on the UI thread. It does end up triggering the `onDraw` method in `SubscamplingScaleImageView` and goes all the way down to `canvas.drawBitmap(bitmap, matrix, bitmapPaint)` - a breakpoint there reveals `bitmap` contains the expected result but it doesn't end up drawing it completely to the canvas.

One thing to note is that I am using fragments here in a viewpager and it is the view pager events that I am using to trigger the `result` bitmap generation async task when the fragment comes into view.

Don't stress it too much, I may have made a poor assumption elsewhere that may be the cause of this .. and my refactor seems to do the trick.

**Comment by davemorrissey** [comment]
Sure, I'll close this issue. One other thing that might cause this is the state of the bitmap not being synchronized between threads, but as I don't know its internals I'm not sure this is relevant.
