### ISSUE TITLE
Scale animation differences

### ISSUE THREAD

**Issue by 0xCyril** [davemorrissey/subsampling-scale-image-view#90]
I have trouble to use the scaling when using ".animateScaleAndCenter(scale, point)", for the same scale value, the more the screen resolution is, the more the viewable area is.

The documentation is not clear about that, how it is working exactly ?

Basically I want to zoom to see a frame of the image, I have a "Rect object" with source coordinate.

**Comment by davemorrissey** [comment]
The scale is a ratio of screen pixels to source image pixels, so it will vary with screen density. To show a rectangle, you can calculate the width or height of your rectangle in source image pixels, then calculate a scale based on the screen width.
