### ISSUE TITLE
Converting local images skia's format

### ISSUE THREAD

**Issue by yazeed44** [davemorrissey/subsampling-scale-image-view#91]
Hello
I'm creating a gallery to display images , it seems i can't load some .png + .jpg and i can't load .jpeg and .gif at all

In Custom decoders section you wrote
```Whenever possible, convert your images to a format Android's Skia library can support, and test them with a variety of devices.```

And i have been wondering to convert the images to android skia format

```java
@Override
    public Object instantiateItem(ViewGroup container, int position) {
        final ImageEntry imageEntry = mAlbumEntry.imageList.get(position);
        final SubsamplingScaleImageView imageView = new SubsamplingScaleImageView(mContext);

        setupTouchGesture(imageView);
        imageView.setImage(ImageSource.uri(imageEntry.path));

        container.addView(imageView, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        return imageView;
    }
```

**Comment by davemorrissey** [comment]
Your code doesn't do any conversion of the image. If an image can't be read by skia, then you need to open it in a graphics editor and save it again, and in most cases that will fix it. If not, you can try changing the output format or using another graphics editor. Loading the image on the device and saving it again may help in some cases, but only if the whole image is guaranteed to fit in memory.

GIFs are not supported by this view.

**Comment by yazeed44** [comment]
```then you need to open it in a graphics editor and save it again```
That's the problem , i can't because my app gets the images from the device storage

**Comment by yazeed44** [comment]
Is there a way to format the images in the code ?

**Comment by davemorrissey** [comment]
You can try loading and re-saving the image on the device, but only if you're certain it will fit in memory as a Bitmap.

**Comment by yazeed44** [comment]
<but only if you're certain it will fit in memory as a Bitmap.
That's the problem , i could use glide for this objective but it can't exceed 4096x4096

**Comment by davemorrissey** [comment]
I'm afraid I don't have any more answers. See the wiki for a guide on how to build a custom decoder, and details of the limitations of this view.
