### ISSUE TITLE
Reset scale 

### ISSUE THREAD

**Issue by iglaweb** [davemorrissey/subsampling-scale-image-view#92]
How can I reset scale of the image to initial state? (e.g. after orientation change) What is the proper way?

I'am doing it with:

```java
mImage.setScaleAndCenter(mCurrentState.getScale(), mCurrentState.getCenter());
```
where mCurrentState is a saved state of the image that was set in onReady method.

**Comment by davemorrissey** [comment]
If by initial state you mean fully zoomed out and centered, this works:
    setScaleAndCenter(0, new PointF(0f, 0f));
