### ISSUE TITLE
Start at scale other than min

### ISSUE THREAD

**Issue by santafebound** [davemorrissey/subsampling-scale-image-view#93]
I've already sent an email but I'm new to Git so I didn't realize you could submit issues directly. 

I was wondering, is there a simple solution to setting the initial scale to something other than the minimum? I would like to set the minimum to something a lot smaller than what the user sees upon opening the view for the first time.

**Comment by davemorrissey** [comment]
I saw your email, but I've been very busy, sorry!

If you know the dimensions of your image, you can pass an ImageViewState object with the image source like this:

    view.setMinScale(0.25);
    view.setImage(src, new ImageViewState(0.5f, new PointF(width/2, height/2), 0);

Otherwise, you can set the min scale to 0.5f when you initialise the view, then use an event listener to set the min scale to 0.25f when the image is ready.

Disclaimer - I haven't tried either approach but I'm fairly confident :-)

**Comment by santafebound** [comment]
Dave,

Thanks a bunch! This is how we did it. Simple enough:

Might be worth putting a small note on your repo. Might be helpful for
beginners at least!

SubsamplingScaleImageView img =
(SubsamplingScaleImageView)item.findViewById(R.id.templateImage);

            // defaults; scale with custom limits and starting point,
disable pan (i.enable view pagers) & zoom
            img.setPanLimit(SubsamplingScaleImageView.PAN_LIMIT_OUTSIDE);

img.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
            img.setMinScale(0.25f);
            img.setMaxScale(3.0f);
            img.setPan(false);
            img.setZoomEnabled(false);

Also, I was wondering if you could add my app to your Hall of Fame?

https://play.google.com/store/apps/details?id=com.elgami.customizer

Just pushing the latest build now so it should be available with the image
library implemented in the next few hours...

Thanks a bunch! You rock.

On Mon, Jul 27, 2015 at 11:39 AM, davemorrissey <notifications@github.com>
wrote:

> I saw your email, but I've been very busy, sorry!
>
> If you know the dimensions of your image, you can pass an ImageViewState
> object with the image source like this:
>
> view.setMinScale(0.25);
> view.setImage(src, new ImageViewState(0.5f, new PointF(width/2, height/2), 0);
>
> Otherwise, you can set the min scale to 0.5f when you initialise the view,
> then use an event listener to set the min scale to 0.25f when the image is
> ready.
>
> Disclaimer - I haven't tried either approach but I'm fairly confident :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davemorrissey/subsampling-scale-image-view/issues/93#issuecomment-125300842>
> .
>



-- 
Best Regards,
Martin Erlić

   - UDesign - Personalize Your World <http://www.elgami.com>
   <http://www.econstreams.com/>
   - EconStreams.com - Comprehension at the Edge of Chaos
   <http://www.econstreams.com/>

**Comment by santafebound** [comment]
Here's a logo should you need it!

On Mon, Jul 27, 2015 at 1:36 PM, Martin Erlic <martin.erlic@gmail.com>
wrote:

> Dave,
>
> Thanks a bunch! This is how we did it. Simple enough:
>
> Might be worth putting a small note on your repo. Might be helpful for
> beginners at least!
>
> SubsamplingScaleImageView img =
> (SubsamplingScaleImageView)item.findViewById(R.id.templateImage);
>
>             // defaults; scale with custom limits and starting point,
> disable pan (i.enable view pagers) & zoom
>             img.setPanLimit(SubsamplingScaleImageView.PAN_LIMIT_OUTSIDE);
>
> img.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
>             img.setMinScale(0.25f);
>             img.setMaxScale(3.0f);
>             img.setPan(false);
>             img.setZoomEnabled(false);
>
> Also, I was wondering if you could add my app to your Hall of Fame?
>
> https://play.google.com/store/apps/details?id=com.elgami.customizer
>
> Just pushing the latest build now so it should be available with the image
> library implemented in the next few hours...
>
> Thanks a bunch! You rock.
>
> On Mon, Jul 27, 2015 at 11:39 AM, davemorrissey <notifications@github.com>
> wrote:
>
>> I saw your email, but I've been very busy, sorry!
>>
>> If you know the dimensions of your image, you can pass an ImageViewState
>> object with the image source like this:
>>
>> view.setMinScale(0.25);
>> view.setImage(src, new ImageViewState(0.5f, new PointF(width/2, height/2), 0);
>>
>> Otherwise, you can set the min scale to 0.5f when you initialise the
>> view, then use an event listener to set the min scale to 0.25f when the
>> image is ready.
>>
>> Disclaimer - I haven't tried either approach but I'm fairly confident :-)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/davemorrissey/subsampling-scale-image-view/issues/93#issuecomment-125300842>
>> .
>>
>
>
>
> --
> Best Regards,
> Martin Erlić
>
>    - UDesign - Personalize Your World <http://www.elgami.com>
>    <http://www.econstreams.com/>
>    - EconStreams.com - Comprehension at the Edge of Chaos
>    <http://www.econstreams.com/>
>
>


-- 
Best Regards,
Martin Erlić

   - UDesign - Personalize Your World <http://www.elgami.com>
   <http://www.econstreams.com/>
   - EconStreams.com - Comprehension at the Edge of Chaos
   <http://www.econstreams.com/>
