### ISSUE TITLE
How to drop multiple pin over image view.

### ISSUE THREAD

**Issue by mahesh825mahi** [davemorrissey/subsampling-scale-image-view#94]
How to drop multiple pin over image view.

**Comment by davemorrissey** [comment]
You need to give more information about what you're trying to do, but have a look at the wiki and the sample project, you should find your answer there.

**Comment by mahesh825mahi** [comment]
![large](https://cloud.githubusercontent.com/assets/11849050/8905696/127c2820-3486-11e5-9feb-e72aec5c32ef.png)

I have attached image for your reference, have a look on it.

**Comment by davemorrissey** [comment]
Please see the sample app, it has an example class with pins.

**Comment by mahesh825mahi** [comment]
yes, i go thought the full code. i can able to add single "marker" over it but multiple marker can not.

Please have look the blow code that you have written:
 
imageView.setPin(new PointF(1718f, 581f));
imageView.setPin(new PointF(1192f, 565f));

i using above code to add 2 pins but it took second  point only (1192f, 565f).

**Comment by davemorrissey** [comment]
You need to adjust the sample to your own needs. I can't help with that.

**Comment by mahesh825mahi** [comment]
Thanks for you response.
