### ISSUE TITLE
[Question] Is there a built-in way to load image over http?

### ISSUE THREAD

**Issue by tomoyuki28jp** [davemorrissey/subsampling-scale-image-view#95]
I try thing like this: 
```java
String uri = "http://example.com/foo.png";

imageView.setImage(ImageSource.uri(uri))
// or 
imageView.setImage(ImageSource.uri(Uri.parse(uri)));
```

In the both cases, I get an error like this: 
```sh
E/SubsamplingScaleImageView﹕ Failed to initialise bitmap decoder
    java.io.FileNotFoundException: No content provider http://example.com/foo.png
```

("http://example.com/foo.png" is just a dummy url and I get the same error when I try with an existing image url.)

**Comment by tomoyuki28jp** [comment]
If there is no built-in way, is there a way to show loading indicator image and replace them after loading image over http? When we load image over http in background, onPostExecute might not be executed in the order I want to show images so I think we cannot just use setImage in my case?

**Comment by davemorrissey** [comment]
There's no built in way because it isn't possible to tile an image loaded over HTTP. You have to download it to a file first. For a loading indicator, please see the wiki.

**Comment by tomoyuki28jp** [comment]
@davemorrissey Thanks for your reply!

> For a loading indicator, please see the wiki.

I checked the wiki, but I'm not sure how can I show a loading indicator image (like imageView holder) and replace the image. Could you point me out specific wiki page url? Thanks in advance!

**Comment by JavierSolis** [comment]
tomoyuki28jp x2

**Comment by crjacinro** [comment]
Just want to share my solution.

I solved this by using Glide library to download the image first and save it into the cache directory of Android. Afterwards, the image is loaded as a URI. So subsampling optimization is not lost (i hope)

`Glide.with(context)
            .asBitmap()
            .load(myURL!!)
            .into(object : SimpleTarget<Bitmap>(1024, 768) {
                override fun onResourceReady(resource: Bitmap?, transition: Transition<in Bitmap>?) {
                    val savedImagePath = saveImage(resource!!)
                    if (savedImagePath.isNullOrEmpty()) {
                        notify(R.string.maps_unable_to_load)
                    } else {
                        map_preview.setImage(ImageSource.uri(savedImagePath))
                    }
                }
            })

private fun saveImage(image: Bitmap): String? {
        var savedImagePath: String? = null

        val imageFileName = URL(myURL).file.replace("/", "")
        val directory = activity?.cacheDir?.absolutePath
        val storageDir =
            File("$directory/maps")
        var success = true
        if (!storageDir.exists()) {
            success = storageDir.mkdirs()
        }
        if (success) {
            val imageFile = File(storageDir, imageFileName)
            savedImagePath = imageFile.absolutePath
            try {
                val fOut = FileOutputStream(imageFile)
                image.compress(Bitmap.CompressFormat.JPEG, 100, fOut)
                fOut.close()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return savedImagePath`

**Comment by chanicheetah** [comment]
@crjacinro  did you manage to place a holder in case no image exists?
