### ISSUE TITLE
Query Exif Orientation for content-Uris

### ISSUE THREAD

**Issue by DavidWiesner** [davemorrissey/subsampling-scale-image-view#98]
Hi,

at first thanks for this great library!
I have some problem when set an image-Uri as source with a 'content'-scheme. So for example: 'content://media/external/images/media/74'. Then the 'SubsamplingScaleImageView' can´t recognize their orientation. I know you described in your [Wiki: 02. Displaying images](https://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images#orientation) that you don´t. But you can query the orientation on the `MediaStore` content resolver:
```java
	public int getOrientationFromMediaStore(Uri imageUri) {
		int exifOrientation = 0;
		final String[] columns = {MediaStore.Images.Media.ORIENTATION};
		final Cursor cursor = context.getContentResolver().query(imageUri, columns, null, null, null);
		if (cursor != null) {
			if(cursor.moveToFirst()){
				exifOrientation = cursor.getInt(0);
			}
			cursor.close();
		}
		return exifOrientation;
	}
```

so the new [`getExifOrientation`](https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.java#L1599) method could look like this:

```java
	private int getExifOrientation(String sourceUri) {
		int exifOrientation = ORIENTATION_0;
		if (sourceUri.startsWith(ContentResolver.SCHEME_CONTENT)){
			return getOrientationFromMediaStore(Uri.parse(sourceUri));
		} else if (sourceUri.startsWith(ImageSource.FILE_SCHEME) && !sourceUri.startsWith(ImageSource.ASSET_SCHEME)) {
			// like before ...
		}
		return exifOrientation;
	}
```

regards,
David

**Comment by davemorrissey** [comment]
Thanks for this suggestion, I've just pushed a commit with this change and it will be included in the next release.

**Comment by DavidWiesner** [comment]
:thumbsup: thx
