### ISSUE TITLE
Getting sigsegv while trying to load 4000x4000 png file

### ISSUE THREAD

**Issue by shmoula** [davemorrissey/subsampling-scale-image-view#99]
Galaxy Nexus running MIUI-4.8.8., Android 4.2.2 JDQ39
This is the image: http://grapeadmin2015.esx.sk/files/map/img/17/grape_map-2.png

F/libc    (22070): Fatal signal 11 (SIGSEGV) at 0x625cc000 (code=1), thread 22210 (AsyncTask #3)
I/DEBUG   (  126): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  126): Build fingerprint: 'Android/full_maguro/maguro:4.2.2/JDQ39/4.8.8:user/release-keys'
I/DEBUG   (  126): Revision: '9'
I/DEBUG   (  126): pid: 22070, tid: 22210, name: AsyncTask #3  >>> sk.o2.grape <<<
I/DEBUG   (  126): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 625cc000
I/DEBUG   (  126):     r0 625cbff0  r1 5c951a01  r2 00000158  r3 00000008
I/DEBUG   (  126):     r4 625cb208  r5 625cb208  r6 5c8a9fcc  r7 5eb63b48
I/DEBUG   (  126):     r8 54414449  r9 00000000  sl 000000ff  fp 4042c7fd
I/DEBUG   (  126):     ip 00000000  sp 5eb63a38  lr 403e84d3  pc 4014668c  cpsr 28000010
I/DEBUG   (  126):     d0  0202020202020202  d1  0202020202020202
I/DEBUG   (  126):     d2  183c242011020202  d3  1903030303645334
I/DEBUG   (  126):     d4  0101010101010103  d5  0101010101010101
I/DEBUG   (  126):     d6  0101010101010101  d7  0101010101010101
I/DEBUG   (  126):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  126):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  126):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  126):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  126):     d16 0101010101010101  d17 3ff0000000000000
I/DEBUG   (  126):     d18 0000000000000000  d19 3fa55553e1053a42
I/DEBUG   (  126):     d20 3feffffffffffdd9  d21 bf2a00f9e2cae768
I/DEBUG   (  126):     d22 0000000000000000  d23 3ff0000000000000
I/DEBUG   (  126):     d24 3ff0000000000000  d25 0000000000000000
I/DEBUG   (  126):     d26 0000000000000000  d27 0000000000000000
I/DEBUG   (  126):     d28 0000000000000000  d29 3ff0000000000000
I/DEBUG   (  126):     d30 3ff0000000000000  d31 3ff0000000000000
I/DEBUG   (  126):     scr 20000013
I/DEBUG   (  126): 
I/DEBUG   (  126): backtrace:
I/DEBUG   (  126):     #00  pc 0001868c  /system/lib/libc.so (memcpy+140)
I/DEBUG   (  126):     #01  pc 001074cf  /system/lib/libskia.so
I/DEBUG   (  126):     #02  pc 000fd27b  /system/lib/libskia.so (png_read_row+870)
I/DEBUG   (  126):     #03  pc 000fd307  /system/lib/libskia.so (png_read_rows+46)
I/DEBUG   (  126):     #04  pc 000b2838  /system/lib/libskia.so (SkPNGImageDecoder::onDecodeRegion(SkBitmap*, SkIRect)+836)
I/DEBUG   (  126):     #05  pc 000ad8f4  /system/lib/libskia.so (SkImageDecoder::decodeRegion(SkBitmap*, SkIRect, SkBitmap::Config)+76)
I/DEBUG   (  126):     #06  pc 000acf9c  /system/lib/libskia.so (SkBitmapRegionDecoder::decodeRegion(SkBitmap*, SkIRect, SkBitmap::Config, int)+84)
I/DEBUG   (  126):     #07  pc 0007066f  /system/lib/libandroid_runtime.so
I/DEBUG   (  126):     #08  pc 0001e290  /system/lib/libdvm.so (dvmPlatformInvoke+112)
I/DEBUG   (  126):     #09  pc 0004d411  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+396)
I/DEBUG   (  126):     #10  pc 000276a0  /system/lib/libdvm.so
I/DEBUG   (  126):     #11  pc 0002b57c  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
I/DEBUG   (  126):     #12  pc 0005fc31  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+272)
I/DEBUG   (  126):     #13  pc 0005fc5b  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
I/DEBUG   (  126):     #14  pc 000547d7  /system/lib/libdvm.so
I/DEBUG   (  126):     #15  pc 0000e3d8  /system/lib/libc.so (__thread_entry+72)
I/DEBUG   (  126):     #16  pc 0000dac4  /system/lib/libc.so (pthread_create+160)
I/DEBUG   (  126): 
I/DEBUG   (  126): stack:
I/DEBUG   (  126):          5eb639f8  5ca529d8  
I/DEBUG   (  126):          5eb639fc  5c8ab055  
I/DEBUG   (  126):          5eb63a00  5c94f060  
I/DEBUG   (  126):          5eb63a04  5c94f2f8  
I/DEBUG   (  126):          5eb63a08  00000000  
I/DEBUG   (  126):          5eb63a0c  5c951b99  
I/DEBUG   (  126):          5eb63a10  00000000  
I/DEBUG   (  126):          5eb63a14  00000001  
I/DEBUG   (  126):          5eb63a18  00000fa1  
I/DEBUG   (  126):          5eb63a1c  000012f0  
I/DEBUG   (  126):          5eb63a20  401ba4b8  /system/lib/libz.so
I/DEBUG   (  126):          5eb63a24  fffffffc  
I/DEBUG   (  126):          5eb63a28  401ba58c  /system/lib/libz.so
I/DEBUG   (  126):          5eb63a2c  00008848  
I/DEBUG   (  126):          5eb63a30  df0027ad  
I/DEBUG   (  126):          5eb63a34  00000000  
I/DEBUG   (  126):     #00  5eb63a38  625cb208  
I/DEBUG   (  126):          5eb63a3c  403e84d3  /system/lib/libskia.so
I/DEBUG   (  126):     #01  5eb63a40  00000000  
I/DEBUG   (  126):          5eb63a44  00000003  
I/DEBUG   (  126):          5eb63a48  00000117  
I/DEBUG   (  126):          5eb63a4c  0000014b  
I/DEBUG   (  126):          5eb63a50  5c8a9e08  
I/DEBUG   (  126):          5eb63a54  5eb63b48  
I/DEBUG   (  126):          5eb63a58  54414449  /dev/ashmem/dalvik-mark-stack (deleted)
I/DEBUG   (  126):          5eb63a5c  5c8a9e08  
I/DEBUG   (  126):          5eb63a60  625cb208  
I/DEBUG   (  126):          5eb63a64  5c8a9fcc  
I/DEBUG   (  126):          5eb63a68  5eb63b48  
I/DEBUG   (  126):          5eb63a6c  54414449  /dev/ashmem/dalvik-mark-stack (deleted)
I/DEBUG   (  126):          5eb63a70  00000000  
I/DEBUG   (  126):          5eb63a74  5c8a9f40  
I/DEBUG   (  126):          5eb63a78  4042c7fd  /system/lib/libskia.so
I/DEBUG   (  126):          5eb63a7c  403de27f  /system/lib/libskia.so (png_read_row+874)
I/DEBUG   (  126):     #02  5eb63a80  40376264  /system/lib/libskia.so (SkMemoryStream::read(void*, unsigned int))
I/DEBUG   (  126):          5eb63a84  0007ffff  
I/DEBUG   (  126):          5eb63a88  625cb208  
I/DEBUG   (  126):          5eb63a8c  00000001  
I/DEBUG   (  126):          5eb63a90  5c8a9e08  
I/DEBUG   (  126):          5eb63a94  00000000  
I/DEBUG   (  126):          5eb63a98  5eb63b48  
I/DEBUG   (  126):          5eb63a9c  00000001  
I/DEBUG   (  126):          5eb63aa0  00000000  
I/DEBUG   (  126):          5eb63aa4  00000000  
I/DEBUG   (  126):          5eb63aa8  00000001  
I/DEBUG   (  126):          5eb63aac  403de30b  /system/lib/libskia.so (png_read_rows+50)
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near r0:
I/DEBUG   (  126):     625cbfd0 02020202 02020202 02020202 02020202  
I/DEBUG   (  126):     625cbfe0 11020202 183c2420 03645334 19030303  
I/DEBUG   (  126):     625cbff0 01010103 01010101 01010101 01010101  
I/DEBUG   (  126):     625cc000 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc010 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc020 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc030 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc040 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc050 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc060 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc070 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc080 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc090 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc0a0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc0b0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126):     625cc0c0 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near r1:
I/DEBUG   (  126):     5c9519e0 01010319 01010101 01010101 01010101  
I/DEBUG   (  126):     5c9519f0 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a00 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a10 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a20 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a30 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a40 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a50 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a60 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a70 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a80 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951a90 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951aa0 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951ab0 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951ac0 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     5c951ad0 01010101 01010101 01010101 01010101  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near r4:
I/DEBUG   (  126):     625cb1e8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb1f8 01010101 01010101 01010101 00010101  
I/DEBUG   (  126):     625cb208 01010100 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb218 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb228 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb238 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb248 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb258 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb268 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb278 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb288 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb298 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2a8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2b8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2c8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2d8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near r5:
I/DEBUG   (  126):     625cb1e8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb1f8 01010101 01010101 01010101 00010101  
I/DEBUG   (  126):     625cb208 01010100 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb218 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb228 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb238 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb248 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb258 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb268 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb278 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb288 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb298 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2a8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2b8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2c8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126):     625cb2d8 01010101 01010101 01010101 01010101  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near r6:
I/DEBUG   (  126):     5c8a9fac 00000fa0 000007d0 5c951bc0 5c950bf8  
I/DEBUG   (  126):     5c8a9fbc 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8a9fcc 00000fa0 00000fa0 08010803 00052d90  
I/DEBUG   (  126):     5c8a9fdc 96ff6021 5c9109d8 00010100 54414449  
I/DEBUG   (  126):     5c8a9fec 00000000 08030000 00010800 00000008  
I/DEBUG   (  126):     5c8a9ffc 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa00c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa01c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa02c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa03c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa04c 00000000 00000000 5c910ce0 00000000  
I/DEBUG   (  126):     5c8aa05c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa06c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa07c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa08c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5c8aa09c 00000000 00000000 00000000 00000000  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near r7:
I/DEBUG   (  126):     5eb63b28 00000008 00000003 00000000 00000003  
I/DEBUG   (  126):     5eb63b38 00000000 5b42dfb8 00000000 625cb208  
I/DEBUG   (  126):     5eb63b48 00000000 00000000 000007d0 000007d0  
I/DEBUG   (  126):     5eb63b58 00000fa0 000007d0 00000000 00000000  
I/DEBUG   (  126):     5eb63b68 00000001 00000001 00000000 00000000  
I/DEBUG   (  126):     5eb63b78 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     5eb63b88 00000000 40437f80 5a6375f8 5a6375f8  
I/DEBUG   (  126):     5eb63b98 4038df48 00000000 5a6375f8 5c5cbfc0  
I/DEBUG   (  126):     5eb63ba8 5c8a9da8 4038e8f8 00000000 00000000  
I/DEBUG   (  126):     5eb63bb8 000007d0 000007d0 5eb63bec 00000004  
I/DEBUG   (  126):     5eb63bc8 5c5cbfc0 4038dfa0 00000000 00000000  
I/DEBUG   (  126):     5eb63bd8 000007d0 000007d0 00000004 5a6375f8  
I/DEBUG   (  126):     5eb63be8 5a589d88 1d200005 402a56f0 4027c671  
I/DEBUG   (  126):     5eb63bf8 00000000 00000000 000007d0 000007d0  
I/DEBUG   (  126):     5eb63c08 00000004 00000001 00000000 5a6375f8  
I/DEBUG   (  126):     5eb63c18 00000001 00000004 00000000 00000000  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near r8:
I/DEBUG   (  126):     54414428 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414438 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414448 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414458 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414468 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414478 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414488 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414498 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     544144a8 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     544144b8 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     544144c8 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     544144d8 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     544144e8 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     544144f8 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414508 00000000 00000000 00000000 00000000  
I/DEBUG   (  126):     54414518 00000000 00000000 00000000 00000000  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near fp:
I/DEBUG   (  126):     4042c7dc 67616d69 61642065 45006174 61727478  
I/DEBUG   (  126):     4042c7ec 6d6f6320 73657270 20646573 61746164  
I/DEBUG   (  126):     4042c7fc 63654400 72706d6f 69737365 65206e6f  
I/DEBUG   (  126):     4042c80c 726f7272 6f6f5400 6e616d20 44492079  
I/DEBUG   (  126):     4042c81c 73275441 756f6620 4900646e 6567616d  
I/DEBUG   (  126):     4042c82c 20736920 206f6f74 68676968 206f7420  
I/DEBUG   (  126):     4042c83c 636f7270 20737365 68746977 676e7020  
I/DEBUG   (  126):     4042c84c 6165725f 6e705f64 00292867 6c6c6143  
I/DEBUG   (  126):     4042c85c 206f7420 4c4c554e 61657220 75662064  
I/DEBUG   (  126):     4042c86c 6974636e 43006e6f 206c6c61 4e206f74  
I/DEBUG   (  126):     4042c87c 204c4c55 6b656573 6e756620 6f697463  
I/DEBUG   (  126):     4042c88c 6552006e 45206461 726f7272 27744900  
I/DEBUG   (  126):     4042c89c 6e612073 72726520 7420726f 6573206f  
I/DEBUG   (  126):     4042c8ac 6f622074 72206874 5f646165 61746164  
I/DEBUG   (  126):     4042c8bc 206e665f 20646e61 74697277 61645f65  
I/DEBUG   (  126):     4042c8cc 665f6174 6e69206e 65687420 61730020  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory near sp:
I/DEBUG   (  126):     5eb63a18 00000fa1 000012f0 401ba4b8 fffffffc  
I/DEBUG   (  126):     5eb63a28 401ba58c 00008848 df0027ad 00000000  
I/DEBUG   (  126):     5eb63a38 625cb208 403e84d3 00000000 00000003  
I/DEBUG   (  126):     5eb63a48 00000117 0000014b 5c8a9e08 5eb63b48  
I/DEBUG   (  126):     5eb63a58 54414449 5c8a9e08 625cb208 5c8a9fcc  
I/DEBUG   (  126):     5eb63a68 5eb63b48 54414449 00000000 5c8a9f40  
I/DEBUG   (  126):     5eb63a78 4042c7fd 403de27f 40376264 0007ffff  
I/DEBUG   (  126):     5eb63a88 625cb208 00000001 5c8a9e08 00000000  
I/DEBUG   (  126):     5eb63a98 5eb63b48 00000001 00000000 00000000  
I/DEBUG   (  126):     5eb63aa8 00000001 403de30b 5a91bb68 000007d1  
I/DEBUG   (  126):     5eb63ab8 5c8a9e08 00000000 00000001 4039383c  
I/DEBUG   (  126):     5eb63ac8 5eb63b1f 5eb63b3c 5eb63b38 00000000  
I/DEBUG   (  126):     5eb63ad8 00000000 00000000 5c8a9e08 5c8a9da8  
I/DEBUG   (  126):     5eb63ae8 5c9108b0 5a6375f8 00000000 5b42dfb8  
I/DEBUG   (  126):     5eb63af8 00000001 00000001 00000000 00000000  
I/DEBUG   (  126):     5eb63b08 00000000 00000000 00000000 00000000  
I/DEBUG   (  126): 
I/DEBUG   (  126): code around pc:
I/DEBUG   (  126):     4014666c f5d1f080 f5d1f0c0 f5d1f100 f421020d  
I/DEBUG   (  126):     4014667c f421420d f5d1f100 e2522040 f400022d  
I/DEBUG   (  126):     4014668c f400422d 2afffff8 e2822040 e2522020  
I/DEBUG   (  126):     4014669c 3a000003 f421020d e2522020 f400022d  
I/DEBUG   (  126):     401466ac 2afffffb e2822020 e3120010 0a000001  
I/DEBUG   (  126):     401466bc f4210a0d f4000a2d e1b0ce82 3a000001  
I/DEBUG   (  126):     401466cc f421070d f400070d aa000001 f4a1030d  
I/DEBUG   (  126):     401466dc f480030d e1b0cf82 44d13001 24d1c001  
I/DEBUG   (  126):     401466ec 24d1e001 44c03001 24c0c001 24c0e001  
I/DEBUG   (  126):     401466fc e8bd4001 e12fff1e e1a02001 e3a01000  
I/DEBUG   (  126):     4014670c e92d40f1 e2603000 e2133003 e1530002  
I/DEBUG   (  126):     4014671c 81a03002 e1a01c01 e1811421 e1811821  
I/DEBUG   (  126):     4014672c e1b0cf83 24c01001 24c01001 44c01001  
I/DEBUG   (  126):     4014673c e0522003 98bd40f1 912fff1e e1a0c001  
I/DEBUG   (  126):     4014674c e1a0e001 e1a04001 e1a05001 e1a06001  
I/DEBUG   (  126):     4014675c e1a07001 e2603000 e213301c 0a000008  
I/DEBUG   (  126): 
I/DEBUG   (  126): code around lr:
I/DEBUG   (  126):     403e84b0 2f012180 ea4fbf18 32010167 460f9801  
I/DEBUG   (  126):     403e84c0 d3a64282 4350e005 08c23007 f7364620  
I/DEBUG   (  126):     403e84d0 b007eb8c 8ff0e8bd 118cf8d0 29009102  
I/DEBUG   (  126):     403e84e0 f8d0d0f7 22041134 01b0f8d0 f4012780  
I/DEBUG   (  126):     403e84f0 26003180 0e01f100 0901f04f 3b91ea82  
I/DEBUG   (  126):     403e8500 0203f06f 3c51eb02 465a0b89 ea179104  
I/DEBUG   (  126):     403e8510 d0250f0a 2a002100 2101bfa8 0504f1c2  
I/DEBUG   (  126):     403e8520 f04f4589 f04f0100 bf180800 2d002101  
I/DEBUG   (  126):     403e8530 f04fbfa8 23000801 bf1845c1 40192301  
I/DEBUG   (  126):     403e8540 80ddf040 1000f89e 700ff640 fa207823  
I/DEBUG   (  126):     403e8550 40d1f505 f001401d 4091010f 70214329  
I/DEBUG   (  126):     403e8560 428a9904 3401d104 0e01f10e e01d465a  
I/DEBUG   (  126):     403e8570 0f00f1bc 0500f04f 0100f04f 2501bfa8  
I/DEBUG   (  126):     403e8580 bfa82a00 42a92101 0500f04f f04f4462  
I/DEBUG   (  126):     403e8590 bf080300 2a002501 2301bfa8 f04f4299  
I/DEBUG   (  126):     403e85a0 bf180100 40292101 80a9f040 2f012180  
I/DEBUG   (  126): 
I/DEBUG   (  126): memory map around fault addr 625cc000:
I/DEBUG   (  126):     61e2a000-625cc000 
I/DEBUG   (  126):     (no map for address)
I/DEBUG   (  126):     bef2a000-bef4b000 [stack]

**Comment by davemorrissey** [comment]
The error is thrown by the skia library so you'll need to report it to them or Google. They haven't yet responded to my bug reports so I can only suggest you try saving the image with another graphics package.

**Comment by shmoula** [comment]
Thanks for reply, dave. I'll try to!

**Comment by LeonScroggins** [comment]
Hi Dave,

When you say "They haven't yet responded to my bug reports," do you mean Skia? Sorry if we (Skia) have been unresponsive :(

For any future Skia bugs, if they are image decoding related (like this one) feel free to assign it to me (scroggo@google.com). For more general Android (Skia) bugs, djsollen@ should be able to route it. Otherwise hcm@ typically handles our bug triage.

**Comment by davemorrissey** [comment]
Hi Leon, thanks for your message. Actually I raised the bug in the Android issues tracker because I wasn't sure where it should be reported. See this link https://code.google.com/p/android/issues/detail?id=76976

In future I will report them direct to the skia issue tracker, but unfortunately it's often hard to determine what's different about an image that fails to decode. I use ImageMagick to check all the attributes but sometimes draw a blank. It appears the problems usually occur with CMYK and grayscale images, and those with unusual subsampling, but I've also had reports of decoding problems for images with nothing obviously out of the ordinary. Anecdotally, Android 5 has more problems than earlier versions, but that could be due to Android itself, manufacturer alterations or hardware.

If you release fixes to Skia, how long does it take for them to be incorporated into Android releases?

**Comment by LeonScroggins** [comment]
> Actually I raised the bug in the Android issues tracker because I wasn't sure where it should be
> reported. See this link https://code.google.com/p/android/issues/detail?id=76976

That seems like a reasonably place, although I am not aware of issues there being actively triaged. If have a bug that you think is Skia (drawing or image decoding related), I would recommend filing a bug with https://code.google.com/p/skia/. I have filed your bug as skbug.com/4264, and I or a coworker will take a look.

> Anecdotally, Android 5 has more problems than earlier versions, but that could be due to Android
> itself, manufacturer alterations or hardware.

Nothing comes to mind as a problem specifically related to Android 5, but BitmapRegionDecoder relies on some Android-specific modifications to libpng and libjpeg. We've had a few instances where we upgraded our versions of those libraries and our modifications no longer worked. We're actively working to fix this problem though.

> If you release fixes to Skia, how long does it take for them to be incorporated into Android releases?

In general, a fix to Skia will go into the next Android release. The window for M has passed, but any fixes to Skia made today will go into the following release
